/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.luopc.platform.quantlib;

public class AnalyticPDFHestonEngine extends PricingEngine {
  private transient long swigCPtr;
  private transient boolean swigCMemOwnDerived;

  protected AnalyticPDFHestonEngine(long cPtr, boolean cMemoryOwn) {
    super(QuantLibJNI.AnalyticPDFHestonEngine_SWIGSmartPtrUpcast(cPtr), true);
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(AnalyticPDFHestonEngine obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void swigSetCMemOwn(boolean own) {
    swigCMemOwnDerived = own;
    super.swigSetCMemOwn(own);
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwnDerived) {
        swigCMemOwnDerived = false;
        QuantLibJNI.delete_AnalyticPDFHestonEngine(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public AnalyticPDFHestonEngine(HestonModel model, double gaussLobattoEps, long gaussLobattoIntegrationOrder) {
    this(QuantLibJNI.new_AnalyticPDFHestonEngine__SWIG_0(HestonModel.getCPtr(model), model, gaussLobattoEps, gaussLobattoIntegrationOrder), true);
  }

  public AnalyticPDFHestonEngine(HestonModel model, double gaussLobattoEps) {
    this(QuantLibJNI.new_AnalyticPDFHestonEngine__SWIG_1(HestonModel.getCPtr(model), model, gaussLobattoEps), true);
  }

  public AnalyticPDFHestonEngine(HestonModel model) {
    this(QuantLibJNI.new_AnalyticPDFHestonEngine__SWIG_2(HestonModel.getCPtr(model), model), true);
  }

}
