/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.4.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.luopc.platform.quantlib;

public class AnalyticTwoAssetCorrelationEngine extends PricingEngine {
  private transient long swigCPtr;
  private transient boolean swigCMemOwnDerived;

  protected AnalyticTwoAssetCorrelationEngine(long cPtr, boolean cMemoryOwn) {
    super(QuantLibJNI.AnalyticTwoAssetCorrelationEngine_SWIGSmartPtrUpcast(cPtr), true);
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(AnalyticTwoAssetCorrelationEngine obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void swigSetCMemOwn(boolean own) {
    swigCMemOwnDerived = own;
    super.swigSetCMemOwn(own);
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwnDerived) {
        swigCMemOwnDerived = false;
        QuantLibJNI.delete_AnalyticTwoAssetCorrelationEngine(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public AnalyticTwoAssetCorrelationEngine(GeneralizedBlackScholesProcess p1, GeneralizedBlackScholesProcess p2, QuoteHandle correlation) {
    this(QuantLibJNI.new_AnalyticTwoAssetCorrelationEngine(GeneralizedBlackScholesProcess.getCPtr(p1), p1, GeneralizedBlackScholesProcess.getCPtr(p2), p2, QuoteHandle.getCPtr(correlation), correlation), true);
  }

}
