/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.luopc.platform.quantlib;

public class ArithmeticAveragedOvernightIndexedCouponPricer extends FloatingRateCouponPricer {
  private transient long swigCPtr;
  private transient boolean swigCMemOwnDerived;

  protected ArithmeticAveragedOvernightIndexedCouponPricer(long cPtr, boolean cMemoryOwn) {
    super(QuantLibJNI.ArithmeticAveragedOvernightIndexedCouponPricer_SWIGSmartPtrUpcast(cPtr), true);
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ArithmeticAveragedOvernightIndexedCouponPricer obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void swigSetCMemOwn(boolean own) {
    swigCMemOwnDerived = own;
    super.swigSetCMemOwn(own);
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwnDerived) {
        swigCMemOwnDerived = false;
        QuantLibJNI.delete_ArithmeticAveragedOvernightIndexedCouponPricer(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public ArithmeticAveragedOvernightIndexedCouponPricer(double meanReversion, double volatility, boolean byApprox) {
    this(QuantLibJNI.new_ArithmeticAveragedOvernightIndexedCouponPricer__SWIG_0(meanReversion, volatility, byApprox), true);
  }

  public ArithmeticAveragedOvernightIndexedCouponPricer(double meanReversion, double volatility) {
    this(QuantLibJNI.new_ArithmeticAveragedOvernightIndexedCouponPricer__SWIG_1(meanReversion, volatility), true);
  }

  public ArithmeticAveragedOvernightIndexedCouponPricer(double meanReversion) {
    this(QuantLibJNI.new_ArithmeticAveragedOvernightIndexedCouponPricer__SWIG_2(meanReversion), true);
  }

  public ArithmeticAveragedOvernightIndexedCouponPricer() {
    this(QuantLibJNI.new_ArithmeticAveragedOvernightIndexedCouponPricer__SWIG_3(), true);
  }

}
