/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.luopc.platform.quantlib;

public class BinomialJ4ConvertibleEngine extends PricingEngine {
  private transient long swigCPtr;
  private transient boolean swigCMemOwnDerived;

  protected BinomialJ4ConvertibleEngine(long cPtr, boolean cMemoryOwn) {
    super(QuantLibJNI.BinomialJ4ConvertibleEngine_SWIGSmartPtrUpcast(cPtr), true);
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(BinomialJ4ConvertibleEngine obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void swigSetCMemOwn(boolean own) {
    swigCMemOwnDerived = own;
    super.swigSetCMemOwn(own);
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwnDerived) {
        swigCMemOwnDerived = false;
        QuantLibJNI.delete_BinomialJ4ConvertibleEngine(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public BinomialJ4ConvertibleEngine(GeneralizedBlackScholesProcess arg0, long steps, QuoteHandle creditSpread, DividendSchedule dividends) {
    this(QuantLibJNI.new_BinomialJ4ConvertibleEngine__SWIG_0(GeneralizedBlackScholesProcess.getCPtr(arg0), arg0, steps, QuoteHandle.getCPtr(creditSpread), creditSpread, DividendSchedule.getCPtr(dividends), dividends), true);
  }

  public BinomialJ4ConvertibleEngine(GeneralizedBlackScholesProcess arg0, long steps, QuoteHandle creditSpread) {
    this(QuantLibJNI.new_BinomialJ4ConvertibleEngine__SWIG_1(GeneralizedBlackScholesProcess.getCPtr(arg0), arg0, steps, QuoteHandle.getCPtr(creditSpread), creditSpread), true);
  }

}
