/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.luopc.platform.quantlib;

public class BoxMullerXoshiro256StarStarGaussianRng {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected BoxMullerXoshiro256StarStarGaussianRng(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(BoxMullerXoshiro256StarStarGaussianRng obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        QuantLibJNI.delete_BoxMullerXoshiro256StarStarGaussianRng(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public BoxMullerXoshiro256StarStarGaussianRng(Xoshiro256StarStarUniformRng rng) {
    this(QuantLibJNI.new_BoxMullerXoshiro256StarStarGaussianRng(Xoshiro256StarStarUniformRng.getCPtr(rng), rng), true);
  }

  public SampleNumber next() {
    return new SampleNumber(QuantLibJNI.BoxMullerXoshiro256StarStarGaussianRng_next(swigCPtr, this), true);
  }

}
