/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.luopc.platform.quantlib;

public class Burley2020SobolRsg {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Burley2020SobolRsg(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Burley2020SobolRsg obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(Burley2020SobolRsg obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        QuantLibJNI.delete_Burley2020SobolRsg(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Burley2020SobolRsg(long dimensionality, int seed, SobolRsg.DirectionIntegers directionIntegers, int scrambleSeed) {
    this(QuantLibJNI.new_Burley2020SobolRsg__SWIG_0(dimensionality, seed, directionIntegers.swigValue(), scrambleSeed), true);
  }

  public Burley2020SobolRsg(long dimensionality, int seed, SobolRsg.DirectionIntegers directionIntegers) {
    this(QuantLibJNI.new_Burley2020SobolRsg__SWIG_1(dimensionality, seed, directionIntegers.swigValue()), true);
  }

  public Burley2020SobolRsg(long dimensionality, int seed) {
    this(QuantLibJNI.new_Burley2020SobolRsg__SWIG_2(dimensionality, seed), true);
  }

  public Burley2020SobolRsg(long dimensionality) {
    this(QuantLibJNI.new_Burley2020SobolRsg__SWIG_3(dimensionality), true);
  }

  public SampleRealVector nextSequence() {
    return new SampleRealVector(QuantLibJNI.Burley2020SobolRsg_nextSequence(swigCPtr, this), false);
  }

  public SampleRealVector lastSequence() {
    return new SampleRealVector(QuantLibJNI.Burley2020SobolRsg_lastSequence(swigCPtr, this), false);
  }

  public long dimension() {
    return QuantLibJNI.Burley2020SobolRsg_dimension(swigCPtr, this);
  }

  public UnsignedIntVector nextInt32Sequence() {
    return new UnsignedIntVector(QuantLibJNI.Burley2020SobolRsg_nextInt32Sequence(swigCPtr, this), true);
  }

}
