/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.luopc.platform.quantlib;

public class Burley2020SobolBrownianBridgeRsg {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Burley2020SobolBrownianBridgeRsg(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Burley2020SobolBrownianBridgeRsg obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        QuantLibJNI.delete_Burley2020SobolBrownianBridgeRsg(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Burley2020SobolBrownianBridgeRsg(long factors, long steps) {
    this(QuantLibJNI.new_Burley2020SobolBrownianBridgeRsg(factors, steps), true);
  }

  public SampleRealVector nextSequence() {
    return new SampleRealVector(QuantLibJNI.Burley2020SobolBrownianBridgeRsg_nextSequence(swigCPtr, this), false);
  }

  public SampleRealVector lastSequence() {
    return new SampleRealVector(QuantLibJNI.Burley2020SobolBrownianBridgeRsg_lastSequence(swigCPtr, this), false);
  }

  public long dimension() {
    return QuantLibJNI.Burley2020SobolBrownianBridgeRsg_dimension(swigCPtr, this);
  }

}
