/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.4.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.luopc.platform.quantlib;

public class CalendarVector extends java.util.AbstractList<Calendar> implements java.util.RandomAccess {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected CalendarVector(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CalendarVector obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(CalendarVector obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        QuantLibJNI.delete_CalendarVector(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  @SuppressWarnings("this-escape")
  public CalendarVector(Calendar[] initialElements) {
    this();
    doReserve(initialElements.length);

    for (Calendar element : initialElements) {
      doAdd(element);
    }
  }

  @SuppressWarnings("this-escape")
  public CalendarVector(Iterable<Calendar> initialElements) {
    this();
    for (Calendar element : initialElements) {
      doAdd(element);
    }
  }

  public Calendar get(int index) {
    return doGet(index);
  }

  public Calendar set(int index, Calendar e) {
    return doSet(index, e);
  }

  public boolean add(Calendar e) {
    modCount++;
    doAdd(e);
    return true;
  }

  public void add(int index, Calendar e) {
    modCount++;
    doAdd(index, e);
  }

  public Calendar remove(int index) {
    modCount++;
    return doRemove(index);
  }

  protected void removeRange(int fromIndex, int toIndex) {
    modCount++;
    doRemoveRange(fromIndex, toIndex);
  }

  public int size() {
    return doSize();
  }

  public int capacity() {
    return doCapacity();
  }

  public void reserve(int n) {
    doReserve(n);
  }

  public CalendarVector() {
    this(QuantLibJNI.new_CalendarVector__SWIG_0(), true);
  }

  public CalendarVector(CalendarVector other) {
    this(QuantLibJNI.new_CalendarVector__SWIG_1(CalendarVector.getCPtr(other), other), true);
  }

  public boolean isEmpty() {
    return QuantLibJNI.CalendarVector_isEmpty(swigCPtr, this);
  }

  public void clear() {
    QuantLibJNI.CalendarVector_clear(swigCPtr, this);
  }

  public CalendarVector(int count, Calendar value) {
    this(QuantLibJNI.new_CalendarVector__SWIG_2(count, Calendar.getCPtr(value), value), true);
  }

  private int doCapacity() {
    return QuantLibJNI.CalendarVector_doCapacity(swigCPtr, this);
  }

  private void doReserve(int n) {
    QuantLibJNI.CalendarVector_doReserve(swigCPtr, this, n);
  }

  private int doSize() {
    return QuantLibJNI.CalendarVector_doSize(swigCPtr, this);
  }

  private void doAdd(Calendar x) {
    QuantLibJNI.CalendarVector_doAdd__SWIG_0(swigCPtr, this, Calendar.getCPtr(x), x);
  }

  private void doAdd(int index, Calendar x) {
    QuantLibJNI.CalendarVector_doAdd__SWIG_1(swigCPtr, this, index, Calendar.getCPtr(x), x);
  }

  private Calendar doRemove(int index) {
    return new Calendar(QuantLibJNI.CalendarVector_doRemove(swigCPtr, this, index), true);
  }

  private Calendar doGet(int index) {
    return new Calendar(QuantLibJNI.CalendarVector_doGet(swigCPtr, this, index), false);
  }

  private Calendar doSet(int index, Calendar val) {
    return new Calendar(QuantLibJNI.CalendarVector_doSet(swigCPtr, this, index, Calendar.getCPtr(val), val), true);
  }

  private void doRemoveRange(int fromIndex, int toIndex) {
    QuantLibJNI.CalendarVector_doRemoveRange(swigCPtr, this, fromIndex, toIndex);
  }

}
