/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.4.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.luopc.platform.quantlib;

public class CalibrationErrorTuple {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected CalibrationErrorTuple(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CalibrationErrorTuple obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(CalibrationErrorTuple obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        QuantLibJNI.delete_CalibrationErrorTuple(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public CalibrationErrorTuple(double arg0, double arg1, double arg2) {
    this(QuantLibJNI.new_CalibrationErrorTuple(arg0, arg1, arg2), true);
  }

  public double first() {
    return QuantLibJNI.CalibrationErrorTuple_first(swigCPtr, this);
  }

  public double second() {
    return QuantLibJNI.CalibrationErrorTuple_second(swigCPtr, this);
  }

  public double third() {
    return QuantLibJNI.CalibrationErrorTuple_third(swigCPtr, this);
  }

}
