/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.luopc.platform.quantlib;

public class CashDividendEuropeanEngine extends PricingEngine {
  private transient long swigCPtr;
  private transient boolean swigCMemOwnDerived;

  protected CashDividendEuropeanEngine(long cPtr, boolean cMemoryOwn) {
    super(QuantLibJNI.CashDividendEuropeanEngine_SWIGSmartPtrUpcast(cPtr), true);
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CashDividendEuropeanEngine obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void swigSetCMemOwn(boolean own) {
    swigCMemOwnDerived = own;
    super.swigSetCMemOwn(own);
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwnDerived) {
        swigCMemOwnDerived = false;
        QuantLibJNI.delete_CashDividendEuropeanEngine(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public CashDividendEuropeanEngine(GeneralizedBlackScholesProcess process, DividendSchedule dividends, CashDividendEuropeanEngine.CashDividendModel cashDividendModel) {
    this(QuantLibJNI.new_CashDividendEuropeanEngine__SWIG_0(GeneralizedBlackScholesProcess.getCPtr(process), process, DividendSchedule.getCPtr(dividends), dividends, cashDividendModel.swigValue()), true);
  }

  public CashDividendEuropeanEngine(GeneralizedBlackScholesProcess process, DividendSchedule dividends) {
    this(QuantLibJNI.new_CashDividendEuropeanEngine__SWIG_1(GeneralizedBlackScholesProcess.getCPtr(process), process, DividendSchedule.getCPtr(dividends), dividends), true);
  }

  public final static class CashDividendModel {
    public final static CashDividendEuropeanEngine.CashDividendModel Spot = new CashDividendEuropeanEngine.CashDividendModel("Spot");
    public final static CashDividendEuropeanEngine.CashDividendModel Escrowed = new CashDividendEuropeanEngine.CashDividendModel("Escrowed");

    public final int swigValue() {
      return swigValue;
    }

    public String toString() {
      return swigName;
    }

    public static CashDividendModel swigToEnum(int swigValue) {
      if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
        return swigValues[swigValue];
      for (int i = 0; i < swigValues.length; i++)
        if (swigValues[i].swigValue == swigValue)
          return swigValues[i];
      throw new IllegalArgumentException("No enum " + CashDividendModel.class + " with value " + swigValue);
    }

    private CashDividendModel(String swigName) {
      this.swigName = swigName;
      this.swigValue = swigNext++;
    }

    private CashDividendModel(String swigName, int swigValue) {
      this.swigName = swigName;
      this.swigValue = swigValue;
      swigNext = swigValue+1;
    }

    private CashDividendModel(String swigName, CashDividendModel swigEnum) {
      this.swigName = swigName;
      this.swigValue = swigEnum.swigValue;
      swigNext = this.swigValue+1;
    }

    private static CashDividendModel[] swigValues = { Spot, Escrowed };
    private static int swigNext = 0;
    private final int swigValue;
    private final String swigName;
  }

}
