/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.luopc.platform.quantlib;

public class ChoiBasketEngine extends PricingEngine {
  private transient long swigCPtr;
  private transient boolean swigCMemOwnDerived;

  protected ChoiBasketEngine(long cPtr, boolean cMemoryOwn) {
    super(QuantLibJNI.ChoiBasketEngine_SWIGSmartPtrUpcast(cPtr), true);
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ChoiBasketEngine obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void swigSetCMemOwn(boolean own) {
    swigCMemOwnDerived = own;
    super.swigSetCMemOwn(own);
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwnDerived) {
        swigCMemOwnDerived = false;
        QuantLibJNI.delete_ChoiBasketEngine(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public ChoiBasketEngine(GeneralizedBlackScholesProcessVector processes, Matrix rho, double lambda, long maxNrIntegrationSteps, boolean calcfwdDelta, boolean controlVariate) {
    this(QuantLibJNI.new_ChoiBasketEngine__SWIG_0(GeneralizedBlackScholesProcessVector.getCPtr(processes), processes, Matrix.getCPtr(rho), rho, lambda, maxNrIntegrationSteps, calcfwdDelta, controlVariate), true);
  }

  public ChoiBasketEngine(GeneralizedBlackScholesProcessVector processes, Matrix rho, double lambda, long maxNrIntegrationSteps, boolean calcfwdDelta) {
    this(QuantLibJNI.new_ChoiBasketEngine__SWIG_1(GeneralizedBlackScholesProcessVector.getCPtr(processes), processes, Matrix.getCPtr(rho), rho, lambda, maxNrIntegrationSteps, calcfwdDelta), true);
  }

  public ChoiBasketEngine(GeneralizedBlackScholesProcessVector processes, Matrix rho, double lambda, long maxNrIntegrationSteps) {
    this(QuantLibJNI.new_ChoiBasketEngine__SWIG_2(GeneralizedBlackScholesProcessVector.getCPtr(processes), processes, Matrix.getCPtr(rho), rho, lambda, maxNrIntegrationSteps), true);
  }

  public ChoiBasketEngine(GeneralizedBlackScholesProcessVector processes, Matrix rho, double lambda) {
    this(QuantLibJNI.new_ChoiBasketEngine__SWIG_3(GeneralizedBlackScholesProcessVector.getCPtr(processes), processes, Matrix.getCPtr(rho), rho, lambda), true);
  }

  public ChoiBasketEngine(GeneralizedBlackScholesProcessVector processes, Matrix rho) {
    this(QuantLibJNI.new_ChoiBasketEngine__SWIG_4(GeneralizedBlackScholesProcessVector.getCPtr(processes), processes, Matrix.getCPtr(rho), rho), true);
  }

}
