/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.4.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.luopc.platform.quantlib;

public class CompoundingMultipleResetsPricer extends FloatingRateCouponPricer {
  private transient long swigCPtr;
  private transient boolean swigCMemOwnDerived;

  protected CompoundingMultipleResetsPricer(long cPtr, boolean cMemoryOwn) {
    super(QuantLibJNI.CompoundingMultipleResetsPricer_SWIGSmartPtrUpcast(cPtr), true);
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CompoundingMultipleResetsPricer obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void swigSetCMemOwn(boolean own) {
    swigCMemOwnDerived = own;
    super.swigSetCMemOwn(own);
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwnDerived) {
        swigCMemOwnDerived = false;
        QuantLibJNI.delete_CompoundingMultipleResetsPricer(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public CompoundingMultipleResetsPricer() {
    this(QuantLibJNI.new_CompoundingMultipleResetsPricer(), true);
  }

}
