/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.luopc.platform.quantlib;

public class ContinuousPartialFixedLookbackOption extends ContinuousFixedLookbackOption {
  private transient long swigCPtr;
  private transient boolean swigCMemOwnDerived;

  protected ContinuousPartialFixedLookbackOption(long cPtr, boolean cMemoryOwn) {
    super(QuantLibJNI.ContinuousPartialFixedLookbackOption_SWIGSmartPtrUpcast(cPtr), true);
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ContinuousPartialFixedLookbackOption obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void swigSetCMemOwn(boolean own) {
    swigCMemOwnDerived = own;
    super.swigSetCMemOwn(own);
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwnDerived) {
        swigCMemOwnDerived = false;
        QuantLibJNI.delete_ContinuousPartialFixedLookbackOption(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public ContinuousPartialFixedLookbackOption(Date lookbackPeriodStart, StrikedTypePayoff payoff, Exercise exercise) {
    this(QuantLibJNI.new_ContinuousPartialFixedLookbackOption(Date.getCPtr(lookbackPeriodStart), lookbackPeriodStart, StrikedTypePayoff.getCPtr(payoff), payoff, Exercise.getCPtr(exercise), exercise), true);
  }

}
