/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.luopc.platform.quantlib;

public class CubicInterpolation {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected CubicInterpolation(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CubicInterpolation obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        QuantLibJNI.delete_CubicInterpolation(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public final static class DerivativeApprox {
    public final static CubicInterpolation.DerivativeApprox Spline = new CubicInterpolation.DerivativeApprox("Spline");
    public final static CubicInterpolation.DerivativeApprox SplineOM1 = new CubicInterpolation.DerivativeApprox("SplineOM1");
    public final static CubicInterpolation.DerivativeApprox SplineOM2 = new CubicInterpolation.DerivativeApprox("SplineOM2");
    public final static CubicInterpolation.DerivativeApprox FourthOrder = new CubicInterpolation.DerivativeApprox("FourthOrder");
    public final static CubicInterpolation.DerivativeApprox Parabolic = new CubicInterpolation.DerivativeApprox("Parabolic");
    public final static CubicInterpolation.DerivativeApprox FritschButland = new CubicInterpolation.DerivativeApprox("FritschButland");
    public final static CubicInterpolation.DerivativeApprox Akima = new CubicInterpolation.DerivativeApprox("Akima");
    public final static CubicInterpolation.DerivativeApprox Kruger = new CubicInterpolation.DerivativeApprox("Kruger");
    public final static CubicInterpolation.DerivativeApprox Harmonic = new CubicInterpolation.DerivativeApprox("Harmonic");

    public final int swigValue() {
      return swigValue;
    }

    public String toString() {
      return swigName;
    }

    public static DerivativeApprox swigToEnum(int swigValue) {
      if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
        return swigValues[swigValue];
      for (int i = 0; i < swigValues.length; i++)
        if (swigValues[i].swigValue == swigValue)
          return swigValues[i];
      throw new IllegalArgumentException("No enum " + DerivativeApprox.class + " with value " + swigValue);
    }

    private DerivativeApprox(String swigName) {
      this.swigName = swigName;
      this.swigValue = swigNext++;
    }

    private DerivativeApprox(String swigName, int swigValue) {
      this.swigName = swigName;
      this.swigValue = swigValue;
      swigNext = swigValue+1;
    }

    private DerivativeApprox(String swigName, DerivativeApprox swigEnum) {
      this.swigName = swigName;
      this.swigValue = swigEnum.swigValue;
      swigNext = this.swigValue+1;
    }

    private static DerivativeApprox[] swigValues = { Spline, SplineOM1, SplineOM2, FourthOrder, Parabolic, FritschButland, Akima, Kruger, Harmonic };
    private static int swigNext = 0;
    private final int swigValue;
    private final String swigName;
  }

  public final static class BoundaryCondition {
    public final static CubicInterpolation.BoundaryCondition NotAKnot = new CubicInterpolation.BoundaryCondition("NotAKnot");
    public final static CubicInterpolation.BoundaryCondition FirstDerivative = new CubicInterpolation.BoundaryCondition("FirstDerivative");
    public final static CubicInterpolation.BoundaryCondition SecondDerivative = new CubicInterpolation.BoundaryCondition("SecondDerivative");
    public final static CubicInterpolation.BoundaryCondition Periodic = new CubicInterpolation.BoundaryCondition("Periodic");
    public final static CubicInterpolation.BoundaryCondition Lagrange = new CubicInterpolation.BoundaryCondition("Lagrange");

    public final int swigValue() {
      return swigValue;
    }

    public String toString() {
      return swigName;
    }

    public static BoundaryCondition swigToEnum(int swigValue) {
      if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
        return swigValues[swigValue];
      for (int i = 0; i < swigValues.length; i++)
        if (swigValues[i].swigValue == swigValue)
          return swigValues[i];
      throw new IllegalArgumentException("No enum " + BoundaryCondition.class + " with value " + swigValue);
    }

    private BoundaryCondition(String swigName) {
      this.swigName = swigName;
      this.swigValue = swigNext++;
    }

    private BoundaryCondition(String swigName, int swigValue) {
      this.swigName = swigName;
      this.swigValue = swigValue;
      swigNext = swigValue+1;
    }

    private BoundaryCondition(String swigName, BoundaryCondition swigEnum) {
      this.swigName = swigName;
      this.swigValue = swigEnum.swigValue;
      swigNext = this.swigValue+1;
    }

    private static BoundaryCondition[] swigValues = { NotAKnot, FirstDerivative, SecondDerivative, Periodic, Lagrange };
    private static int swigNext = 0;
    private final int swigValue;
    private final String swigName;
  }

}
