/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.luopc.platform.quantlib;

public class Cubic {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Cubic(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Cubic obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        QuantLibJNI.delete_Cubic(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Cubic(CubicInterpolation.DerivativeApprox da, boolean monotonic, CubicInterpolation.BoundaryCondition leftCondition, double leftConditionValue, CubicInterpolation.BoundaryCondition rightCondition, double rightConditionValue) {
    this(QuantLibJNI.new_Cubic__SWIG_0(da.swigValue(), monotonic, leftCondition.swigValue(), leftConditionValue, rightCondition.swigValue(), rightConditionValue), true);
  }

  public Cubic(CubicInterpolation.DerivativeApprox da, boolean monotonic, CubicInterpolation.BoundaryCondition leftCondition, double leftConditionValue, CubicInterpolation.BoundaryCondition rightCondition) {
    this(QuantLibJNI.new_Cubic__SWIG_1(da.swigValue(), monotonic, leftCondition.swigValue(), leftConditionValue, rightCondition.swigValue()), true);
  }

  public Cubic(CubicInterpolation.DerivativeApprox da, boolean monotonic, CubicInterpolation.BoundaryCondition leftCondition, double leftConditionValue) {
    this(QuantLibJNI.new_Cubic__SWIG_2(da.swigValue(), monotonic, leftCondition.swigValue(), leftConditionValue), true);
  }

  public Cubic(CubicInterpolation.DerivativeApprox da, boolean monotonic, CubicInterpolation.BoundaryCondition leftCondition) {
    this(QuantLibJNI.new_Cubic__SWIG_3(da.swigValue(), monotonic, leftCondition.swigValue()), true);
  }

  public Cubic(CubicInterpolation.DerivativeApprox da, boolean monotonic) {
    this(QuantLibJNI.new_Cubic__SWIG_4(da.swigValue(), monotonic), true);
  }

  public Cubic(CubicInterpolation.DerivativeApprox da) {
    this(QuantLibJNI.new_Cubic__SWIG_5(da.swigValue()), true);
  }

  public Cubic() {
    this(QuantLibJNI.new_Cubic__SWIG_6(), true);
  }

}
