/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.4.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.luopc.platform.quantlib;

public class CustomIborIndex extends IborIndex {
  private transient long swigCPtr;
  private transient boolean swigCMemOwnDerived;

  protected CustomIborIndex(long cPtr, boolean cMemoryOwn) {
    super(QuantLibJNI.CustomIborIndex_SWIGSmartPtrUpcast(cPtr), true);
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CustomIborIndex obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void swigSetCMemOwn(boolean own) {
    swigCMemOwnDerived = own;
    super.swigSetCMemOwn(own);
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwnDerived) {
        swigCMemOwnDerived = false;
        QuantLibJNI.delete_CustomIborIndex(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public CustomIborIndex(String familyName, Period tenor, long settlementDays, Currency currency, Calendar fixingCalendar, Calendar valueCalendar, Calendar maturityCalendar, BusinessDayConvention convention, boolean endOfMonth, DayCounter dayCounter, YieldTermStructureHandle h) {
    this(QuantLibJNI.new_CustomIborIndex__SWIG_0(familyName, Period.getCPtr(tenor), tenor, settlementDays, Currency.getCPtr(currency), currency, Calendar.getCPtr(fixingCalendar), fixingCalendar, Calendar.getCPtr(valueCalendar), valueCalendar, Calendar.getCPtr(maturityCalendar), maturityCalendar, convention.swigValue(), endOfMonth, DayCounter.getCPtr(dayCounter), dayCounter, YieldTermStructureHandle.getCPtr(h), h), true);
  }

  public CustomIborIndex(String familyName, Period tenor, long settlementDays, Currency currency, Calendar fixingCalendar, Calendar valueCalendar, Calendar maturityCalendar, BusinessDayConvention convention, boolean endOfMonth, DayCounter dayCounter) {
    this(QuantLibJNI.new_CustomIborIndex__SWIG_1(familyName, Period.getCPtr(tenor), tenor, settlementDays, Currency.getCPtr(currency), currency, Calendar.getCPtr(fixingCalendar), fixingCalendar, Calendar.getCPtr(valueCalendar), valueCalendar, Calendar.getCPtr(maturityCalendar), maturityCalendar, convention.swigValue(), endOfMonth, DayCounter.getCPtr(dayCounter), dayCounter), true);
  }

  public Calendar valueCalendar() {
    return new Calendar(QuantLibJNI.CustomIborIndex_valueCalendar(swigCPtr, this), true);
  }

  public Calendar maturityCalendar() {
    return new Calendar(QuantLibJNI.CustomIborIndex_maturityCalendar(swigCPtr, this), true);
  }

}
