/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.luopc.platform.quantlib;

public class Destr extends OvernightIndex {
  private transient long swigCPtr;
  private transient boolean swigCMemOwnDerived;

  protected Destr(long cPtr, boolean cMemoryOwn) {
    super(QuantLibJNI.Destr_SWIGSmartPtrUpcast(cPtr), true);
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Destr obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void swigSetCMemOwn(boolean own) {
    swigCMemOwnDerived = own;
    super.swigSetCMemOwn(own);
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwnDerived) {
        swigCMemOwnDerived = false;
        QuantLibJNI.delete_Destr(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public Destr(YieldTermStructureHandle h) {
    this(QuantLibJNI.new_Destr__SWIG_0(YieldTermStructureHandle.getCPtr(h), h), true);
  }

  public Destr() {
    this(QuantLibJNI.new_Destr__SWIG_1(), true);
  }

}
