/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.4.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.luopc.platform.quantlib;

public class EquityTotalReturnSwap extends Swap {
  private transient long swigCPtr;
  private transient boolean swigCMemOwnDerived;

  protected EquityTotalReturnSwap(long cPtr, boolean cMemoryOwn) {
    super(QuantLibJNI.EquityTotalReturnSwap_SWIGSmartPtrUpcast(cPtr), true);
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(EquityTotalReturnSwap obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void swigSetCMemOwn(boolean own) {
    swigCMemOwnDerived = own;
    super.swigSetCMemOwn(own);
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwnDerived) {
        swigCMemOwnDerived = false;
        QuantLibJNI.delete_EquityTotalReturnSwap(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public EquityTotalReturnSwap(Swap.Type type, double nominal, Schedule schedule, EquityIndex equityIndex, IborIndex interestRateIndex, DayCounter dayCounter, double margin, double gearing, Calendar paymentCalendar, BusinessDayConvention paymentConvention, long paymentDelay) {
    this(QuantLibJNI.new_EquityTotalReturnSwap__SWIG_0(type.swigValue(), nominal, Schedule.getCPtr(schedule), schedule, EquityIndex.getCPtr(equityIndex), equityIndex, IborIndex.getCPtr(interestRateIndex), interestRateIndex, DayCounter.getCPtr(dayCounter), dayCounter, margin, gearing, Calendar.getCPtr(paymentCalendar), paymentCalendar, paymentConvention.swigValue(), paymentDelay), true);
  }

  public EquityTotalReturnSwap(Swap.Type type, double nominal, Schedule schedule, EquityIndex equityIndex, IborIndex interestRateIndex, DayCounter dayCounter, double margin, double gearing, Calendar paymentCalendar, BusinessDayConvention paymentConvention) {
    this(QuantLibJNI.new_EquityTotalReturnSwap__SWIG_1(type.swigValue(), nominal, Schedule.getCPtr(schedule), schedule, EquityIndex.getCPtr(equityIndex), equityIndex, IborIndex.getCPtr(interestRateIndex), interestRateIndex, DayCounter.getCPtr(dayCounter), dayCounter, margin, gearing, Calendar.getCPtr(paymentCalendar), paymentCalendar, paymentConvention.swigValue()), true);
  }

  public EquityTotalReturnSwap(Swap.Type type, double nominal, Schedule schedule, EquityIndex equityIndex, IborIndex interestRateIndex, DayCounter dayCounter, double margin, double gearing, Calendar paymentCalendar) {
    this(QuantLibJNI.new_EquityTotalReturnSwap__SWIG_2(type.swigValue(), nominal, Schedule.getCPtr(schedule), schedule, EquityIndex.getCPtr(equityIndex), equityIndex, IborIndex.getCPtr(interestRateIndex), interestRateIndex, DayCounter.getCPtr(dayCounter), dayCounter, margin, gearing, Calendar.getCPtr(paymentCalendar), paymentCalendar), true);
  }

  public EquityTotalReturnSwap(Swap.Type type, double nominal, Schedule schedule, EquityIndex equityIndex, IborIndex interestRateIndex, DayCounter dayCounter, double margin, double gearing) {
    this(QuantLibJNI.new_EquityTotalReturnSwap__SWIG_3(type.swigValue(), nominal, Schedule.getCPtr(schedule), schedule, EquityIndex.getCPtr(equityIndex), equityIndex, IborIndex.getCPtr(interestRateIndex), interestRateIndex, DayCounter.getCPtr(dayCounter), dayCounter, margin, gearing), true);
  }

  public EquityTotalReturnSwap(Swap.Type type, double nominal, Schedule schedule, EquityIndex equityIndex, IborIndex interestRateIndex, DayCounter dayCounter, double margin) {
    this(QuantLibJNI.new_EquityTotalReturnSwap__SWIG_4(type.swigValue(), nominal, Schedule.getCPtr(schedule), schedule, EquityIndex.getCPtr(equityIndex), equityIndex, IborIndex.getCPtr(interestRateIndex), interestRateIndex, DayCounter.getCPtr(dayCounter), dayCounter, margin), true);
  }

  public EquityTotalReturnSwap(Swap.Type type, double nominal, Schedule schedule, EquityIndex equityIndex, OvernightIndex interestRateIndex, DayCounter dayCounter, double margin, double gearing, Calendar paymentCalendar, BusinessDayConvention paymentConvention, long paymentDelay) {
    this(QuantLibJNI.new_EquityTotalReturnSwap__SWIG_5(type.swigValue(), nominal, Schedule.getCPtr(schedule), schedule, EquityIndex.getCPtr(equityIndex), equityIndex, OvernightIndex.getCPtr(interestRateIndex), interestRateIndex, DayCounter.getCPtr(dayCounter), dayCounter, margin, gearing, Calendar.getCPtr(paymentCalendar), paymentCalendar, paymentConvention.swigValue(), paymentDelay), true);
  }

  public EquityTotalReturnSwap(Swap.Type type, double nominal, Schedule schedule, EquityIndex equityIndex, OvernightIndex interestRateIndex, DayCounter dayCounter, double margin, double gearing, Calendar paymentCalendar, BusinessDayConvention paymentConvention) {
    this(QuantLibJNI.new_EquityTotalReturnSwap__SWIG_6(type.swigValue(), nominal, Schedule.getCPtr(schedule), schedule, EquityIndex.getCPtr(equityIndex), equityIndex, OvernightIndex.getCPtr(interestRateIndex), interestRateIndex, DayCounter.getCPtr(dayCounter), dayCounter, margin, gearing, Calendar.getCPtr(paymentCalendar), paymentCalendar, paymentConvention.swigValue()), true);
  }

  public EquityTotalReturnSwap(Swap.Type type, double nominal, Schedule schedule, EquityIndex equityIndex, OvernightIndex interestRateIndex, DayCounter dayCounter, double margin, double gearing, Calendar paymentCalendar) {
    this(QuantLibJNI.new_EquityTotalReturnSwap__SWIG_7(type.swigValue(), nominal, Schedule.getCPtr(schedule), schedule, EquityIndex.getCPtr(equityIndex), equityIndex, OvernightIndex.getCPtr(interestRateIndex), interestRateIndex, DayCounter.getCPtr(dayCounter), dayCounter, margin, gearing, Calendar.getCPtr(paymentCalendar), paymentCalendar), true);
  }

  public EquityTotalReturnSwap(Swap.Type type, double nominal, Schedule schedule, EquityIndex equityIndex, OvernightIndex interestRateIndex, DayCounter dayCounter, double margin, double gearing) {
    this(QuantLibJNI.new_EquityTotalReturnSwap__SWIG_8(type.swigValue(), nominal, Schedule.getCPtr(schedule), schedule, EquityIndex.getCPtr(equityIndex), equityIndex, OvernightIndex.getCPtr(interestRateIndex), interestRateIndex, DayCounter.getCPtr(dayCounter), dayCounter, margin, gearing), true);
  }

  public EquityTotalReturnSwap(Swap.Type type, double nominal, Schedule schedule, EquityIndex equityIndex, OvernightIndex interestRateIndex, DayCounter dayCounter, double margin) {
    this(QuantLibJNI.new_EquityTotalReturnSwap__SWIG_9(type.swigValue(), nominal, Schedule.getCPtr(schedule), schedule, EquityIndex.getCPtr(equityIndex), equityIndex, OvernightIndex.getCPtr(interestRateIndex), interestRateIndex, DayCounter.getCPtr(dayCounter), dayCounter, margin), true);
  }

  public Swap.Type type() {
    return Swap.Type.swigToEnum(QuantLibJNI.EquityTotalReturnSwap_type(swigCPtr, this));
  }

  public double nominal() {
    return QuantLibJNI.EquityTotalReturnSwap_nominal(swigCPtr, this);
  }

  public EquityIndex equityIndex() {
    long cPtr = QuantLibJNI.EquityTotalReturnSwap_equityIndex(swigCPtr, this);
    return (cPtr == 0) ? null : new EquityIndex(cPtr, true);
  }

  public InterestRateIndex interestRateIndex() {
    long cPtr = QuantLibJNI.EquityTotalReturnSwap_interestRateIndex(swigCPtr, this);
    return (cPtr == 0) ? null : new InterestRateIndex(cPtr, true);
  }

  public Schedule schedule() {
    return new Schedule(QuantLibJNI.EquityTotalReturnSwap_schedule(swigCPtr, this), false);
  }

  public DayCounter dayCounter() {
    return new DayCounter(QuantLibJNI.EquityTotalReturnSwap_dayCounter(swigCPtr, this), false);
  }

  public double margin() {
    return QuantLibJNI.EquityTotalReturnSwap_margin(swigCPtr, this);
  }

  public double gearing() {
    return QuantLibJNI.EquityTotalReturnSwap_gearing(swigCPtr, this);
  }

  public Calendar paymentCalendar() {
    return new Calendar(QuantLibJNI.EquityTotalReturnSwap_paymentCalendar(swigCPtr, this), false);
  }

  public BusinessDayConvention paymentConvention() {
    return BusinessDayConvention.swigToEnum(QuantLibJNI.EquityTotalReturnSwap_paymentConvention(swigCPtr, this));
  }

  public long paymentDelay() {
    return QuantLibJNI.EquityTotalReturnSwap_paymentDelay(swigCPtr, this);
  }

  public Leg equityLeg() {
    return new Leg(QuantLibJNI.EquityTotalReturnSwap_equityLeg(swigCPtr, this), false);
  }

  public Leg interestRateLeg() {
    return new Leg(QuantLibJNI.EquityTotalReturnSwap_interestRateLeg(swigCPtr, this), false);
  }

  public double equityLegNPV() {
    return QuantLibJNI.EquityTotalReturnSwap_equityLegNPV(swigCPtr, this);
  }

  public double interestRateLegNPV() {
    return QuantLibJNI.EquityTotalReturnSwap_interestRateLegNPV(swigCPtr, this);
  }

  public double fairMargin() {
    return QuantLibJNI.EquityTotalReturnSwap_fairMargin(swigCPtr, this);
  }

}
