/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.luopc.platform.quantlib;

public class EquityQuantoCashFlowPricer extends EquityCashFlowPricer {
  private transient long swigCPtr;
  private transient boolean swigCMemOwnDerived;

  protected EquityQuantoCashFlowPricer(long cPtr, boolean cMemoryOwn) {
    super(QuantLibJNI.EquityQuantoCashFlowPricer_SWIGSmartPtrUpcast(cPtr), true);
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(EquityQuantoCashFlowPricer obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void swigSetCMemOwn(boolean own) {
    swigCMemOwnDerived = own;
    super.swigSetCMemOwn(own);
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwnDerived) {
        swigCMemOwnDerived = false;
        QuantLibJNI.delete_EquityQuantoCashFlowPricer(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public EquityQuantoCashFlowPricer(YieldTermStructureHandle quantoCurrencyTermStructure, BlackVolTermStructureHandle equityVolatility, BlackVolTermStructureHandle fxVolatility, QuoteHandle correlation) {
    this(QuantLibJNI.new_EquityQuantoCashFlowPricer(YieldTermStructureHandle.getCPtr(quantoCurrencyTermStructure), quantoCurrencyTermStructure, BlackVolTermStructureHandle.getCPtr(equityVolatility), equityVolatility, BlackVolTermStructureHandle.getCPtr(fxVolatility), fxVolatility, QuoteHandle.getCPtr(correlation), correlation), true);
  }

}
