/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.4.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.luopc.platform.quantlib;

public class EverestOption extends MultiAssetOption {
  private transient long swigCPtr;
  private transient boolean swigCMemOwnDerived;

  protected EverestOption(long cPtr, boolean cMemoryOwn) {
    super(QuantLibJNI.EverestOption_SWIGSmartPtrUpcast(cPtr), true);
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(EverestOption obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void swigSetCMemOwn(boolean own) {
    swigCMemOwnDerived = own;
    super.swigSetCMemOwn(own);
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwnDerived) {
        swigCMemOwnDerived = false;
        QuantLibJNI.delete_EverestOption(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public EverestOption(double notional, double guarantee, Exercise exercise) {
    this(QuantLibJNI.new_EverestOption(notional, guarantee, Exercise.getCPtr(exercise), exercise), true);
  }

}
