/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.4.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.luopc.platform.quantlib;

public class ExpSinhIntegral {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ExpSinhIntegral(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ExpSinhIntegral obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(ExpSinhIntegral obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        QuantLibJNI.delete_ExpSinhIntegral(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public ExpSinhIntegral(double relTolerance, long maxRefinements) {
    this(QuantLibJNI.new_ExpSinhIntegral__SWIG_0(relTolerance, maxRefinements), true);
  }

  public ExpSinhIntegral(double relTolerance) {
    this(QuantLibJNI.new_ExpSinhIntegral__SWIG_1(relTolerance), true);
  }

  public ExpSinhIntegral() {
    this(QuantLibJNI.new_ExpSinhIntegral__SWIG_2(), true);
  }

  public double integrate(UnaryFunctionDelegate f) {
    return QuantLibJNI.ExpSinhIntegral_integrate(swigCPtr, this, UnaryFunctionDelegate.getCPtr(f), f);
  }

  public long numberOfEvaluations() {
    return QuantLibJNI.ExpSinhIntegral_numberOfEvaluations(swigCPtr, this);
  }

  public double calculate(UnaryFunctionDelegate f, double a, double b) {
    return QuantLibJNI.ExpSinhIntegral_calculate(swigCPtr, this, UnaryFunctionDelegate.getCPtr(f), f, a, b);
  }

}
