/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.4.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.luopc.platform.quantlib;

public class ExtendedCoxIngersollRoss extends CoxIngersollRoss {
  private transient long swigCPtr;
  private transient boolean swigCMemOwnDerived;

  protected ExtendedCoxIngersollRoss(long cPtr, boolean cMemoryOwn) {
    super(QuantLibJNI.ExtendedCoxIngersollRoss_SWIGSmartPtrUpcast(cPtr), true);
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ExtendedCoxIngersollRoss obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void swigSetCMemOwn(boolean own) {
    swigCMemOwnDerived = own;
    super.swigSetCMemOwn(own);
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwnDerived) {
        swigCMemOwnDerived = false;
        QuantLibJNI.delete_ExtendedCoxIngersollRoss(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public ExtendedCoxIngersollRoss(YieldTermStructureHandle termStructure, double theta, double k, double sigma, double x0) {
    this(QuantLibJNI.new_ExtendedCoxIngersollRoss__SWIG_0(YieldTermStructureHandle.getCPtr(termStructure), termStructure, theta, k, sigma, x0), true);
  }

  public ExtendedCoxIngersollRoss(YieldTermStructureHandle termStructure, double theta, double k, double sigma) {
    this(QuantLibJNI.new_ExtendedCoxIngersollRoss__SWIG_1(YieldTermStructureHandle.getCPtr(termStructure), termStructure, theta, k, sigma), true);
  }

  public ExtendedCoxIngersollRoss(YieldTermStructureHandle termStructure, double theta, double k) {
    this(QuantLibJNI.new_ExtendedCoxIngersollRoss__SWIG_2(YieldTermStructureHandle.getCPtr(termStructure), termStructure, theta, k), true);
  }

  public ExtendedCoxIngersollRoss(YieldTermStructureHandle termStructure, double theta) {
    this(QuantLibJNI.new_ExtendedCoxIngersollRoss__SWIG_3(YieldTermStructureHandle.getCPtr(termStructure), termStructure, theta), true);
  }

  public ExtendedCoxIngersollRoss(YieldTermStructureHandle termStructure) {
    this(QuantLibJNI.new_ExtendedCoxIngersollRoss__SWIG_4(YieldTermStructureHandle.getCPtr(termStructure), termStructure), true);
  }

  public YieldTermStructureHandle termStructure() {
    return new YieldTermStructureHandle(QuantLibJNI.ExtendedCoxIngersollRoss_termStructure(swigCPtr, this), false);
  }

}
