/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.4.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.luopc.platform.quantlib;

public class FixedVsFloatingSwap extends Swap {
  private transient long swigCPtr;
  private transient boolean swigCMemOwnDerived;

  protected FixedVsFloatingSwap(long cPtr, boolean cMemoryOwn) {
    super(QuantLibJNI.FixedVsFloatingSwap_SWIGSmartPtrUpcast(cPtr), true);
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(FixedVsFloatingSwap obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void swigSetCMemOwn(boolean own) {
    swigCMemOwnDerived = own;
    super.swigSetCMemOwn(own);
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwnDerived) {
        swigCMemOwnDerived = false;
        QuantLibJNI.delete_FixedVsFloatingSwap(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public Swap.Type type() {
    return Swap.Type.swigToEnum(QuantLibJNI.FixedVsFloatingSwap_type(swigCPtr, this));
  }

  public double nominal() {
    return QuantLibJNI.FixedVsFloatingSwap_nominal(swigCPtr, this);
  }

  public DoubleVector nominals() {
    return new DoubleVector(QuantLibJNI.FixedVsFloatingSwap_nominals(swigCPtr, this), true);
  }

  public DoubleVector fixedNominals() {
    return new DoubleVector(QuantLibJNI.FixedVsFloatingSwap_fixedNominals(swigCPtr, this), true);
  }

  public Schedule fixedSchedule() {
    return new Schedule(QuantLibJNI.FixedVsFloatingSwap_fixedSchedule(swigCPtr, this), false);
  }

  public double fixedRate() {
    return QuantLibJNI.FixedVsFloatingSwap_fixedRate(swigCPtr, this);
  }

  public DayCounter fixedDayCount() {
    return new DayCounter(QuantLibJNI.FixedVsFloatingSwap_fixedDayCount(swigCPtr, this), false);
  }

  public DoubleVector floatingNominals() {
    return new DoubleVector(QuantLibJNI.FixedVsFloatingSwap_floatingNominals(swigCPtr, this), true);
  }

  public Schedule floatingSchedule() {
    return new Schedule(QuantLibJNI.FixedVsFloatingSwap_floatingSchedule(swigCPtr, this), false);
  }

  public IborIndex iborIndex() {
    long cPtr = QuantLibJNI.FixedVsFloatingSwap_iborIndex(swigCPtr, this);
    return (cPtr == 0) ? null : new IborIndex(cPtr, true);
  }

  public double spread() {
    return QuantLibJNI.FixedVsFloatingSwap_spread(swigCPtr, this);
  }

  public DayCounter floatingDayCount() {
    return new DayCounter(QuantLibJNI.FixedVsFloatingSwap_floatingDayCount(swigCPtr, this), false);
  }

  public BusinessDayConvention paymentConvention() {
    return BusinessDayConvention.swigToEnum(QuantLibJNI.FixedVsFloatingSwap_paymentConvention(swigCPtr, this));
  }

  public Leg fixedLeg() {
    return new Leg(QuantLibJNI.FixedVsFloatingSwap_fixedLeg(swigCPtr, this), false);
  }

  public Leg floatingLeg() {
    return new Leg(QuantLibJNI.FixedVsFloatingSwap_floatingLeg(swigCPtr, this), false);
  }

  public double fixedLegBPS() {
    return QuantLibJNI.FixedVsFloatingSwap_fixedLegBPS(swigCPtr, this);
  }

  public double fixedLegNPV() {
    return QuantLibJNI.FixedVsFloatingSwap_fixedLegNPV(swigCPtr, this);
  }

  public double fairRate() {
    return QuantLibJNI.FixedVsFloatingSwap_fairRate(swigCPtr, this);
  }

  public double floatingLegBPS() {
    return QuantLibJNI.FixedVsFloatingSwap_floatingLegBPS(swigCPtr, this);
  }

  public double floatingLegNPV() {
    return QuantLibJNI.FixedVsFloatingSwap_floatingLegNPV(swigCPtr, this);
  }

  public double fairSpread() {
    return QuantLibJNI.FixedVsFloatingSwap_fairSpread(swigCPtr, this);
  }

}
