/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.luopc.platform.quantlib;

public class GaussChebyshev2ndIntegration extends GaussianQuadrature {
  private transient long swigCPtr;

  protected GaussChebyshev2ndIntegration(long cPtr, boolean cMemoryOwn) {
    super(QuantLibJNI.GaussChebyshev2ndIntegration_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(GaussChebyshev2ndIntegration obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        QuantLibJNI.delete_GaussChebyshev2ndIntegration(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public GaussChebyshev2ndIntegration(long n) {
    this(QuantLibJNI.new_GaussChebyshev2ndIntegration(n), true);
  }

}
