/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.luopc.platform.quantlib;

public class GaussHermiteIntegration extends GaussianQuadrature {
  private transient long swigCPtr;

  protected GaussHermiteIntegration(long cPtr, boolean cMemoryOwn) {
    super(QuantLibJNI.GaussHermiteIntegration_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(GaussHermiteIntegration obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        QuantLibJNI.delete_GaussHermiteIntegration(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public GaussHermiteIntegration(long n, double mu) {
    this(QuantLibJNI.new_GaussHermiteIntegration__SWIG_0(n, mu), true);
  }

  public GaussHermiteIntegration(long n) {
    this(QuantLibJNI.new_GaussHermiteIntegration__SWIG_1(n), true);
  }

}
