/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.luopc.platform.quantlib;

public class GaussHyperbolicIntegration extends GaussianQuadrature {
  private transient long swigCPtr;

  protected GaussHyperbolicIntegration(long cPtr, boolean cMemoryOwn) {
    super(QuantLibJNI.GaussHyperbolicIntegration_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(GaussHyperbolicIntegration obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        QuantLibJNI.delete_GaussHyperbolicIntegration(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public GaussHyperbolicIntegration(long n) {
    this(QuantLibJNI.new_GaussHyperbolicIntegration(n), true);
  }

}
