/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.4.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.luopc.platform.quantlib;

public class GeneralizedBlackScholesProcessVector extends java.util.AbstractList<GeneralizedBlackScholesProcess> implements java.util.RandomAccess {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected GeneralizedBlackScholesProcessVector(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(GeneralizedBlackScholesProcessVector obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(GeneralizedBlackScholesProcessVector obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        QuantLibJNI.delete_GeneralizedBlackScholesProcessVector(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  @SuppressWarnings("this-escape")
  public GeneralizedBlackScholesProcessVector(GeneralizedBlackScholesProcess[] initialElements) {
    this();
    doReserve(initialElements.length);

    for (GeneralizedBlackScholesProcess element : initialElements) {
      doAdd(element);
    }
  }

  @SuppressWarnings("this-escape")
  public GeneralizedBlackScholesProcessVector(Iterable<GeneralizedBlackScholesProcess> initialElements) {
    this();
    for (GeneralizedBlackScholesProcess element : initialElements) {
      doAdd(element);
    }
  }

  public GeneralizedBlackScholesProcess get(int index) {
    return doGet(index);
  }

  public GeneralizedBlackScholesProcess set(int index, GeneralizedBlackScholesProcess e) {
    return doSet(index, e);
  }

  public boolean add(GeneralizedBlackScholesProcess e) {
    modCount++;
    doAdd(e);
    return true;
  }

  public void add(int index, GeneralizedBlackScholesProcess e) {
    modCount++;
    doAdd(index, e);
  }

  public GeneralizedBlackScholesProcess remove(int index) {
    modCount++;
    return doRemove(index);
  }

  protected void removeRange(int fromIndex, int toIndex) {
    modCount++;
    doRemoveRange(fromIndex, toIndex);
  }

  public int size() {
    return doSize();
  }

  public int capacity() {
    return doCapacity();
  }

  public void reserve(int n) {
    doReserve(n);
  }

  public GeneralizedBlackScholesProcessVector() {
    this(QuantLibJNI.new_GeneralizedBlackScholesProcessVector__SWIG_0(), true);
  }

  public GeneralizedBlackScholesProcessVector(GeneralizedBlackScholesProcessVector other) {
    this(QuantLibJNI.new_GeneralizedBlackScholesProcessVector__SWIG_1(GeneralizedBlackScholesProcessVector.getCPtr(other), other), true);
  }

  public boolean isEmpty() {
    return QuantLibJNI.GeneralizedBlackScholesProcessVector_isEmpty(swigCPtr, this);
  }

  public void clear() {
    QuantLibJNI.GeneralizedBlackScholesProcessVector_clear(swigCPtr, this);
  }

  public GeneralizedBlackScholesProcessVector(int count, GeneralizedBlackScholesProcess value) {
    this(QuantLibJNI.new_GeneralizedBlackScholesProcessVector__SWIG_2(count, GeneralizedBlackScholesProcess.getCPtr(value), value), true);
  }

  private int doCapacity() {
    return QuantLibJNI.GeneralizedBlackScholesProcessVector_doCapacity(swigCPtr, this);
  }

  private void doReserve(int n) {
    QuantLibJNI.GeneralizedBlackScholesProcessVector_doReserve(swigCPtr, this, n);
  }

  private int doSize() {
    return QuantLibJNI.GeneralizedBlackScholesProcessVector_doSize(swigCPtr, this);
  }

  private void doAdd(GeneralizedBlackScholesProcess x) {
    QuantLibJNI.GeneralizedBlackScholesProcessVector_doAdd__SWIG_0(swigCPtr, this, GeneralizedBlackScholesProcess.getCPtr(x), x);
  }

  private void doAdd(int index, GeneralizedBlackScholesProcess x) {
    QuantLibJNI.GeneralizedBlackScholesProcessVector_doAdd__SWIG_1(swigCPtr, this, index, GeneralizedBlackScholesProcess.getCPtr(x), x);
  }

  private GeneralizedBlackScholesProcess doRemove(int index) {
    long cPtr = QuantLibJNI.GeneralizedBlackScholesProcessVector_doRemove(swigCPtr, this, index);
    return (cPtr == 0) ? null : new GeneralizedBlackScholesProcess(cPtr, true);
  }

  private GeneralizedBlackScholesProcess doGet(int index) {
    long cPtr = QuantLibJNI.GeneralizedBlackScholesProcessVector_doGet(swigCPtr, this, index);
    return (cPtr == 0) ? null : new GeneralizedBlackScholesProcess(cPtr, true);
  }

  private GeneralizedBlackScholesProcess doSet(int index, GeneralizedBlackScholesProcess val) {
    long cPtr = QuantLibJNI.GeneralizedBlackScholesProcessVector_doSet(swigCPtr, this, index, GeneralizedBlackScholesProcess.getCPtr(val), val);
    return (cPtr == 0) ? null : new GeneralizedBlackScholesProcess(cPtr, true);
  }

  private void doRemoveRange(int fromIndex, int toIndex) {
    QuantLibJNI.GeneralizedBlackScholesProcessVector_doRemoveRange(swigCPtr, this, fromIndex, toIndex);
  }

}
