/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.luopc.platform.quantlib;

public class GeometricBrownianMotionProcess extends StochasticProcess1D {
  private transient long swigCPtr;
  private transient boolean swigCMemOwnDerived;

  protected GeometricBrownianMotionProcess(long cPtr, boolean cMemoryOwn) {
    super(QuantLibJNI.GeometricBrownianMotionProcess_SWIGSmartPtrUpcast(cPtr), true);
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(GeometricBrownianMotionProcess obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void swigSetCMemOwn(boolean own) {
    swigCMemOwnDerived = own;
    super.swigSetCMemOwn(own);
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwnDerived) {
        swigCMemOwnDerived = false;
        QuantLibJNI.delete_GeometricBrownianMotionProcess(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public GeometricBrownianMotionProcess(double initialValue, double mu, double sigma) {
    this(QuantLibJNI.new_GeometricBrownianMotionProcess(initialValue, mu, sigma), true);
  }

}
