/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.4.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.luopc.platform.quantlib;

public class GlobalBootstrap {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected GlobalBootstrap(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(GlobalBootstrap obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(GlobalBootstrap obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        QuantLibJNI.delete_GlobalBootstrap(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public GlobalBootstrap(double accuracy, OptimizationMethod optimizer, EndCriteria endCriteria) {
    this(QuantLibJNI.new_GlobalBootstrap__SWIG_0(accuracy, OptimizationMethod.getCPtr(optimizer), optimizer, EndCriteria.getCPtr(endCriteria), endCriteria), true);
  }

  public GlobalBootstrap(double accuracy, OptimizationMethod optimizer) {
    this(QuantLibJNI.new_GlobalBootstrap__SWIG_1(accuracy, OptimizationMethod.getCPtr(optimizer), optimizer), true);
  }

  public GlobalBootstrap(double accuracy) {
    this(QuantLibJNI.new_GlobalBootstrap__SWIG_2(accuracy), true);
  }

  public GlobalBootstrap() {
    this(QuantLibJNI.new_GlobalBootstrap__SWIG_3(), true);
  }

  public GlobalBootstrap(RateHelperVector additionalHelpers, DateVector additionalDates, double accuracy, OptimizationMethod optimizer, EndCriteria endCriteria) {
    this(QuantLibJNI.new_GlobalBootstrap__SWIG_4(RateHelperVector.getCPtr(additionalHelpers), additionalHelpers, DateVector.getCPtr(additionalDates), additionalDates, accuracy, OptimizationMethod.getCPtr(optimizer), optimizer, EndCriteria.getCPtr(endCriteria), endCriteria), true);
  }

  public GlobalBootstrap(RateHelperVector additionalHelpers, DateVector additionalDates, double accuracy, OptimizationMethod optimizer) {
    this(QuantLibJNI.new_GlobalBootstrap__SWIG_5(RateHelperVector.getCPtr(additionalHelpers), additionalHelpers, DateVector.getCPtr(additionalDates), additionalDates, accuracy, OptimizationMethod.getCPtr(optimizer), optimizer), true);
  }

  public GlobalBootstrap(RateHelperVector additionalHelpers, DateVector additionalDates, double accuracy) {
    this(QuantLibJNI.new_GlobalBootstrap__SWIG_6(RateHelperVector.getCPtr(additionalHelpers), additionalHelpers, DateVector.getCPtr(additionalDates), additionalDates, accuracy), true);
  }

  public GlobalBootstrap(RateHelperVector additionalHelpers, DateVector additionalDates) {
    this(QuantLibJNI.new_GlobalBootstrap__SWIG_7(RateHelperVector.getCPtr(additionalHelpers), additionalHelpers, DateVector.getCPtr(additionalDates), additionalDates), true);
  }

}
