/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.luopc.platform.quantlib;

public class LazyObject extends Observable {
  private transient long swigCPtr;
  private transient boolean swigCMemOwnDerived;

  protected LazyObject(long cPtr, boolean cMemoryOwn) {
    super(QuantLibJNI.LazyObject_SWIGSmartPtrUpcast(cPtr), true);
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(LazyObject obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void swigSetCMemOwn(boolean own) {
    swigCMemOwnDerived = own;
    super.swigSetCMemOwn(own);
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwnDerived) {
        swigCMemOwnDerived = false;
        QuantLibJNI.delete_LazyObject(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public void recalculate() {
    QuantLibJNI.LazyObject_recalculate(swigCPtr, this);
  }

  public void freeze() {
    QuantLibJNI.LazyObject_freeze(swigCPtr, this);
  }

  public void unfreeze() {
    QuantLibJNI.LazyObject_unfreeze(swigCPtr, this);
  }

  public static void forwardFirstNotificationOnly() {
    QuantLibJNI.LazyObject_forwardFirstNotificationOnly();
  }

  public static void alwaysForwardNotifications() {
    QuantLibJNI.LazyObject_alwaysForwardNotifications();
  }

  public static boolean forwardsAllNotifications() {
    return QuantLibJNI.LazyObject_forwardsAllNotifications();
  }

}
