/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.luopc.platform.quantlib;

public class LMMDriftCalculator {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected LMMDriftCalculator(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(LMMDriftCalculator obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        QuantLibJNI.delete_LMMDriftCalculator(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public LMMDriftCalculator(Matrix pseudo, DoubleVector displacements, DoubleVector taus, long numeraire, long alive) {
    this(QuantLibJNI.new_LMMDriftCalculator(Matrix.getCPtr(pseudo), pseudo, DoubleVector.getCPtr(displacements), displacements, DoubleVector.getCPtr(taus), taus, numeraire, alive), true);
  }

  public void compute(LMMCurveState cs, DoubleVector drifts) {
    QuantLibJNI.LMMDriftCalculator_compute__SWIG_0(swigCPtr, this, LMMCurveState.getCPtr(cs), cs, DoubleVector.getCPtr(drifts), drifts);
  }

  public void compute(DoubleVector fwds, DoubleVector drifts) {
    QuantLibJNI.LMMDriftCalculator_compute__SWIG_1(swigCPtr, this, DoubleVector.getCPtr(fwds), fwds, DoubleVector.getCPtr(drifts), drifts);
  }

  public void computePlain(LMMCurveState cs, DoubleVector drifts) {
    QuantLibJNI.LMMDriftCalculator_computePlain__SWIG_0(swigCPtr, this, LMMCurveState.getCPtr(cs), cs, DoubleVector.getCPtr(drifts), drifts);
  }

  public void computePlain(DoubleVector fwds, DoubleVector drifts) {
    QuantLibJNI.LMMDriftCalculator_computePlain__SWIG_1(swigCPtr, this, DoubleVector.getCPtr(fwds), fwds, DoubleVector.getCPtr(drifts), drifts);
  }

  public void computeReduced(LMMCurveState cs, DoubleVector drifts) {
    QuantLibJNI.LMMDriftCalculator_computeReduced__SWIG_0(swigCPtr, this, LMMCurveState.getCPtr(cs), cs, DoubleVector.getCPtr(drifts), drifts);
  }

  public void computeReduced(DoubleVector fwds, DoubleVector drifts) {
    QuantLibJNI.LMMDriftCalculator_computeReduced__SWIG_1(swigCPtr, this, DoubleVector.getCPtr(fwds), fwds, DoubleVector.getCPtr(drifts), drifts);
  }

}
