/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.luopc.platform.quantlib;

public class LogCubicDiscountCurve extends YieldTermStructure {
  private transient long swigCPtr;
  private transient boolean swigCMemOwnDerived;

  protected LogCubicDiscountCurve(long cPtr, boolean cMemoryOwn) {
    super(QuantLibJNI.LogCubicDiscountCurve_SWIGSmartPtrUpcast(cPtr), true);
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(LogCubicDiscountCurve obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void swigSetCMemOwn(boolean own) {
    swigCMemOwnDerived = own;
    super.swigSetCMemOwn(own);
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwnDerived) {
        swigCMemOwnDerived = false;
        QuantLibJNI.delete_LogCubicDiscountCurve(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public LogCubicDiscountCurve(DateVector dates, DoubleVector discounts, DayCounter dayCounter, Calendar calendar, LogCubic i) {
    this(QuantLibJNI.new_LogCubicDiscountCurve__SWIG_0(DateVector.getCPtr(dates), dates, DoubleVector.getCPtr(discounts), discounts, DayCounter.getCPtr(dayCounter), dayCounter, Calendar.getCPtr(calendar), calendar, LogCubic.getCPtr(i), i), true);
  }

  public LogCubicDiscountCurve(DateVector dates, DoubleVector discounts, DayCounter dayCounter, Calendar calendar) {
    this(QuantLibJNI.new_LogCubicDiscountCurve__SWIG_1(DateVector.getCPtr(dates), dates, DoubleVector.getCPtr(discounts), discounts, DayCounter.getCPtr(dayCounter), dayCounter, Calendar.getCPtr(calendar), calendar), true);
  }

  public LogCubicDiscountCurve(DateVector dates, DoubleVector discounts, DayCounter dayCounter) {
    this(QuantLibJNI.new_LogCubicDiscountCurve__SWIG_2(DateVector.getCPtr(dates), dates, DoubleVector.getCPtr(discounts), discounts, DayCounter.getCPtr(dayCounter), dayCounter), true);
  }

  public DoubleVector times() {
    return new DoubleVector(QuantLibJNI.LogCubicDiscountCurve_times(swigCPtr, this), false);
  }

  public DoubleVector data() {
    return new DoubleVector(QuantLibJNI.LogCubicDiscountCurve_data(swigCPtr, this), false);
  }

  public DateVector dates() {
    return new DateVector(QuantLibJNI.LogCubicDiscountCurve_dates(swigCPtr, this), false);
  }

  public DoubleVector discounts() {
    return new DoubleVector(QuantLibJNI.LogCubicDiscountCurve_discounts(swigCPtr, this), false);
  }

  public NodeVector nodes() {
    return new NodeVector(QuantLibJNI.LogCubicDiscountCurve_nodes(swigCPtr, this), true);
  }

}
