/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.luopc.platform.quantlib;

public class LogMixedLinearCubic {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected LogMixedLinearCubic(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(LogMixedLinearCubic obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(LogMixedLinearCubic obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        QuantLibJNI.delete_LogMixedLinearCubic(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public LogMixedLinearCubic(long n, MixedInterpolation.Behavior behavior, CubicInterpolation.DerivativeApprox da, boolean monotonic, CubicInterpolation.BoundaryCondition leftCondition, double leftConditionValue, CubicInterpolation.BoundaryCondition rightCondition, double rightConditionValue) {
    this(QuantLibJNI.new_LogMixedLinearCubic__SWIG_0(n, behavior.swigValue(), da.swigValue(), monotonic, leftCondition.swigValue(), leftConditionValue, rightCondition.swigValue(), rightConditionValue), true);
  }

  public LogMixedLinearCubic(long n, MixedInterpolation.Behavior behavior, CubicInterpolation.DerivativeApprox da, boolean monotonic, CubicInterpolation.BoundaryCondition leftCondition, double leftConditionValue, CubicInterpolation.BoundaryCondition rightCondition) {
    this(QuantLibJNI.new_LogMixedLinearCubic__SWIG_1(n, behavior.swigValue(), da.swigValue(), monotonic, leftCondition.swigValue(), leftConditionValue, rightCondition.swigValue()), true);
  }

  public LogMixedLinearCubic(long n, MixedInterpolation.Behavior behavior, CubicInterpolation.DerivativeApprox da, boolean monotonic, CubicInterpolation.BoundaryCondition leftCondition, double leftConditionValue) {
    this(QuantLibJNI.new_LogMixedLinearCubic__SWIG_2(n, behavior.swigValue(), da.swigValue(), monotonic, leftCondition.swigValue(), leftConditionValue), true);
  }

  public LogMixedLinearCubic(long n, MixedInterpolation.Behavior behavior, CubicInterpolation.DerivativeApprox da, boolean monotonic, CubicInterpolation.BoundaryCondition leftCondition) {
    this(QuantLibJNI.new_LogMixedLinearCubic__SWIG_3(n, behavior.swigValue(), da.swigValue(), monotonic, leftCondition.swigValue()), true);
  }

  public LogMixedLinearCubic(long n, MixedInterpolation.Behavior behavior, CubicInterpolation.DerivativeApprox da, boolean monotonic) {
    this(QuantLibJNI.new_LogMixedLinearCubic__SWIG_4(n, behavior.swigValue(), da.swigValue(), monotonic), true);
  }

  public LogMixedLinearCubic(long n, MixedInterpolation.Behavior behavior, CubicInterpolation.DerivativeApprox da) {
    this(QuantLibJNI.new_LogMixedLinearCubic__SWIG_5(n, behavior.swigValue(), da.swigValue()), true);
  }

  public LogMixedLinearCubic(long n, MixedInterpolation.Behavior behavior) {
    this(QuantLibJNI.new_LogMixedLinearCubic__SWIG_6(n, behavior.swigValue()), true);
  }

  public LogMixedLinearCubic(long n) {
    this(QuantLibJNI.new_LogMixedLinearCubic__SWIG_7(n), true);
  }

  public LogMixedLinearCubic() {
    this(QuantLibJNI.new_LogMixedLinearCubic__SWIG_8(), true);
  }

}
