/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.4.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.luopc.platform.quantlib;

public class LogMixedLinearCubicSpreadDiscountCurve extends YieldTermStructure {
  private transient long swigCPtr;
  private transient boolean swigCMemOwnDerived;

  protected LogMixedLinearCubicSpreadDiscountCurve(long cPtr, boolean cMemoryOwn) {
    super(QuantLibJNI.LogMixedLinearCubicSpreadDiscountCurve_SWIGSmartPtrUpcast(cPtr), true);
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(LogMixedLinearCubicSpreadDiscountCurve obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void swigSetCMemOwn(boolean own) {
    swigCMemOwnDerived = own;
    super.swigSetCMemOwn(own);
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwnDerived) {
        swigCMemOwnDerived = false;
        QuantLibJNI.delete_LogMixedLinearCubicSpreadDiscountCurve(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public LogMixedLinearCubicSpreadDiscountCurve(YieldTermStructureHandle baseCurve, DateVector dates, DoubleVector dfs, LogMixedLinearCubic i) {
    this(QuantLibJNI.new_LogMixedLinearCubicSpreadDiscountCurve__SWIG_0(YieldTermStructureHandle.getCPtr(baseCurve), baseCurve, DateVector.getCPtr(dates), dates, DoubleVector.getCPtr(dfs), dfs, LogMixedLinearCubic.getCPtr(i), i), true);
  }

  public LogMixedLinearCubicSpreadDiscountCurve(YieldTermStructureHandle baseCurve, DateVector dates, DoubleVector dfs) {
    this(QuantLibJNI.new_LogMixedLinearCubicSpreadDiscountCurve__SWIG_1(YieldTermStructureHandle.getCPtr(baseCurve), baseCurve, DateVector.getCPtr(dates), dates, DoubleVector.getCPtr(dfs), dfs), true);
  }

  public YieldTermStructureHandle baseCurve() {
    return new YieldTermStructureHandle(QuantLibJNI.LogMixedLinearCubicSpreadDiscountCurve_baseCurve(swigCPtr, this), false);
  }

  public DoubleVector times() {
    return new DoubleVector(QuantLibJNI.LogMixedLinearCubicSpreadDiscountCurve_times(swigCPtr, this), false);
  }

  public DateVector dates() {
    return new DateVector(QuantLibJNI.LogMixedLinearCubicSpreadDiscountCurve_dates(swigCPtr, this), false);
  }

  public DoubleVector data() {
    return new DoubleVector(QuantLibJNI.LogMixedLinearCubicSpreadDiscountCurve_data(swigCPtr, this), false);
  }

  public NodeVector nodes() {
    return new NodeVector(QuantLibJNI.LogMixedLinearCubicSpreadDiscountCurve_nodes(swigCPtr, this), true);
  }

}
