/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.4.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.luopc.platform.quantlib;

public class MakeCreditDefaultSwap {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected MakeCreditDefaultSwap(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(MakeCreditDefaultSwap obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(MakeCreditDefaultSwap obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        QuantLibJNI.delete_MakeCreditDefaultSwap(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public MakeCreditDefaultSwap(Period tenor, double runningSpread) {
    this(QuantLibJNI.new_MakeCreditDefaultSwap__SWIG_0(Period.getCPtr(tenor), tenor, runningSpread), true);
  }

  public MakeCreditDefaultSwap(Date termDate, double runningSpread) {
    this(QuantLibJNI.new_MakeCreditDefaultSwap__SWIG_1(Date.getCPtr(termDate), termDate, runningSpread), true);
  }

  public CreditDefaultSwap makeCDS() {
    long cPtr = QuantLibJNI.MakeCreditDefaultSwap_makeCDS(swigCPtr, this);
    return (cPtr == 0) ? null : new CreditDefaultSwap(cPtr, true);
  }

  public MakeCreditDefaultSwap withUpfrontRate(double arg0) {
    return new MakeCreditDefaultSwap(QuantLibJNI.MakeCreditDefaultSwap_withUpfrontRate(swigCPtr, this, arg0), false);
  }

  public MakeCreditDefaultSwap withSide(Protection.Side arg0) {
    return new MakeCreditDefaultSwap(QuantLibJNI.MakeCreditDefaultSwap_withSide(swigCPtr, this, arg0.swigValue()), false);
  }

  public MakeCreditDefaultSwap withNominal(double arg0) {
    return new MakeCreditDefaultSwap(QuantLibJNI.MakeCreditDefaultSwap_withNominal(swigCPtr, this, arg0), false);
  }

  public MakeCreditDefaultSwap withCouponTenor(Period arg0) {
    return new MakeCreditDefaultSwap(QuantLibJNI.MakeCreditDefaultSwap_withCouponTenor(swigCPtr, this, Period.getCPtr(arg0), arg0), false);
  }

  public MakeCreditDefaultSwap withDayCounter(DayCounter arg0) {
    return new MakeCreditDefaultSwap(QuantLibJNI.MakeCreditDefaultSwap_withDayCounter(swigCPtr, this, DayCounter.getCPtr(arg0), arg0), false);
  }

  public MakeCreditDefaultSwap withLastPeriodDayCounter(DayCounter arg0) {
    return new MakeCreditDefaultSwap(QuantLibJNI.MakeCreditDefaultSwap_withLastPeriodDayCounter(swigCPtr, this, DayCounter.getCPtr(arg0), arg0), false);
  }

  public MakeCreditDefaultSwap withDateGenerationRule(DateGeneration.Rule rule) {
    return new MakeCreditDefaultSwap(QuantLibJNI.MakeCreditDefaultSwap_withDateGenerationRule(swigCPtr, this, rule.swigValue()), false);
  }

  public MakeCreditDefaultSwap withCashSettlementDays(long cashSettlementDays) {
    return new MakeCreditDefaultSwap(QuantLibJNI.MakeCreditDefaultSwap_withCashSettlementDays(swigCPtr, this, cashSettlementDays), false);
  }

  public MakeCreditDefaultSwap withPricingEngine(PricingEngine arg0) {
    return new MakeCreditDefaultSwap(QuantLibJNI.MakeCreditDefaultSwap_withPricingEngine(swigCPtr, this, PricingEngine.getCPtr(arg0), arg0), false);
  }

  public MakeCreditDefaultSwap withTradeDate(Date tradeDate) {
    return new MakeCreditDefaultSwap(QuantLibJNI.MakeCreditDefaultSwap_withTradeDate(swigCPtr, this, Date.getCPtr(tradeDate), tradeDate), false);
  }

}
