/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.luopc.platform.quantlib;

public class MakeCapFloor {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected MakeCapFloor(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(MakeCapFloor obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(MakeCapFloor obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        QuantLibJNI.delete_MakeCapFloor(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public MakeCapFloor withNominal(double n) {
    return new MakeCapFloor(QuantLibJNI.MakeCapFloor_withNominal(swigCPtr, this, n), false);
  }

  public MakeCapFloor withEffectiveDate(Date arg0, boolean firstCapletExcluded) {
    return new MakeCapFloor(QuantLibJNI.MakeCapFloor_withEffectiveDate(swigCPtr, this, Date.getCPtr(arg0), arg0, firstCapletExcluded), false);
  }

  public MakeCapFloor withTenor(Period arg0) {
    return new MakeCapFloor(QuantLibJNI.MakeCapFloor_withTenor(swigCPtr, this, Period.getCPtr(arg0), arg0), false);
  }

  public MakeCapFloor withCalendar(Calendar arg0) {
    return new MakeCapFloor(QuantLibJNI.MakeCapFloor_withCalendar(swigCPtr, this, Calendar.getCPtr(arg0), arg0), false);
  }

  public MakeCapFloor withConvention(BusinessDayConvention bdc) {
    return new MakeCapFloor(QuantLibJNI.MakeCapFloor_withConvention(swigCPtr, this, bdc.swigValue()), false);
  }

  public MakeCapFloor withTerminationDateConvention(BusinessDayConvention bdc) {
    return new MakeCapFloor(QuantLibJNI.MakeCapFloor_withTerminationDateConvention(swigCPtr, this, bdc.swigValue()), false);
  }

  public MakeCapFloor withRule(DateGeneration.Rule r) {
    return new MakeCapFloor(QuantLibJNI.MakeCapFloor_withRule(swigCPtr, this, r.swigValue()), false);
  }

  public MakeCapFloor withEndOfMonth(boolean flag) {
    return new MakeCapFloor(QuantLibJNI.MakeCapFloor_withEndOfMonth__SWIG_0(swigCPtr, this, flag), false);
  }

  public MakeCapFloor withEndOfMonth() {
    return new MakeCapFloor(QuantLibJNI.MakeCapFloor_withEndOfMonth__SWIG_1(swigCPtr, this), false);
  }

  public MakeCapFloor withFirstDate(Date arg0) {
    return new MakeCapFloor(QuantLibJNI.MakeCapFloor_withFirstDate(swigCPtr, this, Date.getCPtr(arg0), arg0), false);
  }

  public MakeCapFloor withNextToLastDate(Date arg0) {
    return new MakeCapFloor(QuantLibJNI.MakeCapFloor_withNextToLastDate(swigCPtr, this, Date.getCPtr(arg0), arg0), false);
  }

  public MakeCapFloor withDayCount(DayCounter arg0) {
    return new MakeCapFloor(QuantLibJNI.MakeCapFloor_withDayCount(swigCPtr, this, DayCounter.getCPtr(arg0), arg0), false);
  }

  public MakeCapFloor asOptionlet(boolean b) {
    return new MakeCapFloor(QuantLibJNI.MakeCapFloor_asOptionlet__SWIG_0(swigCPtr, this, b), false);
  }

  public MakeCapFloor asOptionlet() {
    return new MakeCapFloor(QuantLibJNI.MakeCapFloor_asOptionlet__SWIG_1(swigCPtr, this), false);
  }

  public MakeCapFloor withPricingEngine(PricingEngine engine) {
    return new MakeCapFloor(QuantLibJNI.MakeCapFloor_withPricingEngine(swigCPtr, this, PricingEngine.getCPtr(engine), engine), false);
  }

  public MakeCapFloor(CapFloor.Type capFloorType, Period capFloorTenor, IborIndex iborIndex, double strike, Period forwardStart) {
    this(QuantLibJNI.new_MakeCapFloor__SWIG_0(capFloorType.swigValue(), Period.getCPtr(capFloorTenor), capFloorTenor, IborIndex.getCPtr(iborIndex), iborIndex, strike, Period.getCPtr(forwardStart), forwardStart), true);
  }

  public MakeCapFloor(CapFloor.Type capFloorType, Period capFloorTenor, IborIndex iborIndex, double strike) {
    this(QuantLibJNI.new_MakeCapFloor__SWIG_1(capFloorType.swigValue(), Period.getCPtr(capFloorTenor), capFloorTenor, IborIndex.getCPtr(iborIndex), iborIndex, strike), true);
  }

  public MakeCapFloor(CapFloor.Type capFloorType, Period capFloorTenor, IborIndex iborIndex) {
    this(QuantLibJNI.new_MakeCapFloor__SWIG_2(capFloorType.swigValue(), Period.getCPtr(capFloorTenor), capFloorTenor, IborIndex.getCPtr(iborIndex), iborIndex), true);
  }

  public CapFloor makeCapFloor() {
    long cPtr = QuantLibJNI.MakeCapFloor_makeCapFloor(swigCPtr, this);
    return (cPtr == 0) ? null : new CapFloor(cPtr, true);
  }

}
