/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.luopc.platform.quantlib;

public class MarketModelFactory {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected MarketModelFactory(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(MarketModelFactory obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        QuantLibJNI.delete_MarketModelFactory(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public MarketModel create(EvolutionDescription arg0, long numberOfFactors) {
    long cPtr = QuantLibJNI.MarketModelFactory_create(swigCPtr, this, EvolutionDescription.getCPtr(arg0), arg0, numberOfFactors);
    return (cPtr == 0) ? null : new MarketModel(cPtr, true);
  }

}
