/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.luopc.platform.quantlib;

public class MixedInterpolation {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected MixedInterpolation(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(MixedInterpolation obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(MixedInterpolation obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        QuantLibJNI.delete_MixedInterpolation(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public final static class Behavior {
    public final static MixedInterpolation.Behavior ShareRanges = new MixedInterpolation.Behavior("ShareRanges");
    public final static MixedInterpolation.Behavior SplitRanges = new MixedInterpolation.Behavior("SplitRanges");

    public final int swigValue() {
      return swigValue;
    }

    public String toString() {
      return swigName;
    }

    public static Behavior swigToEnum(int swigValue) {
      if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
        return swigValues[swigValue];
      for (int i = 0; i < swigValues.length; i++)
        if (swigValues[i].swigValue == swigValue)
          return swigValues[i];
      throw new IllegalArgumentException("No enum " + Behavior.class + " with value " + swigValue);
    }

    private Behavior(String swigName) {
      this.swigName = swigName;
      this.swigValue = swigNext++;
    }

    private Behavior(String swigName, int swigValue) {
      this.swigName = swigName;
      this.swigValue = swigValue;
      swigNext = swigValue+1;
    }

    private Behavior(String swigName, Behavior swigEnum) {
      this.swigName = swigName;
      this.swigValue = swigEnum.swigValue;
      swigNext = this.swigValue+1;
    }

    private static Behavior[] swigValues = { ShareRanges, SplitRanges };
    private static int swigNext = 0;
    private final int swigValue;
    private final String swigName;
  }

}
