/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.luopc.platform.quantlib;

public class MonotonicParabolicCubic extends Cubic {
  private transient long swigCPtr;

  protected MonotonicParabolicCubic(long cPtr, boolean cMemoryOwn) {
    super(QuantLibJNI.MonotonicParabolicCubic_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(MonotonicParabolicCubic obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(MonotonicParabolicCubic obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        QuantLibJNI.delete_MonotonicParabolicCubic(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public MonotonicParabolicCubic() {
    this(QuantLibJNI.new_MonotonicParabolicCubic(), true);
  }

}
