/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.4.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.luopc.platform.quantlib;

public class MtMCrossCurrencyBasisSwapRateHelper extends RateHelper {
  private transient long swigCPtr;
  private transient boolean swigCMemOwnDerived;

  protected MtMCrossCurrencyBasisSwapRateHelper(long cPtr, boolean cMemoryOwn) {
    super(QuantLibJNI.MtMCrossCurrencyBasisSwapRateHelper_SWIGSmartPtrUpcast(cPtr), true);
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(MtMCrossCurrencyBasisSwapRateHelper obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void swigSetCMemOwn(boolean own) {
    swigCMemOwnDerived = own;
    super.swigSetCMemOwn(own);
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwnDerived) {
        swigCMemOwnDerived = false;
        QuantLibJNI.delete_MtMCrossCurrencyBasisSwapRateHelper(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public MtMCrossCurrencyBasisSwapRateHelper(QuoteHandle basis, Period tenor, long fixingDays, Calendar calendar, BusinessDayConvention convention, boolean endOfMonth, IborIndex baseCurrencyIndex, IborIndex quoteCurrencyIndex, YieldTermStructureHandle collateralCurve, boolean isFxBaseCurrencyCollateralCurrency, boolean isBasisOnFxBaseCurrencyLeg, boolean isFxBaseCurrencyLegResettable, Frequency paymentFrequency, int paymentLag) {
    this(QuantLibJNI.new_MtMCrossCurrencyBasisSwapRateHelper__SWIG_0(QuoteHandle.getCPtr(basis), basis, Period.getCPtr(tenor), tenor, fixingDays, Calendar.getCPtr(calendar), calendar, convention.swigValue(), endOfMonth, IborIndex.getCPtr(baseCurrencyIndex), baseCurrencyIndex, IborIndex.getCPtr(quoteCurrencyIndex), quoteCurrencyIndex, YieldTermStructureHandle.getCPtr(collateralCurve), collateralCurve, isFxBaseCurrencyCollateralCurrency, isBasisOnFxBaseCurrencyLeg, isFxBaseCurrencyLegResettable, paymentFrequency.swigValue(), paymentLag), true);
  }

  public MtMCrossCurrencyBasisSwapRateHelper(QuoteHandle basis, Period tenor, long fixingDays, Calendar calendar, BusinessDayConvention convention, boolean endOfMonth, IborIndex baseCurrencyIndex, IborIndex quoteCurrencyIndex, YieldTermStructureHandle collateralCurve, boolean isFxBaseCurrencyCollateralCurrency, boolean isBasisOnFxBaseCurrencyLeg, boolean isFxBaseCurrencyLegResettable, Frequency paymentFrequency) {
    this(QuantLibJNI.new_MtMCrossCurrencyBasisSwapRateHelper__SWIG_1(QuoteHandle.getCPtr(basis), basis, Period.getCPtr(tenor), tenor, fixingDays, Calendar.getCPtr(calendar), calendar, convention.swigValue(), endOfMonth, IborIndex.getCPtr(baseCurrencyIndex), baseCurrencyIndex, IborIndex.getCPtr(quoteCurrencyIndex), quoteCurrencyIndex, YieldTermStructureHandle.getCPtr(collateralCurve), collateralCurve, isFxBaseCurrencyCollateralCurrency, isBasisOnFxBaseCurrencyLeg, isFxBaseCurrencyLegResettable, paymentFrequency.swigValue()), true);
  }

  public MtMCrossCurrencyBasisSwapRateHelper(QuoteHandle basis, Period tenor, long fixingDays, Calendar calendar, BusinessDayConvention convention, boolean endOfMonth, IborIndex baseCurrencyIndex, IborIndex quoteCurrencyIndex, YieldTermStructureHandle collateralCurve, boolean isFxBaseCurrencyCollateralCurrency, boolean isBasisOnFxBaseCurrencyLeg, boolean isFxBaseCurrencyLegResettable) {
    this(QuantLibJNI.new_MtMCrossCurrencyBasisSwapRateHelper__SWIG_2(QuoteHandle.getCPtr(basis), basis, Period.getCPtr(tenor), tenor, fixingDays, Calendar.getCPtr(calendar), calendar, convention.swigValue(), endOfMonth, IborIndex.getCPtr(baseCurrencyIndex), baseCurrencyIndex, IborIndex.getCPtr(quoteCurrencyIndex), quoteCurrencyIndex, YieldTermStructureHandle.getCPtr(collateralCurve), collateralCurve, isFxBaseCurrencyCollateralCurrency, isBasisOnFxBaseCurrencyLeg, isFxBaseCurrencyLegResettable), true);
  }

}
