/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.4.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.luopc.platform.quantlib;

public class MultipleResetsCoupon extends FloatingRateCoupon {
  private transient long swigCPtr;
  private transient boolean swigCMemOwnDerived;

  protected MultipleResetsCoupon(long cPtr, boolean cMemoryOwn) {
    super(QuantLibJNI.MultipleResetsCoupon_SWIGSmartPtrUpcast(cPtr), true);
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(MultipleResetsCoupon obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void swigSetCMemOwn(boolean own) {
    swigCMemOwnDerived = own;
    super.swigSetCMemOwn(own);
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwnDerived) {
        swigCMemOwnDerived = false;
        QuantLibJNI.delete_MultipleResetsCoupon(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public MultipleResetsCoupon(Date paymentDate, double nominal, Schedule resetSchedule, long fixingDays, IborIndex index, double gearing, double couponSpread, double rateSpread, Date refPeriodStart, Date refPeriodEnd, DayCounter dayCounter, Date exCouponDate) {
    this(QuantLibJNI.new_MultipleResetsCoupon__SWIG_0(Date.getCPtr(paymentDate), paymentDate, nominal, Schedule.getCPtr(resetSchedule), resetSchedule, fixingDays, IborIndex.getCPtr(index), index, gearing, couponSpread, rateSpread, Date.getCPtr(refPeriodStart), refPeriodStart, Date.getCPtr(refPeriodEnd), refPeriodEnd, DayCounter.getCPtr(dayCounter), dayCounter, Date.getCPtr(exCouponDate), exCouponDate), true);
  }

  public MultipleResetsCoupon(Date paymentDate, double nominal, Schedule resetSchedule, long fixingDays, IborIndex index, double gearing, double couponSpread, double rateSpread, Date refPeriodStart, Date refPeriodEnd, DayCounter dayCounter) {
    this(QuantLibJNI.new_MultipleResetsCoupon__SWIG_1(Date.getCPtr(paymentDate), paymentDate, nominal, Schedule.getCPtr(resetSchedule), resetSchedule, fixingDays, IborIndex.getCPtr(index), index, gearing, couponSpread, rateSpread, Date.getCPtr(refPeriodStart), refPeriodStart, Date.getCPtr(refPeriodEnd), refPeriodEnd, DayCounter.getCPtr(dayCounter), dayCounter), true);
  }

  public MultipleResetsCoupon(Date paymentDate, double nominal, Schedule resetSchedule, long fixingDays, IborIndex index, double gearing, double couponSpread, double rateSpread, Date refPeriodStart, Date refPeriodEnd) {
    this(QuantLibJNI.new_MultipleResetsCoupon__SWIG_2(Date.getCPtr(paymentDate), paymentDate, nominal, Schedule.getCPtr(resetSchedule), resetSchedule, fixingDays, IborIndex.getCPtr(index), index, gearing, couponSpread, rateSpread, Date.getCPtr(refPeriodStart), refPeriodStart, Date.getCPtr(refPeriodEnd), refPeriodEnd), true);
  }

  public MultipleResetsCoupon(Date paymentDate, double nominal, Schedule resetSchedule, long fixingDays, IborIndex index, double gearing, double couponSpread, double rateSpread, Date refPeriodStart) {
    this(QuantLibJNI.new_MultipleResetsCoupon__SWIG_3(Date.getCPtr(paymentDate), paymentDate, nominal, Schedule.getCPtr(resetSchedule), resetSchedule, fixingDays, IborIndex.getCPtr(index), index, gearing, couponSpread, rateSpread, Date.getCPtr(refPeriodStart), refPeriodStart), true);
  }

  public MultipleResetsCoupon(Date paymentDate, double nominal, Schedule resetSchedule, long fixingDays, IborIndex index, double gearing, double couponSpread, double rateSpread) {
    this(QuantLibJNI.new_MultipleResetsCoupon__SWIG_4(Date.getCPtr(paymentDate), paymentDate, nominal, Schedule.getCPtr(resetSchedule), resetSchedule, fixingDays, IborIndex.getCPtr(index), index, gearing, couponSpread, rateSpread), true);
  }

  public MultipleResetsCoupon(Date paymentDate, double nominal, Schedule resetSchedule, long fixingDays, IborIndex index, double gearing, double couponSpread) {
    this(QuantLibJNI.new_MultipleResetsCoupon__SWIG_5(Date.getCPtr(paymentDate), paymentDate, nominal, Schedule.getCPtr(resetSchedule), resetSchedule, fixingDays, IborIndex.getCPtr(index), index, gearing, couponSpread), true);
  }

  public MultipleResetsCoupon(Date paymentDate, double nominal, Schedule resetSchedule, long fixingDays, IborIndex index, double gearing) {
    this(QuantLibJNI.new_MultipleResetsCoupon__SWIG_6(Date.getCPtr(paymentDate), paymentDate, nominal, Schedule.getCPtr(resetSchedule), resetSchedule, fixingDays, IborIndex.getCPtr(index), index, gearing), true);
  }

  public MultipleResetsCoupon(Date paymentDate, double nominal, Schedule resetSchedule, long fixingDays, IborIndex index) {
    this(QuantLibJNI.new_MultipleResetsCoupon__SWIG_7(Date.getCPtr(paymentDate), paymentDate, nominal, Schedule.getCPtr(resetSchedule), resetSchedule, fixingDays, IborIndex.getCPtr(index), index), true);
  }

  public DateVector fixingDates() {
    return new DateVector(QuantLibJNI.MultipleResetsCoupon_fixingDates(swigCPtr, this), false);
  }

  public DoubleVector dt() {
    return new DoubleVector(QuantLibJNI.MultipleResetsCoupon_dt(swigCPtr, this), false);
  }

  public DateVector valueDates() {
    return new DateVector(QuantLibJNI.MultipleResetsCoupon_valueDates(swigCPtr, this), false);
  }

  public double rateSpread() {
    return QuantLibJNI.MultipleResetsCoupon_rateSpread(swigCPtr, this);
  }

}
