/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.luopc.platform.quantlib;

public class MultipleResetsSwap extends FixedVsFloatingSwap {
  private transient long swigCPtr;
  private transient boolean swigCMemOwnDerived;

  protected MultipleResetsSwap(long cPtr, boolean cMemoryOwn) {
    super(QuantLibJNI.MultipleResetsSwap_SWIGSmartPtrUpcast(cPtr), true);
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(MultipleResetsSwap obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void swigSetCMemOwn(boolean own) {
    swigCMemOwnDerived = own;
    super.swigSetCMemOwn(own);
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwnDerived) {
        swigCMemOwnDerived = false;
        QuantLibJNI.delete_MultipleResetsSwap(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public MultipleResetsSwap(Swap.Type type, double nominal, Schedule fixedSchedule, double fixedRate, DayCounter fixedDayCount, Schedule fullResetSchedule, IborIndex iborIndex, long resetsPerCoupon, double spread, RateAveraging.Type averagingMethod, SWIGTYPE_p_ext__optionalT_BusinessDayConvention_t paymentConvention, int paymentLag, Calendar paymentCalendar) {
    this(QuantLibJNI.new_MultipleResetsSwap__SWIG_0(type.swigValue(), nominal, Schedule.getCPtr(fixedSchedule), fixedSchedule, fixedRate, DayCounter.getCPtr(fixedDayCount), fixedDayCount, Schedule.getCPtr(fullResetSchedule), fullResetSchedule, IborIndex.getCPtr(iborIndex), iborIndex, resetsPerCoupon, spread, averagingMethod.swigValue(), SWIGTYPE_p_ext__optionalT_BusinessDayConvention_t.getCPtr(paymentConvention), paymentLag, Calendar.getCPtr(paymentCalendar), paymentCalendar), true);
  }

  public MultipleResetsSwap(Swap.Type type, double nominal, Schedule fixedSchedule, double fixedRate, DayCounter fixedDayCount, Schedule fullResetSchedule, IborIndex iborIndex, long resetsPerCoupon, double spread, RateAveraging.Type averagingMethod, SWIGTYPE_p_ext__optionalT_BusinessDayConvention_t paymentConvention, int paymentLag) {
    this(QuantLibJNI.new_MultipleResetsSwap__SWIG_1(type.swigValue(), nominal, Schedule.getCPtr(fixedSchedule), fixedSchedule, fixedRate, DayCounter.getCPtr(fixedDayCount), fixedDayCount, Schedule.getCPtr(fullResetSchedule), fullResetSchedule, IborIndex.getCPtr(iborIndex), iborIndex, resetsPerCoupon, spread, averagingMethod.swigValue(), SWIGTYPE_p_ext__optionalT_BusinessDayConvention_t.getCPtr(paymentConvention), paymentLag), true);
  }

  public MultipleResetsSwap(Swap.Type type, double nominal, Schedule fixedSchedule, double fixedRate, DayCounter fixedDayCount, Schedule fullResetSchedule, IborIndex iborIndex, long resetsPerCoupon, double spread, RateAveraging.Type averagingMethod, SWIGTYPE_p_ext__optionalT_BusinessDayConvention_t paymentConvention) {
    this(QuantLibJNI.new_MultipleResetsSwap__SWIG_2(type.swigValue(), nominal, Schedule.getCPtr(fixedSchedule), fixedSchedule, fixedRate, DayCounter.getCPtr(fixedDayCount), fixedDayCount, Schedule.getCPtr(fullResetSchedule), fullResetSchedule, IborIndex.getCPtr(iborIndex), iborIndex, resetsPerCoupon, spread, averagingMethod.swigValue(), SWIGTYPE_p_ext__optionalT_BusinessDayConvention_t.getCPtr(paymentConvention)), true);
  }

  public MultipleResetsSwap(Swap.Type type, double nominal, Schedule fixedSchedule, double fixedRate, DayCounter fixedDayCount, Schedule fullResetSchedule, IborIndex iborIndex, long resetsPerCoupon, double spread, RateAveraging.Type averagingMethod) {
    this(QuantLibJNI.new_MultipleResetsSwap__SWIG_3(type.swigValue(), nominal, Schedule.getCPtr(fixedSchedule), fixedSchedule, fixedRate, DayCounter.getCPtr(fixedDayCount), fixedDayCount, Schedule.getCPtr(fullResetSchedule), fullResetSchedule, IborIndex.getCPtr(iborIndex), iborIndex, resetsPerCoupon, spread, averagingMethod.swigValue()), true);
  }

  public MultipleResetsSwap(Swap.Type type, double nominal, Schedule fixedSchedule, double fixedRate, DayCounter fixedDayCount, Schedule fullResetSchedule, IborIndex iborIndex, long resetsPerCoupon, double spread) {
    this(QuantLibJNI.new_MultipleResetsSwap__SWIG_4(type.swigValue(), nominal, Schedule.getCPtr(fixedSchedule), fixedSchedule, fixedRate, DayCounter.getCPtr(fixedDayCount), fixedDayCount, Schedule.getCPtr(fullResetSchedule), fullResetSchedule, IborIndex.getCPtr(iborIndex), iborIndex, resetsPerCoupon, spread), true);
  }

  public MultipleResetsSwap(Swap.Type type, double nominal, Schedule fixedSchedule, double fixedRate, DayCounter fixedDayCount, Schedule fullResetSchedule, IborIndex iborIndex, long resetsPerCoupon) {
    this(QuantLibJNI.new_MultipleResetsSwap__SWIG_5(type.swigValue(), nominal, Schedule.getCPtr(fixedSchedule), fixedSchedule, fixedRate, DayCounter.getCPtr(fixedDayCount), fixedDayCount, Schedule.getCPtr(fullResetSchedule), fullResetSchedule, IborIndex.getCPtr(iborIndex), iborIndex, resetsPerCoupon), true);
  }

  public Schedule fullResetSchedule() {
    return new Schedule(QuantLibJNI.MultipleResetsSwap_fullResetSchedule(swigCPtr, this), false);
  }

  public long resetsPerCoupon() {
    return QuantLibJNI.MultipleResetsSwap_resetsPerCoupon(swigCPtr, this);
  }

  public RateAveraging.Type averagingMethod() {
    return RateAveraging.Type.swigToEnum(QuantLibJNI.MultipleResetsSwap_averagingMethod(swigCPtr, this));
  }

}
