/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.4.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.luopc.platform.quantlib;

public class NaturalCubicForwardCurve extends YieldTermStructure {
  private transient long swigCPtr;
  private transient boolean swigCMemOwnDerived;

  protected NaturalCubicForwardCurve(long cPtr, boolean cMemoryOwn) {
    super(QuantLibJNI.NaturalCubicForwardCurve_SWIGSmartPtrUpcast(cPtr), true);
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(NaturalCubicForwardCurve obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void swigSetCMemOwn(boolean own) {
    swigCMemOwnDerived = own;
    super.swigSetCMemOwn(own);
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwnDerived) {
        swigCMemOwnDerived = false;
        QuantLibJNI.delete_NaturalCubicForwardCurve(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public NaturalCubicForwardCurve(DateVector dates, DoubleVector forwards, DayCounter dayCounter, Calendar calendar, SplineCubic i) {
    this(QuantLibJNI.new_NaturalCubicForwardCurve__SWIG_0(DateVector.getCPtr(dates), dates, DoubleVector.getCPtr(forwards), forwards, DayCounter.getCPtr(dayCounter), dayCounter, Calendar.getCPtr(calendar), calendar, SplineCubic.getCPtr(i), i), true);
  }

  public NaturalCubicForwardCurve(DateVector dates, DoubleVector forwards, DayCounter dayCounter, Calendar calendar) {
    this(QuantLibJNI.new_NaturalCubicForwardCurve__SWIG_1(DateVector.getCPtr(dates), dates, DoubleVector.getCPtr(forwards), forwards, DayCounter.getCPtr(dayCounter), dayCounter, Calendar.getCPtr(calendar), calendar), true);
  }

  public NaturalCubicForwardCurve(DateVector dates, DoubleVector forwards, DayCounter dayCounter) {
    this(QuantLibJNI.new_NaturalCubicForwardCurve__SWIG_2(DateVector.getCPtr(dates), dates, DoubleVector.getCPtr(forwards), forwards, DayCounter.getCPtr(dayCounter), dayCounter), true);
  }

  public DateVector dates() {
    return new DateVector(QuantLibJNI.NaturalCubicForwardCurve_dates(swigCPtr, this), false);
  }

  public DoubleVector forwards() {
    return new DoubleVector(QuantLibJNI.NaturalCubicForwardCurve_forwards(swigCPtr, this), false);
  }

  public NodeVector nodes() {
    return new NodeVector(QuantLibJNI.NaturalCubicForwardCurve_nodes(swigCPtr, this), true);
  }

}
