/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.luopc.platform.quantlib;

public class OptionalInteger {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected OptionalInteger(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(OptionalInteger obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        QuantLibJNI.delete_OptionalInteger(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public OptionalInteger(int t) {
    this(QuantLibJNI.new_OptionalInteger(t), true);
  }

}
