/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.luopc.platform.quantlib;

public class OvernightIndexedSwap extends FixedVsFloatingSwap {
  private transient long swigCPtr;
  private transient boolean swigCMemOwnDerived;

  protected OvernightIndexedSwap(long cPtr, boolean cMemoryOwn) {
    super(QuantLibJNI.OvernightIndexedSwap_SWIGSmartPtrUpcast(cPtr), true);
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(OvernightIndexedSwap obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void swigSetCMemOwn(boolean own) {
    swigCMemOwnDerived = own;
    super.swigSetCMemOwn(own);
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwnDerived) {
        swigCMemOwnDerived = false;
        QuantLibJNI.delete_OvernightIndexedSwap(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public OvernightIndexedSwap(Swap.Type type, double nominal, Schedule schedule, double fixedRate, DayCounter fixedDC, OvernightIndex index, double spread, int paymentLag, BusinessDayConvention paymentAdjustment, Calendar paymentCalendar, boolean telescopicValueDates, RateAveraging.Type averagingMethod, long lookbackDays, long lockoutDays, boolean applyObservationShift) {
    this(QuantLibJNI.new_OvernightIndexedSwap__SWIG_0(type.swigValue(), nominal, Schedule.getCPtr(schedule), schedule, fixedRate, DayCounter.getCPtr(fixedDC), fixedDC, OvernightIndex.getCPtr(index), index, spread, paymentLag, paymentAdjustment.swigValue(), Calendar.getCPtr(paymentCalendar), paymentCalendar, telescopicValueDates, averagingMethod.swigValue(), lookbackDays, lockoutDays, applyObservationShift), true);
  }

  public OvernightIndexedSwap(Swap.Type type, double nominal, Schedule schedule, double fixedRate, DayCounter fixedDC, OvernightIndex index, double spread, int paymentLag, BusinessDayConvention paymentAdjustment, Calendar paymentCalendar, boolean telescopicValueDates, RateAveraging.Type averagingMethod, long lookbackDays, long lockoutDays) {
    this(QuantLibJNI.new_OvernightIndexedSwap__SWIG_1(type.swigValue(), nominal, Schedule.getCPtr(schedule), schedule, fixedRate, DayCounter.getCPtr(fixedDC), fixedDC, OvernightIndex.getCPtr(index), index, spread, paymentLag, paymentAdjustment.swigValue(), Calendar.getCPtr(paymentCalendar), paymentCalendar, telescopicValueDates, averagingMethod.swigValue(), lookbackDays, lockoutDays), true);
  }

  public OvernightIndexedSwap(Swap.Type type, double nominal, Schedule schedule, double fixedRate, DayCounter fixedDC, OvernightIndex index, double spread, int paymentLag, BusinessDayConvention paymentAdjustment, Calendar paymentCalendar, boolean telescopicValueDates, RateAveraging.Type averagingMethod, long lookbackDays) {
    this(QuantLibJNI.new_OvernightIndexedSwap__SWIG_2(type.swigValue(), nominal, Schedule.getCPtr(schedule), schedule, fixedRate, DayCounter.getCPtr(fixedDC), fixedDC, OvernightIndex.getCPtr(index), index, spread, paymentLag, paymentAdjustment.swigValue(), Calendar.getCPtr(paymentCalendar), paymentCalendar, telescopicValueDates, averagingMethod.swigValue(), lookbackDays), true);
  }

  public OvernightIndexedSwap(Swap.Type type, double nominal, Schedule schedule, double fixedRate, DayCounter fixedDC, OvernightIndex index, double spread, int paymentLag, BusinessDayConvention paymentAdjustment, Calendar paymentCalendar, boolean telescopicValueDates, RateAveraging.Type averagingMethod) {
    this(QuantLibJNI.new_OvernightIndexedSwap__SWIG_3(type.swigValue(), nominal, Schedule.getCPtr(schedule), schedule, fixedRate, DayCounter.getCPtr(fixedDC), fixedDC, OvernightIndex.getCPtr(index), index, spread, paymentLag, paymentAdjustment.swigValue(), Calendar.getCPtr(paymentCalendar), paymentCalendar, telescopicValueDates, averagingMethod.swigValue()), true);
  }

  public OvernightIndexedSwap(Swap.Type type, double nominal, Schedule schedule, double fixedRate, DayCounter fixedDC, OvernightIndex index, double spread, int paymentLag, BusinessDayConvention paymentAdjustment, Calendar paymentCalendar, boolean telescopicValueDates) {
    this(QuantLibJNI.new_OvernightIndexedSwap__SWIG_4(type.swigValue(), nominal, Schedule.getCPtr(schedule), schedule, fixedRate, DayCounter.getCPtr(fixedDC), fixedDC, OvernightIndex.getCPtr(index), index, spread, paymentLag, paymentAdjustment.swigValue(), Calendar.getCPtr(paymentCalendar), paymentCalendar, telescopicValueDates), true);
  }

  public OvernightIndexedSwap(Swap.Type type, double nominal, Schedule schedule, double fixedRate, DayCounter fixedDC, OvernightIndex index, double spread, int paymentLag, BusinessDayConvention paymentAdjustment, Calendar paymentCalendar) {
    this(QuantLibJNI.new_OvernightIndexedSwap__SWIG_5(type.swigValue(), nominal, Schedule.getCPtr(schedule), schedule, fixedRate, DayCounter.getCPtr(fixedDC), fixedDC, OvernightIndex.getCPtr(index), index, spread, paymentLag, paymentAdjustment.swigValue(), Calendar.getCPtr(paymentCalendar), paymentCalendar), true);
  }

  public OvernightIndexedSwap(Swap.Type type, double nominal, Schedule schedule, double fixedRate, DayCounter fixedDC, OvernightIndex index, double spread, int paymentLag, BusinessDayConvention paymentAdjustment) {
    this(QuantLibJNI.new_OvernightIndexedSwap__SWIG_6(type.swigValue(), nominal, Schedule.getCPtr(schedule), schedule, fixedRate, DayCounter.getCPtr(fixedDC), fixedDC, OvernightIndex.getCPtr(index), index, spread, paymentLag, paymentAdjustment.swigValue()), true);
  }

  public OvernightIndexedSwap(Swap.Type type, double nominal, Schedule schedule, double fixedRate, DayCounter fixedDC, OvernightIndex index, double spread, int paymentLag) {
    this(QuantLibJNI.new_OvernightIndexedSwap__SWIG_7(type.swigValue(), nominal, Schedule.getCPtr(schedule), schedule, fixedRate, DayCounter.getCPtr(fixedDC), fixedDC, OvernightIndex.getCPtr(index), index, spread, paymentLag), true);
  }

  public OvernightIndexedSwap(Swap.Type type, double nominal, Schedule schedule, double fixedRate, DayCounter fixedDC, OvernightIndex index, double spread) {
    this(QuantLibJNI.new_OvernightIndexedSwap__SWIG_8(type.swigValue(), nominal, Schedule.getCPtr(schedule), schedule, fixedRate, DayCounter.getCPtr(fixedDC), fixedDC, OvernightIndex.getCPtr(index), index, spread), true);
  }

  public OvernightIndexedSwap(Swap.Type type, double nominal, Schedule schedule, double fixedRate, DayCounter fixedDC, OvernightIndex index) {
    this(QuantLibJNI.new_OvernightIndexedSwap__SWIG_9(type.swigValue(), nominal, Schedule.getCPtr(schedule), schedule, fixedRate, DayCounter.getCPtr(fixedDC), fixedDC, OvernightIndex.getCPtr(index), index), true);
  }

  public OvernightIndexedSwap(Swap.Type type, DoubleVector nominals, Schedule schedule, double fixedRate, DayCounter fixedDC, OvernightIndex index, double spread, int paymentLag, BusinessDayConvention paymentAdjustment, Calendar paymentCalendar, boolean telescopicValueDates, RateAveraging.Type averagingMethod, long lookbackDays, long lockoutDays, boolean applyObservationShift) {
    this(QuantLibJNI.new_OvernightIndexedSwap__SWIG_10(type.swigValue(), DoubleVector.getCPtr(nominals), nominals, Schedule.getCPtr(schedule), schedule, fixedRate, DayCounter.getCPtr(fixedDC), fixedDC, OvernightIndex.getCPtr(index), index, spread, paymentLag, paymentAdjustment.swigValue(), Calendar.getCPtr(paymentCalendar), paymentCalendar, telescopicValueDates, averagingMethod.swigValue(), lookbackDays, lockoutDays, applyObservationShift), true);
  }

  public OvernightIndexedSwap(Swap.Type type, DoubleVector nominals, Schedule schedule, double fixedRate, DayCounter fixedDC, OvernightIndex index, double spread, int paymentLag, BusinessDayConvention paymentAdjustment, Calendar paymentCalendar, boolean telescopicValueDates, RateAveraging.Type averagingMethod, long lookbackDays, long lockoutDays) {
    this(QuantLibJNI.new_OvernightIndexedSwap__SWIG_11(type.swigValue(), DoubleVector.getCPtr(nominals), nominals, Schedule.getCPtr(schedule), schedule, fixedRate, DayCounter.getCPtr(fixedDC), fixedDC, OvernightIndex.getCPtr(index), index, spread, paymentLag, paymentAdjustment.swigValue(), Calendar.getCPtr(paymentCalendar), paymentCalendar, telescopicValueDates, averagingMethod.swigValue(), lookbackDays, lockoutDays), true);
  }

  public OvernightIndexedSwap(Swap.Type type, DoubleVector nominals, Schedule schedule, double fixedRate, DayCounter fixedDC, OvernightIndex index, double spread, int paymentLag, BusinessDayConvention paymentAdjustment, Calendar paymentCalendar, boolean telescopicValueDates, RateAveraging.Type averagingMethod, long lookbackDays) {
    this(QuantLibJNI.new_OvernightIndexedSwap__SWIG_12(type.swigValue(), DoubleVector.getCPtr(nominals), nominals, Schedule.getCPtr(schedule), schedule, fixedRate, DayCounter.getCPtr(fixedDC), fixedDC, OvernightIndex.getCPtr(index), index, spread, paymentLag, paymentAdjustment.swigValue(), Calendar.getCPtr(paymentCalendar), paymentCalendar, telescopicValueDates, averagingMethod.swigValue(), lookbackDays), true);
  }

  public OvernightIndexedSwap(Swap.Type type, DoubleVector nominals, Schedule schedule, double fixedRate, DayCounter fixedDC, OvernightIndex index, double spread, int paymentLag, BusinessDayConvention paymentAdjustment, Calendar paymentCalendar, boolean telescopicValueDates, RateAveraging.Type averagingMethod) {
    this(QuantLibJNI.new_OvernightIndexedSwap__SWIG_13(type.swigValue(), DoubleVector.getCPtr(nominals), nominals, Schedule.getCPtr(schedule), schedule, fixedRate, DayCounter.getCPtr(fixedDC), fixedDC, OvernightIndex.getCPtr(index), index, spread, paymentLag, paymentAdjustment.swigValue(), Calendar.getCPtr(paymentCalendar), paymentCalendar, telescopicValueDates, averagingMethod.swigValue()), true);
  }

  public OvernightIndexedSwap(Swap.Type type, DoubleVector nominals, Schedule schedule, double fixedRate, DayCounter fixedDC, OvernightIndex index, double spread, int paymentLag, BusinessDayConvention paymentAdjustment, Calendar paymentCalendar, boolean telescopicValueDates) {
    this(QuantLibJNI.new_OvernightIndexedSwap__SWIG_14(type.swigValue(), DoubleVector.getCPtr(nominals), nominals, Schedule.getCPtr(schedule), schedule, fixedRate, DayCounter.getCPtr(fixedDC), fixedDC, OvernightIndex.getCPtr(index), index, spread, paymentLag, paymentAdjustment.swigValue(), Calendar.getCPtr(paymentCalendar), paymentCalendar, telescopicValueDates), true);
  }

  public OvernightIndexedSwap(Swap.Type type, DoubleVector nominals, Schedule schedule, double fixedRate, DayCounter fixedDC, OvernightIndex index, double spread, int paymentLag, BusinessDayConvention paymentAdjustment, Calendar paymentCalendar) {
    this(QuantLibJNI.new_OvernightIndexedSwap__SWIG_15(type.swigValue(), DoubleVector.getCPtr(nominals), nominals, Schedule.getCPtr(schedule), schedule, fixedRate, DayCounter.getCPtr(fixedDC), fixedDC, OvernightIndex.getCPtr(index), index, spread, paymentLag, paymentAdjustment.swigValue(), Calendar.getCPtr(paymentCalendar), paymentCalendar), true);
  }

  public OvernightIndexedSwap(Swap.Type type, DoubleVector nominals, Schedule schedule, double fixedRate, DayCounter fixedDC, OvernightIndex index, double spread, int paymentLag, BusinessDayConvention paymentAdjustment) {
    this(QuantLibJNI.new_OvernightIndexedSwap__SWIG_16(type.swigValue(), DoubleVector.getCPtr(nominals), nominals, Schedule.getCPtr(schedule), schedule, fixedRate, DayCounter.getCPtr(fixedDC), fixedDC, OvernightIndex.getCPtr(index), index, spread, paymentLag, paymentAdjustment.swigValue()), true);
  }

  public OvernightIndexedSwap(Swap.Type type, DoubleVector nominals, Schedule schedule, double fixedRate, DayCounter fixedDC, OvernightIndex index, double spread, int paymentLag) {
    this(QuantLibJNI.new_OvernightIndexedSwap__SWIG_17(type.swigValue(), DoubleVector.getCPtr(nominals), nominals, Schedule.getCPtr(schedule), schedule, fixedRate, DayCounter.getCPtr(fixedDC), fixedDC, OvernightIndex.getCPtr(index), index, spread, paymentLag), true);
  }

  public OvernightIndexedSwap(Swap.Type type, DoubleVector nominals, Schedule schedule, double fixedRate, DayCounter fixedDC, OvernightIndex index, double spread) {
    this(QuantLibJNI.new_OvernightIndexedSwap__SWIG_18(type.swigValue(), DoubleVector.getCPtr(nominals), nominals, Schedule.getCPtr(schedule), schedule, fixedRate, DayCounter.getCPtr(fixedDC), fixedDC, OvernightIndex.getCPtr(index), index, spread), true);
  }

  public OvernightIndexedSwap(Swap.Type type, DoubleVector nominals, Schedule schedule, double fixedRate, DayCounter fixedDC, OvernightIndex index) {
    this(QuantLibJNI.new_OvernightIndexedSwap__SWIG_19(type.swigValue(), DoubleVector.getCPtr(nominals), nominals, Schedule.getCPtr(schedule), schedule, fixedRate, DayCounter.getCPtr(fixedDC), fixedDC, OvernightIndex.getCPtr(index), index), true);
  }

  public OvernightIndexedSwap(Swap.Type type, DoubleVector fixedNominals, Schedule fixedSchedule, double fixedRate, DayCounter fixedDC, DoubleVector overnightNominals, Schedule overnightSchedule, OvernightIndex overnightIndex, double spread, int paymentLag, BusinessDayConvention paymentAdjustment, Calendar paymentCalendar, boolean telescopicValueDates, RateAveraging.Type averagingMethod, long lookbackDays, long lockoutDays, boolean applyObservationShift) {
    this(QuantLibJNI.new_OvernightIndexedSwap__SWIG_20(type.swigValue(), DoubleVector.getCPtr(fixedNominals), fixedNominals, Schedule.getCPtr(fixedSchedule), fixedSchedule, fixedRate, DayCounter.getCPtr(fixedDC), fixedDC, DoubleVector.getCPtr(overnightNominals), overnightNominals, Schedule.getCPtr(overnightSchedule), overnightSchedule, OvernightIndex.getCPtr(overnightIndex), overnightIndex, spread, paymentLag, paymentAdjustment.swigValue(), Calendar.getCPtr(paymentCalendar), paymentCalendar, telescopicValueDates, averagingMethod.swigValue(), lookbackDays, lockoutDays, applyObservationShift), true);
  }

  public OvernightIndexedSwap(Swap.Type type, DoubleVector fixedNominals, Schedule fixedSchedule, double fixedRate, DayCounter fixedDC, DoubleVector overnightNominals, Schedule overnightSchedule, OvernightIndex overnightIndex, double spread, int paymentLag, BusinessDayConvention paymentAdjustment, Calendar paymentCalendar, boolean telescopicValueDates, RateAveraging.Type averagingMethod, long lookbackDays, long lockoutDays) {
    this(QuantLibJNI.new_OvernightIndexedSwap__SWIG_21(type.swigValue(), DoubleVector.getCPtr(fixedNominals), fixedNominals, Schedule.getCPtr(fixedSchedule), fixedSchedule, fixedRate, DayCounter.getCPtr(fixedDC), fixedDC, DoubleVector.getCPtr(overnightNominals), overnightNominals, Schedule.getCPtr(overnightSchedule), overnightSchedule, OvernightIndex.getCPtr(overnightIndex), overnightIndex, spread, paymentLag, paymentAdjustment.swigValue(), Calendar.getCPtr(paymentCalendar), paymentCalendar, telescopicValueDates, averagingMethod.swigValue(), lookbackDays, lockoutDays), true);
  }

  public OvernightIndexedSwap(Swap.Type type, DoubleVector fixedNominals, Schedule fixedSchedule, double fixedRate, DayCounter fixedDC, DoubleVector overnightNominals, Schedule overnightSchedule, OvernightIndex overnightIndex, double spread, int paymentLag, BusinessDayConvention paymentAdjustment, Calendar paymentCalendar, boolean telescopicValueDates, RateAveraging.Type averagingMethod, long lookbackDays) {
    this(QuantLibJNI.new_OvernightIndexedSwap__SWIG_22(type.swigValue(), DoubleVector.getCPtr(fixedNominals), fixedNominals, Schedule.getCPtr(fixedSchedule), fixedSchedule, fixedRate, DayCounter.getCPtr(fixedDC), fixedDC, DoubleVector.getCPtr(overnightNominals), overnightNominals, Schedule.getCPtr(overnightSchedule), overnightSchedule, OvernightIndex.getCPtr(overnightIndex), overnightIndex, spread, paymentLag, paymentAdjustment.swigValue(), Calendar.getCPtr(paymentCalendar), paymentCalendar, telescopicValueDates, averagingMethod.swigValue(), lookbackDays), true);
  }

  public OvernightIndexedSwap(Swap.Type type, DoubleVector fixedNominals, Schedule fixedSchedule, double fixedRate, DayCounter fixedDC, DoubleVector overnightNominals, Schedule overnightSchedule, OvernightIndex overnightIndex, double spread, int paymentLag, BusinessDayConvention paymentAdjustment, Calendar paymentCalendar, boolean telescopicValueDates, RateAveraging.Type averagingMethod) {
    this(QuantLibJNI.new_OvernightIndexedSwap__SWIG_23(type.swigValue(), DoubleVector.getCPtr(fixedNominals), fixedNominals, Schedule.getCPtr(fixedSchedule), fixedSchedule, fixedRate, DayCounter.getCPtr(fixedDC), fixedDC, DoubleVector.getCPtr(overnightNominals), overnightNominals, Schedule.getCPtr(overnightSchedule), overnightSchedule, OvernightIndex.getCPtr(overnightIndex), overnightIndex, spread, paymentLag, paymentAdjustment.swigValue(), Calendar.getCPtr(paymentCalendar), paymentCalendar, telescopicValueDates, averagingMethod.swigValue()), true);
  }

  public OvernightIndexedSwap(Swap.Type type, DoubleVector fixedNominals, Schedule fixedSchedule, double fixedRate, DayCounter fixedDC, DoubleVector overnightNominals, Schedule overnightSchedule, OvernightIndex overnightIndex, double spread, int paymentLag, BusinessDayConvention paymentAdjustment, Calendar paymentCalendar, boolean telescopicValueDates) {
    this(QuantLibJNI.new_OvernightIndexedSwap__SWIG_24(type.swigValue(), DoubleVector.getCPtr(fixedNominals), fixedNominals, Schedule.getCPtr(fixedSchedule), fixedSchedule, fixedRate, DayCounter.getCPtr(fixedDC), fixedDC, DoubleVector.getCPtr(overnightNominals), overnightNominals, Schedule.getCPtr(overnightSchedule), overnightSchedule, OvernightIndex.getCPtr(overnightIndex), overnightIndex, spread, paymentLag, paymentAdjustment.swigValue(), Calendar.getCPtr(paymentCalendar), paymentCalendar, telescopicValueDates), true);
  }

  public OvernightIndexedSwap(Swap.Type type, DoubleVector fixedNominals, Schedule fixedSchedule, double fixedRate, DayCounter fixedDC, DoubleVector overnightNominals, Schedule overnightSchedule, OvernightIndex overnightIndex, double spread, int paymentLag, BusinessDayConvention paymentAdjustment, Calendar paymentCalendar) {
    this(QuantLibJNI.new_OvernightIndexedSwap__SWIG_25(type.swigValue(), DoubleVector.getCPtr(fixedNominals), fixedNominals, Schedule.getCPtr(fixedSchedule), fixedSchedule, fixedRate, DayCounter.getCPtr(fixedDC), fixedDC, DoubleVector.getCPtr(overnightNominals), overnightNominals, Schedule.getCPtr(overnightSchedule), overnightSchedule, OvernightIndex.getCPtr(overnightIndex), overnightIndex, spread, paymentLag, paymentAdjustment.swigValue(), Calendar.getCPtr(paymentCalendar), paymentCalendar), true);
  }

  public OvernightIndexedSwap(Swap.Type type, DoubleVector fixedNominals, Schedule fixedSchedule, double fixedRate, DayCounter fixedDC, DoubleVector overnightNominals, Schedule overnightSchedule, OvernightIndex overnightIndex, double spread, int paymentLag, BusinessDayConvention paymentAdjustment) {
    this(QuantLibJNI.new_OvernightIndexedSwap__SWIG_26(type.swigValue(), DoubleVector.getCPtr(fixedNominals), fixedNominals, Schedule.getCPtr(fixedSchedule), fixedSchedule, fixedRate, DayCounter.getCPtr(fixedDC), fixedDC, DoubleVector.getCPtr(overnightNominals), overnightNominals, Schedule.getCPtr(overnightSchedule), overnightSchedule, OvernightIndex.getCPtr(overnightIndex), overnightIndex, spread, paymentLag, paymentAdjustment.swigValue()), true);
  }

  public OvernightIndexedSwap(Swap.Type type, DoubleVector fixedNominals, Schedule fixedSchedule, double fixedRate, DayCounter fixedDC, DoubleVector overnightNominals, Schedule overnightSchedule, OvernightIndex overnightIndex, double spread, int paymentLag) {
    this(QuantLibJNI.new_OvernightIndexedSwap__SWIG_27(type.swigValue(), DoubleVector.getCPtr(fixedNominals), fixedNominals, Schedule.getCPtr(fixedSchedule), fixedSchedule, fixedRate, DayCounter.getCPtr(fixedDC), fixedDC, DoubleVector.getCPtr(overnightNominals), overnightNominals, Schedule.getCPtr(overnightSchedule), overnightSchedule, OvernightIndex.getCPtr(overnightIndex), overnightIndex, spread, paymentLag), true);
  }

  public OvernightIndexedSwap(Swap.Type type, DoubleVector fixedNominals, Schedule fixedSchedule, double fixedRate, DayCounter fixedDC, DoubleVector overnightNominals, Schedule overnightSchedule, OvernightIndex overnightIndex, double spread) {
    this(QuantLibJNI.new_OvernightIndexedSwap__SWIG_28(type.swigValue(), DoubleVector.getCPtr(fixedNominals), fixedNominals, Schedule.getCPtr(fixedSchedule), fixedSchedule, fixedRate, DayCounter.getCPtr(fixedDC), fixedDC, DoubleVector.getCPtr(overnightNominals), overnightNominals, Schedule.getCPtr(overnightSchedule), overnightSchedule, OvernightIndex.getCPtr(overnightIndex), overnightIndex, spread), true);
  }

  public OvernightIndexedSwap(Swap.Type type, DoubleVector fixedNominals, Schedule fixedSchedule, double fixedRate, DayCounter fixedDC, DoubleVector overnightNominals, Schedule overnightSchedule, OvernightIndex overnightIndex) {
    this(QuantLibJNI.new_OvernightIndexedSwap__SWIG_29(type.swigValue(), DoubleVector.getCPtr(fixedNominals), fixedNominals, Schedule.getCPtr(fixedSchedule), fixedSchedule, fixedRate, DayCounter.getCPtr(fixedDC), fixedDC, DoubleVector.getCPtr(overnightNominals), overnightNominals, Schedule.getCPtr(overnightSchedule), overnightSchedule, OvernightIndex.getCPtr(overnightIndex), overnightIndex), true);
  }

  public double overnightLegBPS() {
    return QuantLibJNI.OvernightIndexedSwap_overnightLegBPS(swigCPtr, this);
  }

  public double overnightLegNPV() {
    return QuantLibJNI.OvernightIndexedSwap_overnightLegNPV(swigCPtr, this);
  }

  public Frequency paymentFrequency() {
    return Frequency.swigToEnum(QuantLibJNI.OvernightIndexedSwap_paymentFrequency(swigCPtr, this));
  }

  public OvernightIndex overnightIndex() {
    long cPtr = QuantLibJNI.OvernightIndexedSwap_overnightIndex(swigCPtr, this);
    return (cPtr == 0) ? null : new OvernightIndex(cPtr, true);
  }

  public Leg overnightLeg() {
    return new Leg(QuantLibJNI.OvernightIndexedSwap_overnightLeg(swigCPtr, this), false);
  }

  public RateAveraging.Type averagingMethod() {
    return RateAveraging.Type.swigToEnum(QuantLibJNI.OvernightIndexedSwap_averagingMethod(swigCPtr, this));
  }

  public long lookbackDays() {
    return QuantLibJNI.OvernightIndexedSwap_lookbackDays(swigCPtr, this);
  }

  public long lockoutDays() {
    return QuantLibJNI.OvernightIndexedSwap_lockoutDays(swigCPtr, this);
  }

  public boolean applyObservationShift() {
    return QuantLibJNI.OvernightIndexedSwap_applyObservationShift(swigCPtr, this);
  }

}
