/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.luopc.platform.quantlib;

public class OvernightIndexFutureRateHelper extends RateHelper {
  private transient long swigCPtr;
  private transient boolean swigCMemOwnDerived;

  protected OvernightIndexFutureRateHelper(long cPtr, boolean cMemoryOwn) {
    super(QuantLibJNI.OvernightIndexFutureRateHelper_SWIGSmartPtrUpcast(cPtr), true);
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(OvernightIndexFutureRateHelper obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void swigSetCMemOwn(boolean own) {
    swigCMemOwnDerived = own;
    super.swigSetCMemOwn(own);
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwnDerived) {
        swigCMemOwnDerived = false;
        QuantLibJNI.delete_OvernightIndexFutureRateHelper(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public OvernightIndexFutureRateHelper(QuoteHandle price, Date valueDate, Date maturityDate, OvernightIndex index, QuoteHandle convexityAdjustment, RateAveraging.Type averagingMethod, Pillar.Choice pillar, Date customPillarDate) {
    this(QuantLibJNI.new_OvernightIndexFutureRateHelper__SWIG_0(QuoteHandle.getCPtr(price), price, Date.getCPtr(valueDate), valueDate, Date.getCPtr(maturityDate), maturityDate, OvernightIndex.getCPtr(index), index, QuoteHandle.getCPtr(convexityAdjustment), convexityAdjustment, averagingMethod.swigValue(), pillar.swigValue(), Date.getCPtr(customPillarDate), customPillarDate), true);
  }

  public OvernightIndexFutureRateHelper(QuoteHandle price, Date valueDate, Date maturityDate, OvernightIndex index, QuoteHandle convexityAdjustment, RateAveraging.Type averagingMethod, Pillar.Choice pillar) {
    this(QuantLibJNI.new_OvernightIndexFutureRateHelper__SWIG_1(QuoteHandle.getCPtr(price), price, Date.getCPtr(valueDate), valueDate, Date.getCPtr(maturityDate), maturityDate, OvernightIndex.getCPtr(index), index, QuoteHandle.getCPtr(convexityAdjustment), convexityAdjustment, averagingMethod.swigValue(), pillar.swigValue()), true);
  }

  public OvernightIndexFutureRateHelper(QuoteHandle price, Date valueDate, Date maturityDate, OvernightIndex index, QuoteHandle convexityAdjustment, RateAveraging.Type averagingMethod) {
    this(QuantLibJNI.new_OvernightIndexFutureRateHelper__SWIG_2(QuoteHandle.getCPtr(price), price, Date.getCPtr(valueDate), valueDate, Date.getCPtr(maturityDate), maturityDate, OvernightIndex.getCPtr(index), index, QuoteHandle.getCPtr(convexityAdjustment), convexityAdjustment, averagingMethod.swigValue()), true);
  }

  public OvernightIndexFutureRateHelper(QuoteHandle price, Date valueDate, Date maturityDate, OvernightIndex index, QuoteHandle convexityAdjustment) {
    this(QuantLibJNI.new_OvernightIndexFutureRateHelper__SWIG_3(QuoteHandle.getCPtr(price), price, Date.getCPtr(valueDate), valueDate, Date.getCPtr(maturityDate), maturityDate, OvernightIndex.getCPtr(index), index, QuoteHandle.getCPtr(convexityAdjustment), convexityAdjustment), true);
  }

  public OvernightIndexFutureRateHelper(QuoteHandle price, Date valueDate, Date maturityDate, OvernightIndex index) {
    this(QuantLibJNI.new_OvernightIndexFutureRateHelper__SWIG_4(QuoteHandle.getCPtr(price), price, Date.getCPtr(valueDate), valueDate, Date.getCPtr(maturityDate), maturityDate, OvernightIndex.getCPtr(index), index), true);
  }

  public double convexityAdjustment() {
    return QuantLibJNI.OvernightIndexFutureRateHelper_convexityAdjustment(swigCPtr, this);
  }

}
