/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.luopc.platform.quantlib;

public class PiecewiseLogMixedLinearCubicSpreadDiscount extends YieldTermStructure {
  private transient long swigCPtr;
  private transient boolean swigCMemOwnDerived;

  protected PiecewiseLogMixedLinearCubicSpreadDiscount(long cPtr, boolean cMemoryOwn) {
    super(QuantLibJNI.PiecewiseLogMixedLinearCubicSpreadDiscount_SWIGSmartPtrUpcast(cPtr), true);
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(PiecewiseLogMixedLinearCubicSpreadDiscount obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void swigSetCMemOwn(boolean own) {
    swigCMemOwnDerived = own;
    super.swigSetCMemOwn(own);
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwnDerived) {
        swigCMemOwnDerived = false;
        QuantLibJNI.delete_PiecewiseLogMixedLinearCubicSpreadDiscount(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public PiecewiseLogMixedLinearCubicSpreadDiscount(YieldTermStructureHandle baseCurve, RateHelperVector instruments, LogMixedLinearCubic interpolator, IterativeBootstrap bootstrap) {
    this(QuantLibJNI.new_PiecewiseLogMixedLinearCubicSpreadDiscount__SWIG_0(YieldTermStructureHandle.getCPtr(baseCurve), baseCurve, RateHelperVector.getCPtr(instruments), instruments, LogMixedLinearCubic.getCPtr(interpolator), interpolator, IterativeBootstrap.getCPtr(bootstrap), bootstrap), true);
  }

  public PiecewiseLogMixedLinearCubicSpreadDiscount(YieldTermStructureHandle baseCurve, RateHelperVector instruments, LogMixedLinearCubic interpolator) {
    this(QuantLibJNI.new_PiecewiseLogMixedLinearCubicSpreadDiscount__SWIG_1(YieldTermStructureHandle.getCPtr(baseCurve), baseCurve, RateHelperVector.getCPtr(instruments), instruments, LogMixedLinearCubic.getCPtr(interpolator), interpolator), true);
  }

  public PiecewiseLogMixedLinearCubicSpreadDiscount(YieldTermStructureHandle baseCurve, RateHelperVector instruments) {
    this(QuantLibJNI.new_PiecewiseLogMixedLinearCubicSpreadDiscount__SWIG_2(YieldTermStructureHandle.getCPtr(baseCurve), baseCurve, RateHelperVector.getCPtr(instruments), instruments), true);
  }

  public YieldTermStructureHandle baseCurve() {
    return new YieldTermStructureHandle(QuantLibJNI.PiecewiseLogMixedLinearCubicSpreadDiscount_baseCurve(swigCPtr, this), false);
  }

  public DateVector dates() {
    return new DateVector(QuantLibJNI.PiecewiseLogMixedLinearCubicSpreadDiscount_dates(swigCPtr, this), false);
  }

  public DoubleVector times() {
    return new DoubleVector(QuantLibJNI.PiecewiseLogMixedLinearCubicSpreadDiscount_times(swigCPtr, this), false);
  }

  public DoubleVector data() {
    return new DoubleVector(QuantLibJNI.PiecewiseLogMixedLinearCubicSpreadDiscount_data(swigCPtr, this), false);
  }

  public NodeVector nodes() {
    return new NodeVector(QuantLibJNI.PiecewiseLogMixedLinearCubicSpreadDiscount_nodes(swigCPtr, this), true);
  }

  public void recalculate() {
    QuantLibJNI.PiecewiseLogMixedLinearCubicSpreadDiscount_recalculate(swigCPtr, this);
  }

  public void freeze() {
    QuantLibJNI.PiecewiseLogMixedLinearCubicSpreadDiscount_freeze(swigCPtr, this);
  }

  public void unfreeze() {
    QuantLibJNI.PiecewiseLogMixedLinearCubicSpreadDiscount_unfreeze(swigCPtr, this);
  }

}
