/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.4.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.luopc.platform.quantlib;

public class PiecewiseNaturalLogCubicSpreadDiscount extends YieldTermStructure {
  private transient long swigCPtr;
  private transient boolean swigCMemOwnDerived;

  protected PiecewiseNaturalLogCubicSpreadDiscount(long cPtr, boolean cMemoryOwn) {
    super(QuantLibJNI.PiecewiseNaturalLogCubicSpreadDiscount_SWIGSmartPtrUpcast(cPtr), true);
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(PiecewiseNaturalLogCubicSpreadDiscount obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void swigSetCMemOwn(boolean own) {
    swigCMemOwnDerived = own;
    super.swigSetCMemOwn(own);
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwnDerived) {
        swigCMemOwnDerived = false;
        QuantLibJNI.delete_PiecewiseNaturalLogCubicSpreadDiscount(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public PiecewiseNaturalLogCubicSpreadDiscount(YieldTermStructureHandle baseCurve, RateHelperVector instruments, SplineLogCubic interpolator, IterativeBootstrap bootstrap) {
    this(QuantLibJNI.new_PiecewiseNaturalLogCubicSpreadDiscount__SWIG_0(YieldTermStructureHandle.getCPtr(baseCurve), baseCurve, RateHelperVector.getCPtr(instruments), instruments, SplineLogCubic.getCPtr(interpolator), interpolator, IterativeBootstrap.getCPtr(bootstrap), bootstrap), true);
  }

  public PiecewiseNaturalLogCubicSpreadDiscount(YieldTermStructureHandle baseCurve, RateHelperVector instruments, SplineLogCubic interpolator) {
    this(QuantLibJNI.new_PiecewiseNaturalLogCubicSpreadDiscount__SWIG_1(YieldTermStructureHandle.getCPtr(baseCurve), baseCurve, RateHelperVector.getCPtr(instruments), instruments, SplineLogCubic.getCPtr(interpolator), interpolator), true);
  }

  public PiecewiseNaturalLogCubicSpreadDiscount(YieldTermStructureHandle baseCurve, RateHelperVector instruments) {
    this(QuantLibJNI.new_PiecewiseNaturalLogCubicSpreadDiscount__SWIG_2(YieldTermStructureHandle.getCPtr(baseCurve), baseCurve, RateHelperVector.getCPtr(instruments), instruments), true);
  }

  public YieldTermStructureHandle baseCurve() {
    return new YieldTermStructureHandle(QuantLibJNI.PiecewiseNaturalLogCubicSpreadDiscount_baseCurve(swigCPtr, this), false);
  }

  public DateVector dates() {
    return new DateVector(QuantLibJNI.PiecewiseNaturalLogCubicSpreadDiscount_dates(swigCPtr, this), false);
  }

  public DoubleVector times() {
    return new DoubleVector(QuantLibJNI.PiecewiseNaturalLogCubicSpreadDiscount_times(swigCPtr, this), false);
  }

  public DoubleVector data() {
    return new DoubleVector(QuantLibJNI.PiecewiseNaturalLogCubicSpreadDiscount_data(swigCPtr, this), false);
  }

  public NodeVector nodes() {
    return new NodeVector(QuantLibJNI.PiecewiseNaturalLogCubicSpreadDiscount_nodes(swigCPtr, this), true);
  }

  public void recalculate() {
    QuantLibJNI.PiecewiseNaturalLogCubicSpreadDiscount_recalculate(swigCPtr, this);
  }

  public void freeze() {
    QuantLibJNI.PiecewiseNaturalLogCubicSpreadDiscount_freeze(swigCPtr, this);
  }

  public void unfreeze() {
    QuantLibJNI.PiecewiseNaturalLogCubicSpreadDiscount_unfreeze(swigCPtr, this);
  }

}
