/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.4.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.luopc.platform.quantlib;

public class PiecewiseBlackVarianceSurface extends BlackVolTermStructure {
  private transient long swigCPtr;
  private transient boolean swigCMemOwnDerived;

  protected PiecewiseBlackVarianceSurface(long cPtr, boolean cMemoryOwn) {
    super(QuantLibJNI.PiecewiseBlackVarianceSurface_SWIGSmartPtrUpcast(cPtr), true);
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(PiecewiseBlackVarianceSurface obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void swigSetCMemOwn(boolean own) {
    swigCMemOwnDerived = own;
    super.swigSetCMemOwn(own);
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwnDerived) {
        swigCMemOwnDerived = false;
        QuantLibJNI.delete_PiecewiseBlackVarianceSurface(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public PiecewiseBlackVarianceSurface(Date referenceDate, DateVector dates, SmileSectionVector smileSections, DayCounter dayCounter) {
    this(QuantLibJNI.new_PiecewiseBlackVarianceSurface__SWIG_0(Date.getCPtr(referenceDate), referenceDate, DateVector.getCPtr(dates), dates, SmileSectionVector.getCPtr(smileSections), smileSections, DayCounter.getCPtr(dayCounter), dayCounter), true);
  }

  public PiecewiseBlackVarianceSurface(Date referenceDate, DateVector dates, SmileSectionVector smileSections) {
    this(QuantLibJNI.new_PiecewiseBlackVarianceSurface__SWIG_1(Date.getCPtr(referenceDate), referenceDate, DateVector.getCPtr(dates), dates, SmileSectionVector.getCPtr(smileSections), smileSections), true);
  }

  public static PiecewiseBlackVarianceSurface makeFromGrid(Date referenceDate, DateVector dates, DoubleVector strikes, Matrix blackVols, DayCounter dc) {
    long cPtr = QuantLibJNI.PiecewiseBlackVarianceSurface_makeFromGrid__SWIG_0(Date.getCPtr(referenceDate), referenceDate, DateVector.getCPtr(dates), dates, DoubleVector.getCPtr(strikes), strikes, Matrix.getCPtr(blackVols), blackVols, DayCounter.getCPtr(dc), dc);
    return (cPtr == 0) ? null : new PiecewiseBlackVarianceSurface(cPtr, true);
  }

  public static PiecewiseBlackVarianceSurface makeFromGrid(Date referenceDate, DateVector dates, DoubleVector strikes, Matrix blackVols) {
    long cPtr = QuantLibJNI.PiecewiseBlackVarianceSurface_makeFromGrid__SWIG_1(Date.getCPtr(referenceDate), referenceDate, DateVector.getCPtr(dates), dates, DoubleVector.getCPtr(strikes), strikes, Matrix.getCPtr(blackVols), blackVols);
    return (cPtr == 0) ? null : new PiecewiseBlackVarianceSurface(cPtr, true);
  }

}
