/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.4.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.luopc.platform.quantlib;

public class PiecewiseZeroInflation extends ZeroInflationTermStructure {
  private transient long swigCPtr;
  private transient boolean swigCMemOwnDerived;

  protected PiecewiseZeroInflation(long cPtr, boolean cMemoryOwn) {
    super(QuantLibJNI.PiecewiseZeroInflation_SWIGSmartPtrUpcast(cPtr), true);
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(PiecewiseZeroInflation obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void swigSetCMemOwn(boolean own) {
    swigCMemOwnDerived = own;
    super.swigSetCMemOwn(own);
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwnDerived) {
        swigCMemOwnDerived = false;
        QuantLibJNI.delete_PiecewiseZeroInflation(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public PiecewiseZeroInflation(Date referenceDate, Date baseDate, Frequency frequency, DayCounter dayCounter, ZeroHelperVector instruments, Seasonality seasonality, double accuracy, Linear i) {
    this(QuantLibJNI.new_PiecewiseZeroInflation__SWIG_0(Date.getCPtr(referenceDate), referenceDate, Date.getCPtr(baseDate), baseDate, frequency.swigValue(), DayCounter.getCPtr(dayCounter), dayCounter, ZeroHelperVector.getCPtr(instruments), instruments, Seasonality.getCPtr(seasonality), seasonality, accuracy, Linear.getCPtr(i), i), true);
  }

  public PiecewiseZeroInflation(Date referenceDate, Date baseDate, Frequency frequency, DayCounter dayCounter, ZeroHelperVector instruments, Seasonality seasonality, double accuracy) {
    this(QuantLibJNI.new_PiecewiseZeroInflation__SWIG_1(Date.getCPtr(referenceDate), referenceDate, Date.getCPtr(baseDate), baseDate, frequency.swigValue(), DayCounter.getCPtr(dayCounter), dayCounter, ZeroHelperVector.getCPtr(instruments), instruments, Seasonality.getCPtr(seasonality), seasonality, accuracy), true);
  }

  public PiecewiseZeroInflation(Date referenceDate, Date baseDate, Frequency frequency, DayCounter dayCounter, ZeroHelperVector instruments, Seasonality seasonality) {
    this(QuantLibJNI.new_PiecewiseZeroInflation__SWIG_2(Date.getCPtr(referenceDate), referenceDate, Date.getCPtr(baseDate), baseDate, frequency.swigValue(), DayCounter.getCPtr(dayCounter), dayCounter, ZeroHelperVector.getCPtr(instruments), instruments, Seasonality.getCPtr(seasonality), seasonality), true);
  }

  public PiecewiseZeroInflation(Date referenceDate, Date baseDate, Frequency frequency, DayCounter dayCounter, ZeroHelperVector instruments) {
    this(QuantLibJNI.new_PiecewiseZeroInflation__SWIG_3(Date.getCPtr(referenceDate), referenceDate, Date.getCPtr(baseDate), baseDate, frequency.swigValue(), DayCounter.getCPtr(dayCounter), dayCounter, ZeroHelperVector.getCPtr(instruments), instruments), true);
  }

  public DateVector dates() {
    return new DateVector(QuantLibJNI.PiecewiseZeroInflation_dates(swigCPtr, this), false);
  }

  public DoubleVector times() {
    return new DoubleVector(QuantLibJNI.PiecewiseZeroInflation_times(swigCPtr, this), false);
  }

  public DoubleVector data() {
    return new DoubleVector(QuantLibJNI.PiecewiseZeroInflation_data(swigCPtr, this), false);
  }

  public NodeVector nodes() {
    return new NodeVector(QuantLibJNI.PiecewiseZeroInflation_nodes(swigCPtr, this), true);
  }

}
