/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.4.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.luopc.platform.quantlib;

public class QdFpTanhSinhIterationScheme extends QdFpIterationScheme {
  private transient long swigCPtr;
  private transient boolean swigCMemOwnDerived;

  protected QdFpTanhSinhIterationScheme(long cPtr, boolean cMemoryOwn) {
    super(QuantLibJNI.QdFpTanhSinhIterationScheme_SWIGSmartPtrUpcast(cPtr), true);
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(QdFpTanhSinhIterationScheme obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void swigSetCMemOwn(boolean own) {
    swigCMemOwnDerived = own;
    super.swigSetCMemOwn(own);
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwnDerived) {
        swigCMemOwnDerived = false;
        QuantLibJNI.delete_QdFpTanhSinhIterationScheme(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public QdFpTanhSinhIterationScheme(long m, long n, double eps) {
    this(QuantLibJNI.new_QdFpTanhSinhIterationScheme(m, n, eps), true);
  }

}
