/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.luopc.platform.quantlib;

public class QuantoTermStructure extends YieldTermStructure {
  private transient long swigCPtr;
  private transient boolean swigCMemOwnDerived;

  protected QuantoTermStructure(long cPtr, boolean cMemoryOwn) {
    super(QuantLibJNI.QuantoTermStructure_SWIGSmartPtrUpcast(cPtr), true);
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(QuantoTermStructure obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void swigSetCMemOwn(boolean own) {
    swigCMemOwnDerived = own;
    super.swigSetCMemOwn(own);
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwnDerived) {
        swigCMemOwnDerived = false;
        QuantLibJNI.delete_QuantoTermStructure(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public QuantoTermStructure(YieldTermStructureHandle underlyingDividendTS, YieldTermStructureHandle riskFreeTS, YieldTermStructureHandle foreignRiskFreeTS, BlackVolTermStructureHandle underlyingBlackVolTS, double strike, BlackVolTermStructureHandle exchRateBlackVolTS, double exchRateATMlevel, double underlyingExchRateCorrelation) {
    this(QuantLibJNI.new_QuantoTermStructure(YieldTermStructureHandle.getCPtr(underlyingDividendTS), underlyingDividendTS, YieldTermStructureHandle.getCPtr(riskFreeTS), riskFreeTS, YieldTermStructureHandle.getCPtr(foreignRiskFreeTS), foreignRiskFreeTS, BlackVolTermStructureHandle.getCPtr(underlyingBlackVolTS), underlyingBlackVolTS, strike, BlackVolTermStructureHandle.getCPtr(exchRateBlackVolTS), exchRateBlackVolTS, exchRateATMlevel, underlyingExchRateCorrelation), true);
  }

}
