/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.luopc.platform.quantlib;

public class RangeAccrualPricerByBgm extends RangeAccrualPricer {
  private transient long swigCPtr;
  private transient boolean swigCMemOwnDerived;

  protected RangeAccrualPricerByBgm(long cPtr, boolean cMemoryOwn) {
    super(QuantLibJNI.RangeAccrualPricerByBgm_SWIGSmartPtrUpcast(cPtr), true);
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(RangeAccrualPricerByBgm obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void swigSetCMemOwn(boolean own) {
    swigCMemOwnDerived = own;
    super.swigSetCMemOwn(own);
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwnDerived) {
        swigCMemOwnDerived = false;
        QuantLibJNI.delete_RangeAccrualPricerByBgm(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public RangeAccrualPricerByBgm(double correlation, SmileSection smilesOnExpiry, SmileSection smilesOnPayment, boolean withSmile, boolean byCallSpread) {
    this(QuantLibJNI.new_RangeAccrualPricerByBgm(correlation, SmileSection.getCPtr(smilesOnExpiry), smilesOnExpiry, SmileSection.getCPtr(smilesOnPayment), smilesOnPayment, withSmile, byCallSpread), true);
  }

}
