/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.luopc.platform.quantlib;

public class RangeAccrualFloatersCoupon extends FloatingRateCoupon {
  private transient long swigCPtr;
  private transient boolean swigCMemOwnDerived;

  protected RangeAccrualFloatersCoupon(long cPtr, boolean cMemoryOwn) {
    super(QuantLibJNI.RangeAccrualFloatersCoupon_SWIGSmartPtrUpcast(cPtr), true);
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(RangeAccrualFloatersCoupon obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void swigSetCMemOwn(boolean own) {
    swigCMemOwnDerived = own;
    super.swigSetCMemOwn(own);
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwnDerived) {
        swigCMemOwnDerived = false;
        QuantLibJNI.delete_RangeAccrualFloatersCoupon(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public RangeAccrualFloatersCoupon(Date paymentDate, double nominal, IborIndex index, Date startDate, Date endDate, long fixingDays, DayCounter dayCounter, double gearing, double spread, Date refPeriodStart, Date refPeriodEnd, Schedule observationsSchedule, double lowerTrigger, double upperTrigger) {
    this(QuantLibJNI.new_RangeAccrualFloatersCoupon(Date.getCPtr(paymentDate), paymentDate, nominal, IborIndex.getCPtr(index), index, Date.getCPtr(startDate), startDate, Date.getCPtr(endDate), endDate, fixingDays, DayCounter.getCPtr(dayCounter), dayCounter, gearing, spread, Date.getCPtr(refPeriodStart), refPeriodStart, Date.getCPtr(refPeriodEnd), refPeriodEnd, Schedule.getCPtr(observationsSchedule), observationsSchedule, lowerTrigger, upperTrigger), true);
  }

}
