/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.luopc.platform.quantlib;

public class RelinkableLocalVolTermStructureHandle extends LocalVolTermStructureHandle {
  private transient long swigCPtr;

  protected RelinkableLocalVolTermStructureHandle(long cPtr, boolean cMemoryOwn) {
    super(QuantLibJNI.RelinkableLocalVolTermStructureHandle_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(RelinkableLocalVolTermStructureHandle obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        QuantLibJNI.delete_RelinkableLocalVolTermStructureHandle(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public RelinkableLocalVolTermStructureHandle() {
    this(QuantLibJNI.new_RelinkableLocalVolTermStructureHandle__SWIG_0(), true);
  }

  public RelinkableLocalVolTermStructureHandle(LocalVolTermStructure p, boolean registerAsObserver) {
    this(QuantLibJNI.new_RelinkableLocalVolTermStructureHandle__SWIG_1(LocalVolTermStructure.getCPtr(p), p, registerAsObserver), true);
  }

  public RelinkableLocalVolTermStructureHandle(LocalVolTermStructure p) {
    this(QuantLibJNI.new_RelinkableLocalVolTermStructureHandle__SWIG_2(LocalVolTermStructure.getCPtr(p), p), true);
  }

  public void linkTo(LocalVolTermStructure h, boolean registerAsObserver) {
    QuantLibJNI.RelinkableLocalVolTermStructureHandle_linkTo__SWIG_0(swigCPtr, this, LocalVolTermStructure.getCPtr(h), h, registerAsObserver);
  }

  public void linkTo(LocalVolTermStructure h) {
    QuantLibJNI.RelinkableLocalVolTermStructureHandle_linkTo__SWIG_1(swigCPtr, this, LocalVolTermStructure.getCPtr(h), h);
  }

  public void reset() {
    QuantLibJNI.RelinkableLocalVolTermStructureHandle_reset(swigCPtr, this);
  }

}
