/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.luopc.platform.quantlib;

public class RelinkableQuoteHandle extends QuoteHandle {
  private transient long swigCPtr;

  protected RelinkableQuoteHandle(long cPtr, boolean cMemoryOwn) {
    super(QuantLibJNI.RelinkableQuoteHandle_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(RelinkableQuoteHandle obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        QuantLibJNI.delete_RelinkableQuoteHandle(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public RelinkableQuoteHandle() {
    this(QuantLibJNI.new_RelinkableQuoteHandle__SWIG_0(), true);
  }

  public RelinkableQuoteHandle(Quote p, boolean registerAsObserver) {
    this(QuantLibJNI.new_RelinkableQuoteHandle__SWIG_1(Quote.getCPtr(p), p, registerAsObserver), true);
  }

  public RelinkableQuoteHandle(Quote p) {
    this(QuantLibJNI.new_RelinkableQuoteHandle__SWIG_2(Quote.getCPtr(p), p), true);
  }

  public void linkTo(Quote h, boolean registerAsObserver) {
    QuantLibJNI.RelinkableQuoteHandle_linkTo__SWIG_0(swigCPtr, this, Quote.getCPtr(h), h, registerAsObserver);
  }

  public void linkTo(Quote h) {
    QuantLibJNI.RelinkableQuoteHandle_linkTo__SWIG_1(swigCPtr, this, Quote.getCPtr(h), h);
  }

  public void reset() {
    QuantLibJNI.RelinkableQuoteHandle_reset(swigCPtr, this);
  }

}
