/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.luopc.platform.quantlib;

public class RelinkableZeroInflationTermStructureHandle extends ZeroInflationTermStructureHandle {
  private transient long swigCPtr;

  protected RelinkableZeroInflationTermStructureHandle(long cPtr, boolean cMemoryOwn) {
    super(QuantLibJNI.RelinkableZeroInflationTermStructureHandle_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(RelinkableZeroInflationTermStructureHandle obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        QuantLibJNI.delete_RelinkableZeroInflationTermStructureHandle(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public RelinkableZeroInflationTermStructureHandle() {
    this(QuantLibJNI.new_RelinkableZeroInflationTermStructureHandle__SWIG_0(), true);
  }

  public RelinkableZeroInflationTermStructureHandle(ZeroInflationTermStructure p, boolean registerAsObserver) {
    this(QuantLibJNI.new_RelinkableZeroInflationTermStructureHandle__SWIG_1(ZeroInflationTermStructure.getCPtr(p), p, registerAsObserver), true);
  }

  public RelinkableZeroInflationTermStructureHandle(ZeroInflationTermStructure p) {
    this(QuantLibJNI.new_RelinkableZeroInflationTermStructureHandle__SWIG_2(ZeroInflationTermStructure.getCPtr(p), p), true);
  }

  public void linkTo(ZeroInflationTermStructure h, boolean registerAsObserver) {
    QuantLibJNI.RelinkableZeroInflationTermStructureHandle_linkTo__SWIG_0(swigCPtr, this, ZeroInflationTermStructure.getCPtr(h), h, registerAsObserver);
  }

  public void linkTo(ZeroInflationTermStructure h) {
    QuantLibJNI.RelinkableZeroInflationTermStructureHandle_linkTo__SWIG_1(swigCPtr, this, ZeroInflationTermStructure.getCPtr(h), h);
  }

  public void reset() {
    QuantLibJNI.RelinkableZeroInflationTermStructureHandle_reset(swigCPtr, this);
  }

}
