/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.luopc.platform.quantlib;

public class RelinkableShortRateModelHandle extends ShortRateModelHandle {
  private transient long swigCPtr;

  protected RelinkableShortRateModelHandle(long cPtr, boolean cMemoryOwn) {
    super(QuantLibJNI.RelinkableShortRateModelHandle_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(RelinkableShortRateModelHandle obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(RelinkableShortRateModelHandle obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        QuantLibJNI.delete_RelinkableShortRateModelHandle(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public RelinkableShortRateModelHandle() {
    this(QuantLibJNI.new_RelinkableShortRateModelHandle__SWIG_0(), true);
  }

  public RelinkableShortRateModelHandle(ShortRateModel p, boolean registerAsObserver) {
    this(QuantLibJNI.new_RelinkableShortRateModelHandle__SWIG_1(ShortRateModel.getCPtr(p), p, registerAsObserver), true);
  }

  public RelinkableShortRateModelHandle(ShortRateModel p) {
    this(QuantLibJNI.new_RelinkableShortRateModelHandle__SWIG_2(ShortRateModel.getCPtr(p), p), true);
  }

  public void linkTo(ShortRateModel h, boolean registerAsObserver) {
    QuantLibJNI.RelinkableShortRateModelHandle_linkTo__SWIG_0(swigCPtr, this, ShortRateModel.getCPtr(h), h, registerAsObserver);
  }

  public void linkTo(ShortRateModel h) {
    QuantLibJNI.RelinkableShortRateModelHandle_linkTo__SWIG_1(swigCPtr, this, ShortRateModel.getCPtr(h), h);
  }

  public void reset() {
    QuantLibJNI.RelinkableShortRateModelHandle_reset(swigCPtr, this);
  }

}
