/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.luopc.platform.quantlib;

public class RelinkableSwaptionVolatilityStructureHandle extends SwaptionVolatilityStructureHandle {
  private transient long swigCPtr;

  protected RelinkableSwaptionVolatilityStructureHandle(long cPtr, boolean cMemoryOwn) {
    super(QuantLibJNI.RelinkableSwaptionVolatilityStructureHandle_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(RelinkableSwaptionVolatilityStructureHandle obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(RelinkableSwaptionVolatilityStructureHandle obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        QuantLibJNI.delete_RelinkableSwaptionVolatilityStructureHandle(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public RelinkableSwaptionVolatilityStructureHandle() {
    this(QuantLibJNI.new_RelinkableSwaptionVolatilityStructureHandle__SWIG_0(), true);
  }

  public RelinkableSwaptionVolatilityStructureHandle(SwaptionVolatilityStructure p, boolean registerAsObserver) {
    this(QuantLibJNI.new_RelinkableSwaptionVolatilityStructureHandle__SWIG_1(SwaptionVolatilityStructure.getCPtr(p), p, registerAsObserver), true);
  }

  public RelinkableSwaptionVolatilityStructureHandle(SwaptionVolatilityStructure p) {
    this(QuantLibJNI.new_RelinkableSwaptionVolatilityStructureHandle__SWIG_2(SwaptionVolatilityStructure.getCPtr(p), p), true);
  }

  public void linkTo(SwaptionVolatilityStructure h, boolean registerAsObserver) {
    QuantLibJNI.RelinkableSwaptionVolatilityStructureHandle_linkTo__SWIG_0(swigCPtr, this, SwaptionVolatilityStructure.getCPtr(h), h, registerAsObserver);
  }

  public void linkTo(SwaptionVolatilityStructure h) {
    QuantLibJNI.RelinkableSwaptionVolatilityStructureHandle_linkTo__SWIG_1(swigCPtr, this, SwaptionVolatilityStructure.getCPtr(h), h);
  }

  public void reset() {
    QuantLibJNI.RelinkableSwaptionVolatilityStructureHandle_reset(swigCPtr, this);
  }

}
