/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.luopc.platform.quantlib;

public class RelinkableYoYInflationTermStructureHandle extends YoYInflationTermStructureHandle {
  private transient long swigCPtr;

  protected RelinkableYoYInflationTermStructureHandle(long cPtr, boolean cMemoryOwn) {
    super(QuantLibJNI.RelinkableYoYInflationTermStructureHandle_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(RelinkableYoYInflationTermStructureHandle obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        QuantLibJNI.delete_RelinkableYoYInflationTermStructureHandle(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public RelinkableYoYInflationTermStructureHandle() {
    this(QuantLibJNI.new_RelinkableYoYInflationTermStructureHandle__SWIG_0(), true);
  }

  public RelinkableYoYInflationTermStructureHandle(YoYInflationTermStructure p, boolean registerAsObserver) {
    this(QuantLibJNI.new_RelinkableYoYInflationTermStructureHandle__SWIG_1(YoYInflationTermStructure.getCPtr(p), p, registerAsObserver), true);
  }

  public RelinkableYoYInflationTermStructureHandle(YoYInflationTermStructure p) {
    this(QuantLibJNI.new_RelinkableYoYInflationTermStructureHandle__SWIG_2(YoYInflationTermStructure.getCPtr(p), p), true);
  }

  public void linkTo(YoYInflationTermStructure h, boolean registerAsObserver) {
    QuantLibJNI.RelinkableYoYInflationTermStructureHandle_linkTo__SWIG_0(swigCPtr, this, YoYInflationTermStructure.getCPtr(h), h, registerAsObserver);
  }

  public void linkTo(YoYInflationTermStructure h) {
    QuantLibJNI.RelinkableYoYInflationTermStructureHandle_linkTo__SWIG_1(swigCPtr, this, YoYInflationTermStructure.getCPtr(h), h);
  }

  public void reset() {
    QuantLibJNI.RelinkableYoYInflationTermStructureHandle_reset(swigCPtr, this);
  }

}
