/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.luopc.platform.quantlib;

public class RelinkableCapFloorTermVolatilityStructureHandle extends CapFloorTermVolatilityStructureHandle {
  private transient long swigCPtr;

  protected RelinkableCapFloorTermVolatilityStructureHandle(long cPtr, boolean cMemoryOwn) {
    super(QuantLibJNI.RelinkableCapFloorTermVolatilityStructureHandle_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(RelinkableCapFloorTermVolatilityStructureHandle obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        QuantLibJNI.delete_RelinkableCapFloorTermVolatilityStructureHandle(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public RelinkableCapFloorTermVolatilityStructureHandle() {
    this(QuantLibJNI.new_RelinkableCapFloorTermVolatilityStructureHandle__SWIG_0(), true);
  }

  public RelinkableCapFloorTermVolatilityStructureHandle(CapFloorTermVolatilityStructure p, boolean registerAsObserver) {
    this(QuantLibJNI.new_RelinkableCapFloorTermVolatilityStructureHandle__SWIG_1(CapFloorTermVolatilityStructure.getCPtr(p), p, registerAsObserver), true);
  }

  public RelinkableCapFloorTermVolatilityStructureHandle(CapFloorTermVolatilityStructure p) {
    this(QuantLibJNI.new_RelinkableCapFloorTermVolatilityStructureHandle__SWIG_2(CapFloorTermVolatilityStructure.getCPtr(p), p), true);
  }

  public void linkTo(CapFloorTermVolatilityStructure h, boolean registerAsObserver) {
    QuantLibJNI.RelinkableCapFloorTermVolatilityStructureHandle_linkTo__SWIG_0(swigCPtr, this, CapFloorTermVolatilityStructure.getCPtr(h), h, registerAsObserver);
  }

  public void linkTo(CapFloorTermVolatilityStructure h) {
    QuantLibJNI.RelinkableCapFloorTermVolatilityStructureHandle_linkTo__SWIG_1(swigCPtr, this, CapFloorTermVolatilityStructure.getCPtr(h), h);
  }

  public void reset() {
    QuantLibJNI.RelinkableCapFloorTermVolatilityStructureHandle_reset(swigCPtr, this);
  }

}
