/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.luopc.platform.quantlib;

public class SimpleChooserOption extends OneAssetOption {
  private transient long swigCPtr;
  private transient boolean swigCMemOwnDerived;

  protected SimpleChooserOption(long cPtr, boolean cMemoryOwn) {
    super(QuantLibJNI.SimpleChooserOption_SWIGSmartPtrUpcast(cPtr), true);
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SimpleChooserOption obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void swigSetCMemOwn(boolean own) {
    swigCMemOwnDerived = own;
    super.swigSetCMemOwn(own);
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwnDerived) {
        swigCMemOwnDerived = false;
        QuantLibJNI.delete_SimpleChooserOption(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public SimpleChooserOption(Date choosingDate, double strike, Exercise exercise) {
    this(QuantLibJNI.new_SimpleChooserOption(Date.getCPtr(choosingDate), choosingDate, strike, Exercise.getCPtr(exercise), exercise), true);
  }

}
