/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.luopc.platform.quantlib;

public class SpreadedParabolicCubicZeroInterpolatedTermStructure extends YieldTermStructure {
  private transient long swigCPtr;
  private transient boolean swigCMemOwnDerived;

  protected SpreadedParabolicCubicZeroInterpolatedTermStructure(long cPtr, boolean cMemoryOwn) {
    super(QuantLibJNI.SpreadedParabolicCubicZeroInterpolatedTermStructure_SWIGSmartPtrUpcast(cPtr), true);
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SpreadedParabolicCubicZeroInterpolatedTermStructure obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void swigSetCMemOwn(boolean own) {
    swigCMemOwnDerived = own;
    super.swigSetCMemOwn(own);
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwnDerived) {
        swigCMemOwnDerived = false;
        QuantLibJNI.delete_SpreadedParabolicCubicZeroInterpolatedTermStructure(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public SpreadedParabolicCubicZeroInterpolatedTermStructure(YieldTermStructureHandle baseCurve, QuoteHandleVector spreads, DateVector dates, Compounding comp, Frequency freq, DayCounter dc, ParabolicCubic factory) {
    this(QuantLibJNI.new_SpreadedParabolicCubicZeroInterpolatedTermStructure__SWIG_0(YieldTermStructureHandle.getCPtr(baseCurve), baseCurve, QuoteHandleVector.getCPtr(spreads), spreads, DateVector.getCPtr(dates), dates, comp.swigValue(), freq.swigValue(), DayCounter.getCPtr(dc), dc, ParabolicCubic.getCPtr(factory), factory), true);
  }

  public SpreadedParabolicCubicZeroInterpolatedTermStructure(YieldTermStructureHandle baseCurve, QuoteHandleVector spreads, DateVector dates, Compounding comp, Frequency freq, DayCounter dc) {
    this(QuantLibJNI.new_SpreadedParabolicCubicZeroInterpolatedTermStructure__SWIG_1(YieldTermStructureHandle.getCPtr(baseCurve), baseCurve, QuoteHandleVector.getCPtr(spreads), spreads, DateVector.getCPtr(dates), dates, comp.swigValue(), freq.swigValue(), DayCounter.getCPtr(dc), dc), true);
  }

  public SpreadedParabolicCubicZeroInterpolatedTermStructure(YieldTermStructureHandle baseCurve, QuoteHandleVector spreads, DateVector dates, Compounding comp, Frequency freq) {
    this(QuantLibJNI.new_SpreadedParabolicCubicZeroInterpolatedTermStructure__SWIG_2(YieldTermStructureHandle.getCPtr(baseCurve), baseCurve, QuoteHandleVector.getCPtr(spreads), spreads, DateVector.getCPtr(dates), dates, comp.swigValue(), freq.swigValue()), true);
  }

  public SpreadedParabolicCubicZeroInterpolatedTermStructure(YieldTermStructureHandle baseCurve, QuoteHandleVector spreads, DateVector dates, Compounding comp) {
    this(QuantLibJNI.new_SpreadedParabolicCubicZeroInterpolatedTermStructure__SWIG_3(YieldTermStructureHandle.getCPtr(baseCurve), baseCurve, QuoteHandleVector.getCPtr(spreads), spreads, DateVector.getCPtr(dates), dates, comp.swigValue()), true);
  }

  public SpreadedParabolicCubicZeroInterpolatedTermStructure(YieldTermStructureHandle baseCurve, QuoteHandleVector spreads, DateVector dates) {
    this(QuantLibJNI.new_SpreadedParabolicCubicZeroInterpolatedTermStructure__SWIG_4(YieldTermStructureHandle.getCPtr(baseCurve), baseCurve, QuoteHandleVector.getCPtr(spreads), spreads, DateVector.getCPtr(dates), dates), true);
  }

}
