/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.luopc.platform.quantlib;

public class SpreadFittingMethod extends FittingMethod {
  private transient long swigCPtr;
  private transient boolean swigCMemOwnDerived;

  protected SpreadFittingMethod(long cPtr, boolean cMemoryOwn) {
    super(QuantLibJNI.SpreadFittingMethod_SWIGSmartPtrUpcast(cPtr), true);
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SpreadFittingMethod obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void swigSetCMemOwn(boolean own) {
    swigCMemOwnDerived = own;
    super.swigSetCMemOwn(own);
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwnDerived) {
        swigCMemOwnDerived = false;
        QuantLibJNI.delete_SpreadFittingMethod(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public SpreadFittingMethod(FittingMethod method, YieldTermStructureHandle discountCurve, double minCutoffTime, double maxCutoffTime) {
    this(QuantLibJNI.new_SpreadFittingMethod__SWIG_0(FittingMethod.getCPtr(method), method, YieldTermStructureHandle.getCPtr(discountCurve), discountCurve, minCutoffTime, maxCutoffTime), true);
  }

  public SpreadFittingMethod(FittingMethod method, YieldTermStructureHandle discountCurve, double minCutoffTime) {
    this(QuantLibJNI.new_SpreadFittingMethod__SWIG_1(FittingMethod.getCPtr(method), method, YieldTermStructureHandle.getCPtr(discountCurve), discountCurve, minCutoffTime), true);
  }

  public SpreadFittingMethod(FittingMethod method, YieldTermStructureHandle discountCurve) {
    this(QuantLibJNI.new_SpreadFittingMethod__SWIG_2(FittingMethod.getCPtr(method), method, YieldTermStructureHandle.getCPtr(discountCurve), discountCurve), true);
  }

}
