/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.4.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.luopc.platform.quantlib;

public class StrikedTypePayoff extends TypePayoff {
  private transient long swigCPtr;
  private transient boolean swigCMemOwnDerived;

  protected StrikedTypePayoff(long cPtr, boolean cMemoryOwn) {
    super(QuantLibJNI.StrikedTypePayoff_SWIGSmartPtrUpcast(cPtr), true);
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(StrikedTypePayoff obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void swigSetCMemOwn(boolean own) {
    swigCMemOwnDerived = own;
    super.swigSetCMemOwn(own);
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwnDerived) {
        swigCMemOwnDerived = false;
        QuantLibJNI.delete_StrikedTypePayoff(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public double strike() {
    return QuantLibJNI.StrikedTypePayoff_strike(swigCPtr, this);
  }

}
