/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.4.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.luopc.platform.quantlib;

public class SuoWangDoubleBarrierEngine extends PricingEngine {
  private transient long swigCPtr;
  private transient boolean swigCMemOwnDerived;

  protected SuoWangDoubleBarrierEngine(long cPtr, boolean cMemoryOwn) {
    super(QuantLibJNI.SuoWangDoubleBarrierEngine_SWIGSmartPtrUpcast(cPtr), true);
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SuoWangDoubleBarrierEngine obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void swigSetCMemOwn(boolean own) {
    swigCMemOwnDerived = own;
    super.swigSetCMemOwn(own);
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwnDerived) {
        swigCMemOwnDerived = false;
        QuantLibJNI.delete_SuoWangDoubleBarrierEngine(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public SuoWangDoubleBarrierEngine(GeneralizedBlackScholesProcess process, int series) {
    this(QuantLibJNI.new_SuoWangDoubleBarrierEngine__SWIG_0(GeneralizedBlackScholesProcess.getCPtr(process), process, series), true);
  }

  public SuoWangDoubleBarrierEngine(GeneralizedBlackScholesProcess process) {
    this(QuantLibJNI.new_SuoWangDoubleBarrierEngine__SWIG_1(GeneralizedBlackScholesProcess.getCPtr(process), process), true);
  }

}
