/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.luopc.platform.quantlib;

public class SvenssonFitting extends FittingMethod {
  private transient long swigCPtr;
  private transient boolean swigCMemOwnDerived;

  protected SvenssonFitting(long cPtr, boolean cMemoryOwn) {
    super(QuantLibJNI.SvenssonFitting_SWIGSmartPtrUpcast(cPtr), true);
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SvenssonFitting obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void swigSetCMemOwn(boolean own) {
    swigCMemOwnDerived = own;
    super.swigSetCMemOwn(own);
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwnDerived) {
        swigCMemOwnDerived = false;
        QuantLibJNI.delete_SvenssonFitting(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public SvenssonFitting(Array weights, OptimizationMethod optimizationMethod, Array l2, double minCutoffTime, double maxCutoffTime, Constraint constraint) {
    this(QuantLibJNI.new_SvenssonFitting__SWIG_0(Array.getCPtr(weights), weights, OptimizationMethod.getCPtr(optimizationMethod), optimizationMethod, Array.getCPtr(l2), l2, minCutoffTime, maxCutoffTime, Constraint.getCPtr(constraint), constraint), true);
  }

  public SvenssonFitting(Array weights, OptimizationMethod optimizationMethod, Array l2, double minCutoffTime, double maxCutoffTime) {
    this(QuantLibJNI.new_SvenssonFitting__SWIG_1(Array.getCPtr(weights), weights, OptimizationMethod.getCPtr(optimizationMethod), optimizationMethod, Array.getCPtr(l2), l2, minCutoffTime, maxCutoffTime), true);
  }

  public SvenssonFitting(Array weights, OptimizationMethod optimizationMethod, Array l2, double minCutoffTime) {
    this(QuantLibJNI.new_SvenssonFitting__SWIG_2(Array.getCPtr(weights), weights, OptimizationMethod.getCPtr(optimizationMethod), optimizationMethod, Array.getCPtr(l2), l2, minCutoffTime), true);
  }

  public SvenssonFitting(Array weights, OptimizationMethod optimizationMethod, Array l2) {
    this(QuantLibJNI.new_SvenssonFitting__SWIG_3(Array.getCPtr(weights), weights, OptimizationMethod.getCPtr(optimizationMethod), optimizationMethod, Array.getCPtr(l2), l2), true);
  }

  public SvenssonFitting(Array weights, OptimizationMethod optimizationMethod) {
    this(QuantLibJNI.new_SvenssonFitting__SWIG_4(Array.getCPtr(weights), weights, OptimizationMethod.getCPtr(optimizationMethod), optimizationMethod), true);
  }

  public SvenssonFitting(Array weights) {
    this(QuantLibJNI.new_SvenssonFitting__SWIG_5(Array.getCPtr(weights), weights), true);
  }

  public SvenssonFitting() {
    this(QuantLibJNI.new_SvenssonFitting__SWIG_6(), true);
  }

}
