/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.luopc.platform.quantlib;

public class SviSmileSection extends SmileSection {
  private transient long swigCPtr;
  private transient boolean swigCMemOwnDerived;

  protected SviSmileSection(long cPtr, boolean cMemoryOwn) {
    super(QuantLibJNI.SviSmileSection_SWIGSmartPtrUpcast(cPtr), true);
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SviSmileSection obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void swigSetCMemOwn(boolean own) {
    swigCMemOwnDerived = own;
    super.swigSetCMemOwn(own);
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwnDerived) {
        swigCMemOwnDerived = false;
        QuantLibJNI.delete_SviSmileSection(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public SviSmileSection(double timeToExpiry, double forward, DoubleVector sviParameters) {
    this(QuantLibJNI.new_SviSmileSection__SWIG_0(timeToExpiry, forward, DoubleVector.getCPtr(sviParameters), sviParameters), true);
  }

  public SviSmileSection(Date d, double forward, DoubleVector sviParameters, DayCounter dc) {
    this(QuantLibJNI.new_SviSmileSection__SWIG_1(Date.getCPtr(d), d, forward, DoubleVector.getCPtr(sviParameters), sviParameters, DayCounter.getCPtr(dc), dc), true);
  }

  public SviSmileSection(Date d, double forward, DoubleVector sviParameters) {
    this(QuantLibJNI.new_SviSmileSection__SWIG_2(Date.getCPtr(d), d, forward, DoubleVector.getCPtr(sviParameters), sviParameters), true);
  }

}
