/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.4.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.luopc.platform.quantlib;

public class SymmetricSchurDecomposition {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected SymmetricSchurDecomposition(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SymmetricSchurDecomposition obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(SymmetricSchurDecomposition obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        QuantLibJNI.delete_SymmetricSchurDecomposition(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public SymmetricSchurDecomposition(Matrix s) {
    this(QuantLibJNI.new_SymmetricSchurDecomposition(Matrix.getCPtr(s), s), true);
  }

  public Array eigenvalues() {
    return new Array(QuantLibJNI.SymmetricSchurDecomposition_eigenvalues(swigCPtr, this), false);
  }

  public Matrix eigenvectors() {
    return new Matrix(QuantLibJNI.SymmetricSchurDecomposition_eigenvectors(swigCPtr, this), false);
  }

}
