/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.luopc.platform.quantlib;

public class UGXCurrency extends Currency {
  private transient long swigCPtr;

  protected UGXCurrency(long cPtr, boolean cMemoryOwn) {
    super(QuantLibJNI.UGXCurrency_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(UGXCurrency obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        QuantLibJNI.delete_UGXCurrency(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public UGXCurrency() {
    this(QuantLibJNI.new_UGXCurrency(), true);
  }

}
