/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.luopc.platform.quantlib;

public class UltimateForwardTermStructure extends YieldTermStructure {
  private transient long swigCPtr;
  private transient boolean swigCMemOwnDerived;

  protected UltimateForwardTermStructure(long cPtr, boolean cMemoryOwn) {
    super(QuantLibJNI.UltimateForwardTermStructure_SWIGSmartPtrUpcast(cPtr), true);
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(UltimateForwardTermStructure obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void swigSetCMemOwn(boolean own) {
    swigCMemOwnDerived = own;
    super.swigSetCMemOwn(own);
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwnDerived) {
        swigCMemOwnDerived = false;
        QuantLibJNI.delete_UltimateForwardTermStructure(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public UltimateForwardTermStructure(YieldTermStructureHandle curveHandle, QuoteHandle lastLiquidForwardRate, QuoteHandle ultimateForwardRate, Period firstSmoothingPoint, double alpha, OptionalInteger roundingDigits, Compounding compounding, Frequency frequency) {
    this(QuantLibJNI.new_UltimateForwardTermStructure__SWIG_0(YieldTermStructureHandle.getCPtr(curveHandle), curveHandle, QuoteHandle.getCPtr(lastLiquidForwardRate), lastLiquidForwardRate, QuoteHandle.getCPtr(ultimateForwardRate), ultimateForwardRate, Period.getCPtr(firstSmoothingPoint), firstSmoothingPoint, alpha, OptionalInteger.getCPtr(roundingDigits), roundingDigits, compounding.swigValue(), frequency.swigValue()), true);
  }

  public UltimateForwardTermStructure(YieldTermStructureHandle curveHandle, QuoteHandle lastLiquidForwardRate, QuoteHandle ultimateForwardRate, Period firstSmoothingPoint, double alpha, OptionalInteger roundingDigits, Compounding compounding) {
    this(QuantLibJNI.new_UltimateForwardTermStructure__SWIG_1(YieldTermStructureHandle.getCPtr(curveHandle), curveHandle, QuoteHandle.getCPtr(lastLiquidForwardRate), lastLiquidForwardRate, QuoteHandle.getCPtr(ultimateForwardRate), ultimateForwardRate, Period.getCPtr(firstSmoothingPoint), firstSmoothingPoint, alpha, OptionalInteger.getCPtr(roundingDigits), roundingDigits, compounding.swigValue()), true);
  }

  public UltimateForwardTermStructure(YieldTermStructureHandle curveHandle, QuoteHandle lastLiquidForwardRate, QuoteHandle ultimateForwardRate, Period firstSmoothingPoint, double alpha, OptionalInteger roundingDigits) {
    this(QuantLibJNI.new_UltimateForwardTermStructure__SWIG_2(YieldTermStructureHandle.getCPtr(curveHandle), curveHandle, QuoteHandle.getCPtr(lastLiquidForwardRate), lastLiquidForwardRate, QuoteHandle.getCPtr(ultimateForwardRate), ultimateForwardRate, Period.getCPtr(firstSmoothingPoint), firstSmoothingPoint, alpha, OptionalInteger.getCPtr(roundingDigits), roundingDigits), true);
  }

  public UltimateForwardTermStructure(YieldTermStructureHandle curveHandle, QuoteHandle lastLiquidForwardRate, QuoteHandle ultimateForwardRate, Period firstSmoothingPoint, double alpha) {
    this(QuantLibJNI.new_UltimateForwardTermStructure__SWIG_3(YieldTermStructureHandle.getCPtr(curveHandle), curveHandle, QuoteHandle.getCPtr(lastLiquidForwardRate), lastLiquidForwardRate, QuoteHandle.getCPtr(ultimateForwardRate), ultimateForwardRate, Period.getCPtr(firstSmoothingPoint), firstSmoothingPoint, alpha), true);
  }

}
