/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.luopc.platform.quantlib;

public class UnsignedIntPair {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected UnsignedIntPair(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(UnsignedIntPair obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        QuantLibJNI.delete_UnsignedIntPair(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public UnsignedIntPair() {
    this(QuantLibJNI.new_UnsignedIntPair__SWIG_0(), true);
  }

  public UnsignedIntPair(long first, long second) {
    this(QuantLibJNI.new_UnsignedIntPair__SWIG_1(first, second), true);
  }

  public UnsignedIntPair(UnsignedIntPair other) {
    this(QuantLibJNI.new_UnsignedIntPair__SWIG_2(UnsignedIntPair.getCPtr(other), other), true);
  }

  public void setFirst(long value) {
    QuantLibJNI.UnsignedIntPair_first_set(swigCPtr, this, value);
  }

  public long getFirst() {
    return QuantLibJNI.UnsignedIntPair_first_get(swigCPtr, this);
  }

  public void setSecond(long value) {
    QuantLibJNI.UnsignedIntPair_second_set(swigCPtr, this, value);
  }

  public long getSecond() {
    return QuantLibJNI.UnsignedIntPair_second_get(swigCPtr, this);
  }

}
