/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.4.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.luopc.platform.quantlib;

public class WriterExtensibleOption extends OneAssetOption {
  private transient long swigCPtr;
  private transient boolean swigCMemOwnDerived;

  protected WriterExtensibleOption(long cPtr, boolean cMemoryOwn) {
    super(QuantLibJNI.WriterExtensibleOption_SWIGSmartPtrUpcast(cPtr), true);
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(WriterExtensibleOption obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void swigSetCMemOwn(boolean own) {
    swigCMemOwnDerived = own;
    super.swigSetCMemOwn(own);
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwnDerived) {
        swigCMemOwnDerived = false;
        QuantLibJNI.delete_WriterExtensibleOption(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public WriterExtensibleOption(SWIGTYPE_p_ext__shared_ptrT_PlainVanillaPayoff_t payoff1, Exercise exercise1, SWIGTYPE_p_ext__shared_ptrT_PlainVanillaPayoff_t payoff2, Exercise exercise2) {
    this(QuantLibJNI.new_WriterExtensibleOption(SWIGTYPE_p_ext__shared_ptrT_PlainVanillaPayoff_t.getCPtr(payoff1), Exercise.getCPtr(exercise1), exercise1, SWIGTYPE_p_ext__shared_ptrT_PlainVanillaPayoff_t.getCPtr(payoff2), Exercise.getCPtr(exercise2), exercise2), true);
  }

  public Payoff payoff2() {
    long cPtr = QuantLibJNI.WriterExtensibleOption_payoff2(swigCPtr, this);
    return (cPtr == 0) ? null : new Payoff(cPtr, true);
  }

  public Exercise exercise2() {
    long cPtr = QuantLibJNI.WriterExtensibleOption_exercise2(swigCPtr, this);
    return (cPtr == 0) ? null : new Exercise(cPtr, true);
  }

}
