/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.luopc.platform.quantlib;

public class Xoshiro256StarStarUniformRng {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Xoshiro256StarStarUniformRng(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Xoshiro256StarStarUniformRng obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        QuantLibJNI.delete_Xoshiro256StarStarUniformRng(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Xoshiro256StarStarUniformRng(int seed) {
    this(QuantLibJNI.new_Xoshiro256StarStarUniformRng__SWIG_0(seed), true);
  }

  public Xoshiro256StarStarUniformRng() {
    this(QuantLibJNI.new_Xoshiro256StarStarUniformRng__SWIG_1(), true);
  }

  public SampleNumber next() {
    return new SampleNumber(QuantLibJNI.Xoshiro256StarStarUniformRng_next(swigCPtr, this), true);
  }

}
