/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.4.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.luopc.platform.quantlib;

public class YearOnYearInflationSwapHelper extends YoYHelper {
  private transient long swigCPtr;
  private transient boolean swigCMemOwnDerived;

  protected YearOnYearInflationSwapHelper(long cPtr, boolean cMemoryOwn) {
    super(QuantLibJNI.YearOnYearInflationSwapHelper_SWIGSmartPtrUpcast(cPtr), true);
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(YearOnYearInflationSwapHelper obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void swigSetCMemOwn(boolean own) {
    swigCMemOwnDerived = own;
    super.swigSetCMemOwn(own);
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwnDerived) {
        swigCMemOwnDerived = false;
        QuantLibJNI.delete_YearOnYearInflationSwapHelper(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public YearOnYearInflationSwapHelper(QuoteHandle quote, Period lag, Date maturity, Calendar calendar, BusinessDayConvention bdc, DayCounter dayCounter, YoYInflationIndex index, CPI.InterpolationType interpolation, YieldTermStructureHandle nominalTS, Pillar.Choice pillar, Date customPillarDate) {
    this(QuantLibJNI.new_YearOnYearInflationSwapHelper__SWIG_0(QuoteHandle.getCPtr(quote), quote, Period.getCPtr(lag), lag, Date.getCPtr(maturity), maturity, Calendar.getCPtr(calendar), calendar, bdc.swigValue(), DayCounter.getCPtr(dayCounter), dayCounter, YoYInflationIndex.getCPtr(index), index, interpolation.swigValue(), YieldTermStructureHandle.getCPtr(nominalTS), nominalTS, pillar.swigValue(), Date.getCPtr(customPillarDate), customPillarDate), true);
  }

  public YearOnYearInflationSwapHelper(QuoteHandle quote, Period lag, Date maturity, Calendar calendar, BusinessDayConvention bdc, DayCounter dayCounter, YoYInflationIndex index, CPI.InterpolationType interpolation, YieldTermStructureHandle nominalTS, Pillar.Choice pillar) {
    this(QuantLibJNI.new_YearOnYearInflationSwapHelper__SWIG_1(QuoteHandle.getCPtr(quote), quote, Period.getCPtr(lag), lag, Date.getCPtr(maturity), maturity, Calendar.getCPtr(calendar), calendar, bdc.swigValue(), DayCounter.getCPtr(dayCounter), dayCounter, YoYInflationIndex.getCPtr(index), index, interpolation.swigValue(), YieldTermStructureHandle.getCPtr(nominalTS), nominalTS, pillar.swigValue()), true);
  }

  public YearOnYearInflationSwapHelper(QuoteHandle quote, Period lag, Date maturity, Calendar calendar, BusinessDayConvention bdc, DayCounter dayCounter, YoYInflationIndex index, CPI.InterpolationType interpolation, YieldTermStructureHandle nominalTS) {
    this(QuantLibJNI.new_YearOnYearInflationSwapHelper__SWIG_2(QuoteHandle.getCPtr(quote), quote, Period.getCPtr(lag), lag, Date.getCPtr(maturity), maturity, Calendar.getCPtr(calendar), calendar, bdc.swigValue(), DayCounter.getCPtr(dayCounter), dayCounter, YoYInflationIndex.getCPtr(index), index, interpolation.swigValue(), YieldTermStructureHandle.getCPtr(nominalTS), nominalTS), true);
  }

  public static YearOnYearInflationSwapHelper forDates(QuoteHandle quote, Period lag, Date startDate, Date endDate, Calendar calendar, BusinessDayConvention bdc, DayCounter dayCounter, YoYInflationIndex index, CPI.InterpolationType interpolation, YieldTermStructureHandle nominalTS, Pillar.Choice pillar, Date customPillarDate) {
    long cPtr = QuantLibJNI.YearOnYearInflationSwapHelper_forDates__SWIG_0(QuoteHandle.getCPtr(quote), quote, Period.getCPtr(lag), lag, Date.getCPtr(startDate), startDate, Date.getCPtr(endDate), endDate, Calendar.getCPtr(calendar), calendar, bdc.swigValue(), DayCounter.getCPtr(dayCounter), dayCounter, YoYInflationIndex.getCPtr(index), index, interpolation.swigValue(), YieldTermStructureHandle.getCPtr(nominalTS), nominalTS, pillar.swigValue(), Date.getCPtr(customPillarDate), customPillarDate);
    return (cPtr == 0) ? null : new YearOnYearInflationSwapHelper(cPtr, true);
  }

  public static YearOnYearInflationSwapHelper forDates(QuoteHandle quote, Period lag, Date startDate, Date endDate, Calendar calendar, BusinessDayConvention bdc, DayCounter dayCounter, YoYInflationIndex index, CPI.InterpolationType interpolation, YieldTermStructureHandle nominalTS, Pillar.Choice pillar) {
    long cPtr = QuantLibJNI.YearOnYearInflationSwapHelper_forDates__SWIG_1(QuoteHandle.getCPtr(quote), quote, Period.getCPtr(lag), lag, Date.getCPtr(startDate), startDate, Date.getCPtr(endDate), endDate, Calendar.getCPtr(calendar), calendar, bdc.swigValue(), DayCounter.getCPtr(dayCounter), dayCounter, YoYInflationIndex.getCPtr(index), index, interpolation.swigValue(), YieldTermStructureHandle.getCPtr(nominalTS), nominalTS, pillar.swigValue());
    return (cPtr == 0) ? null : new YearOnYearInflationSwapHelper(cPtr, true);
  }

  public static YearOnYearInflationSwapHelper forDates(QuoteHandle quote, Period lag, Date startDate, Date endDate, Calendar calendar, BusinessDayConvention bdc, DayCounter dayCounter, YoYInflationIndex index, CPI.InterpolationType interpolation, YieldTermStructureHandle nominalTS) {
    long cPtr = QuantLibJNI.YearOnYearInflationSwapHelper_forDates__SWIG_2(QuoteHandle.getCPtr(quote), quote, Period.getCPtr(lag), lag, Date.getCPtr(startDate), startDate, Date.getCPtr(endDate), endDate, Calendar.getCPtr(calendar), calendar, bdc.swigValue(), DayCounter.getCPtr(dayCounter), dayCounter, YoYInflationIndex.getCPtr(index), index, interpolation.swigValue(), YieldTermStructureHandle.getCPtr(nominalTS), nominalTS);
    return (cPtr == 0) ? null : new YearOnYearInflationSwapHelper(cPtr, true);
  }

  public SWIGTYPE_p_ext__shared_ptrT_YearOnYearInflationSwap_t swap() {
    return new SWIGTYPE_p_ext__shared_ptrT_YearOnYearInflationSwap_t(QuantLibJNI.YearOnYearInflationSwapHelper_swap(swigCPtr, this), true);
  }

}
