/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.luopc.platform.quantlib;

public class YoYInflationCurve extends YoYInflationTermStructure {
  private transient long swigCPtr;
  private transient boolean swigCMemOwnDerived;

  protected YoYInflationCurve(long cPtr, boolean cMemoryOwn) {
    super(QuantLibJNI.YoYInflationCurve_SWIGSmartPtrUpcast(cPtr), true);
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(YoYInflationCurve obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void swigSetCMemOwn(boolean own) {
    swigCMemOwnDerived = own;
    super.swigSetCMemOwn(own);
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwnDerived) {
        swigCMemOwnDerived = false;
        QuantLibJNI.delete_YoYInflationCurve(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public YoYInflationCurve(Date referenceDate, DateVector dates, DoubleVector rates, Frequency frequency, DayCounter dayCounter, Seasonality seasonality, Linear interpolator) {
    this(QuantLibJNI.new_YoYInflationCurve__SWIG_0(Date.getCPtr(referenceDate), referenceDate, DateVector.getCPtr(dates), dates, DoubleVector.getCPtr(rates), rates, frequency.swigValue(), DayCounter.getCPtr(dayCounter), dayCounter, Seasonality.getCPtr(seasonality), seasonality, Linear.getCPtr(interpolator), interpolator), true);
  }

  public YoYInflationCurve(Date referenceDate, DateVector dates, DoubleVector rates, Frequency frequency, DayCounter dayCounter, Seasonality seasonality) {
    this(QuantLibJNI.new_YoYInflationCurve__SWIG_1(Date.getCPtr(referenceDate), referenceDate, DateVector.getCPtr(dates), dates, DoubleVector.getCPtr(rates), rates, frequency.swigValue(), DayCounter.getCPtr(dayCounter), dayCounter, Seasonality.getCPtr(seasonality), seasonality), true);
  }

  public YoYInflationCurve(Date referenceDate, DateVector dates, DoubleVector rates, Frequency frequency, DayCounter dayCounter) {
    this(QuantLibJNI.new_YoYInflationCurve__SWIG_2(Date.getCPtr(referenceDate), referenceDate, DateVector.getCPtr(dates), dates, DoubleVector.getCPtr(rates), rates, frequency.swigValue(), DayCounter.getCPtr(dayCounter), dayCounter), true);
  }

  public DateVector dates() {
    return new DateVector(QuantLibJNI.YoYInflationCurve_dates(swigCPtr, this), false);
  }

  public DoubleVector times() {
    return new DoubleVector(QuantLibJNI.YoYInflationCurve_times(swigCPtr, this), false);
  }

  public DoubleVector data() {
    return new DoubleVector(QuantLibJNI.YoYInflationCurve_data(swigCPtr, this), false);
  }

  public DoubleVector rates() {
    return new DoubleVector(QuantLibJNI.YoYInflationCurve_rates(swigCPtr, this), false);
  }

  public NodeVector nodes() {
    return new NodeVector(QuantLibJNI.YoYInflationCurve_nodes(swigCPtr, this), true);
  }

}
