/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.luopc.platform.quantlib;

public class YoYInflationCoupon extends InflationCoupon {
  private transient long swigCPtr;
  private transient boolean swigCMemOwnDerived;

  protected YoYInflationCoupon(long cPtr, boolean cMemoryOwn) {
    super(QuantLibJNI.YoYInflationCoupon_SWIGSmartPtrUpcast(cPtr), true);
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(YoYInflationCoupon obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void swigSetCMemOwn(boolean own) {
    swigCMemOwnDerived = own;
    super.swigSetCMemOwn(own);
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwnDerived) {
        swigCMemOwnDerived = false;
        QuantLibJNI.delete_YoYInflationCoupon(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public YoYInflationCoupon(Date paymentDate, double nominal, Date startDate, Date endDate, long fixingDays, YoYInflationIndex index, Period observationLag, CPI.InterpolationType interpolation, DayCounter dayCounter, double gearing, double spread, Date refPeriodStart, Date refPeriodEnd) {
    this(QuantLibJNI.new_YoYInflationCoupon__SWIG_0(Date.getCPtr(paymentDate), paymentDate, nominal, Date.getCPtr(startDate), startDate, Date.getCPtr(endDate), endDate, fixingDays, YoYInflationIndex.getCPtr(index), index, Period.getCPtr(observationLag), observationLag, interpolation.swigValue(), DayCounter.getCPtr(dayCounter), dayCounter, gearing, spread, Date.getCPtr(refPeriodStart), refPeriodStart, Date.getCPtr(refPeriodEnd), refPeriodEnd), true);
  }

  public YoYInflationCoupon(Date paymentDate, double nominal, Date startDate, Date endDate, long fixingDays, YoYInflationIndex index, Period observationLag, CPI.InterpolationType interpolation, DayCounter dayCounter, double gearing, double spread, Date refPeriodStart) {
    this(QuantLibJNI.new_YoYInflationCoupon__SWIG_1(Date.getCPtr(paymentDate), paymentDate, nominal, Date.getCPtr(startDate), startDate, Date.getCPtr(endDate), endDate, fixingDays, YoYInflationIndex.getCPtr(index), index, Period.getCPtr(observationLag), observationLag, interpolation.swigValue(), DayCounter.getCPtr(dayCounter), dayCounter, gearing, spread, Date.getCPtr(refPeriodStart), refPeriodStart), true);
  }

  public YoYInflationCoupon(Date paymentDate, double nominal, Date startDate, Date endDate, long fixingDays, YoYInflationIndex index, Period observationLag, CPI.InterpolationType interpolation, DayCounter dayCounter, double gearing, double spread) {
    this(QuantLibJNI.new_YoYInflationCoupon__SWIG_2(Date.getCPtr(paymentDate), paymentDate, nominal, Date.getCPtr(startDate), startDate, Date.getCPtr(endDate), endDate, fixingDays, YoYInflationIndex.getCPtr(index), index, Period.getCPtr(observationLag), observationLag, interpolation.swigValue(), DayCounter.getCPtr(dayCounter), dayCounter, gearing, spread), true);
  }

  public YoYInflationCoupon(Date paymentDate, double nominal, Date startDate, Date endDate, long fixingDays, YoYInflationIndex index, Period observationLag, CPI.InterpolationType interpolation, DayCounter dayCounter, double gearing) {
    this(QuantLibJNI.new_YoYInflationCoupon__SWIG_3(Date.getCPtr(paymentDate), paymentDate, nominal, Date.getCPtr(startDate), startDate, Date.getCPtr(endDate), endDate, fixingDays, YoYInflationIndex.getCPtr(index), index, Period.getCPtr(observationLag), observationLag, interpolation.swigValue(), DayCounter.getCPtr(dayCounter), dayCounter, gearing), true);
  }

  public YoYInflationCoupon(Date paymentDate, double nominal, Date startDate, Date endDate, long fixingDays, YoYInflationIndex index, Period observationLag, CPI.InterpolationType interpolation, DayCounter dayCounter) {
    this(QuantLibJNI.new_YoYInflationCoupon__SWIG_4(Date.getCPtr(paymentDate), paymentDate, nominal, Date.getCPtr(startDate), startDate, Date.getCPtr(endDate), endDate, fixingDays, YoYInflationIndex.getCPtr(index), index, Period.getCPtr(observationLag), observationLag, interpolation.swigValue(), DayCounter.getCPtr(dayCounter), dayCounter), true);
  }

  public double gearing() {
    return QuantLibJNI.YoYInflationCoupon_gearing(swigCPtr, this);
  }

  public double spread() {
    return QuantLibJNI.YoYInflationCoupon_spread(swigCPtr, this);
  }

  public double adjustedFixing() {
    return QuantLibJNI.YoYInflationCoupon_adjustedFixing(swigCPtr, this);
  }

  public YoYInflationIndex yoyIndex() {
    long cPtr = QuantLibJNI.YoYInflationCoupon_yoyIndex(swigCPtr, this);
    return (cPtr == 0) ? null : new YoYInflationIndex(cPtr, true);
  }

  public CPI.InterpolationType interpolation() {
    return CPI.InterpolationType.swigToEnum(QuantLibJNI.YoYInflationCoupon_interpolation(swigCPtr, this));
  }

}
