/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.4.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.luopc.platform.quantlib;

public class ZeroCouponInflationSwapHelper extends ZeroHelper {
  private transient long swigCPtr;
  private transient boolean swigCMemOwnDerived;

  protected ZeroCouponInflationSwapHelper(long cPtr, boolean cMemoryOwn) {
    super(QuantLibJNI.ZeroCouponInflationSwapHelper_SWIGSmartPtrUpcast(cPtr), true);
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ZeroCouponInflationSwapHelper obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void swigSetCMemOwn(boolean own) {
    swigCMemOwnDerived = own;
    super.swigSetCMemOwn(own);
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwnDerived) {
        swigCMemOwnDerived = false;
        QuantLibJNI.delete_ZeroCouponInflationSwapHelper(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public ZeroCouponInflationSwapHelper(QuoteHandle quote, Period lag, Date maturity, Calendar calendar, BusinessDayConvention bdc, DayCounter dayCounter, ZeroInflationIndex index, CPI.InterpolationType observationInterpolation, Pillar.Choice pillar, Date customPillarDate) {
    this(QuantLibJNI.new_ZeroCouponInflationSwapHelper__SWIG_0(QuoteHandle.getCPtr(quote), quote, Period.getCPtr(lag), lag, Date.getCPtr(maturity), maturity, Calendar.getCPtr(calendar), calendar, bdc.swigValue(), DayCounter.getCPtr(dayCounter), dayCounter, ZeroInflationIndex.getCPtr(index), index, observationInterpolation.swigValue(), pillar.swigValue(), Date.getCPtr(customPillarDate), customPillarDate), true);
  }

  public ZeroCouponInflationSwapHelper(QuoteHandle quote, Period lag, Date maturity, Calendar calendar, BusinessDayConvention bdc, DayCounter dayCounter, ZeroInflationIndex index, CPI.InterpolationType observationInterpolation, Pillar.Choice pillar) {
    this(QuantLibJNI.new_ZeroCouponInflationSwapHelper__SWIG_1(QuoteHandle.getCPtr(quote), quote, Period.getCPtr(lag), lag, Date.getCPtr(maturity), maturity, Calendar.getCPtr(calendar), calendar, bdc.swigValue(), DayCounter.getCPtr(dayCounter), dayCounter, ZeroInflationIndex.getCPtr(index), index, observationInterpolation.swigValue(), pillar.swigValue()), true);
  }

  public ZeroCouponInflationSwapHelper(QuoteHandle quote, Period lag, Date maturity, Calendar calendar, BusinessDayConvention bdc, DayCounter dayCounter, ZeroInflationIndex index, CPI.InterpolationType observationInterpolation) {
    this(QuantLibJNI.new_ZeroCouponInflationSwapHelper__SWIG_2(QuoteHandle.getCPtr(quote), quote, Period.getCPtr(lag), lag, Date.getCPtr(maturity), maturity, Calendar.getCPtr(calendar), calendar, bdc.swigValue(), DayCounter.getCPtr(dayCounter), dayCounter, ZeroInflationIndex.getCPtr(index), index, observationInterpolation.swigValue()), true);
  }

  public ZeroCouponInflationSwapHelper(QuoteHandle quote, Period lag, Date maturity, Calendar calendar, BusinessDayConvention bdc, DayCounter dayCounter, ZeroInflationIndex index, CPI.InterpolationType observationInterpolation, YieldTermStructureHandle nominalTS) {
    this(QuantLibJNI.new_ZeroCouponInflationSwapHelper__SWIG_3(QuoteHandle.getCPtr(quote), quote, Period.getCPtr(lag), lag, Date.getCPtr(maturity), maturity, Calendar.getCPtr(calendar), calendar, bdc.swigValue(), DayCounter.getCPtr(dayCounter), dayCounter, ZeroInflationIndex.getCPtr(index), index, observationInterpolation.swigValue(), YieldTermStructureHandle.getCPtr(nominalTS), nominalTS), true);
  }

  public static ZeroCouponInflationSwapHelper forDates(QuoteHandle quote, Period lag, Date startDate, Date endDate, Calendar calendar, BusinessDayConvention bdc, DayCounter dayCounter, ZeroInflationIndex index, CPI.InterpolationType observationInterpolation, Pillar.Choice pillar, Date customPillarDate) {
    long cPtr = QuantLibJNI.ZeroCouponInflationSwapHelper_forDates__SWIG_0(QuoteHandle.getCPtr(quote), quote, Period.getCPtr(lag), lag, Date.getCPtr(startDate), startDate, Date.getCPtr(endDate), endDate, Calendar.getCPtr(calendar), calendar, bdc.swigValue(), DayCounter.getCPtr(dayCounter), dayCounter, ZeroInflationIndex.getCPtr(index), index, observationInterpolation.swigValue(), pillar.swigValue(), Date.getCPtr(customPillarDate), customPillarDate);
    return (cPtr == 0) ? null : new ZeroCouponInflationSwapHelper(cPtr, true);
  }

  public static ZeroCouponInflationSwapHelper forDates(QuoteHandle quote, Period lag, Date startDate, Date endDate, Calendar calendar, BusinessDayConvention bdc, DayCounter dayCounter, ZeroInflationIndex index, CPI.InterpolationType observationInterpolation, Pillar.Choice pillar) {
    long cPtr = QuantLibJNI.ZeroCouponInflationSwapHelper_forDates__SWIG_1(QuoteHandle.getCPtr(quote), quote, Period.getCPtr(lag), lag, Date.getCPtr(startDate), startDate, Date.getCPtr(endDate), endDate, Calendar.getCPtr(calendar), calendar, bdc.swigValue(), DayCounter.getCPtr(dayCounter), dayCounter, ZeroInflationIndex.getCPtr(index), index, observationInterpolation.swigValue(), pillar.swigValue());
    return (cPtr == 0) ? null : new ZeroCouponInflationSwapHelper(cPtr, true);
  }

  public static ZeroCouponInflationSwapHelper forDates(QuoteHandle quote, Period lag, Date startDate, Date endDate, Calendar calendar, BusinessDayConvention bdc, DayCounter dayCounter, ZeroInflationIndex index, CPI.InterpolationType observationInterpolation) {
    long cPtr = QuantLibJNI.ZeroCouponInflationSwapHelper_forDates__SWIG_2(QuoteHandle.getCPtr(quote), quote, Period.getCPtr(lag), lag, Date.getCPtr(startDate), startDate, Date.getCPtr(endDate), endDate, Calendar.getCPtr(calendar), calendar, bdc.swigValue(), DayCounter.getCPtr(dayCounter), dayCounter, ZeroInflationIndex.getCPtr(index), index, observationInterpolation.swigValue());
    return (cPtr == 0) ? null : new ZeroCouponInflationSwapHelper(cPtr, true);
  }

  public SWIGTYPE_p_ext__shared_ptrT_ZeroCouponInflationSwap_t swap() {
    return new SWIGTYPE_p_ext__shared_ptrT_ZeroCouponInflationSwap_t(QuantLibJNI.ZeroCouponInflationSwapHelper_swap(swigCPtr, this), true);
  }

}
