/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.luopc.platform.quantlib;

public class ZigguratXoshiro256StarStarGaussianRsg {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ZigguratXoshiro256StarStarGaussianRsg(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ZigguratXoshiro256StarStarGaussianRsg obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(ZigguratXoshiro256StarStarGaussianRsg obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        QuantLibJNI.delete_ZigguratXoshiro256StarStarGaussianRsg(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public ZigguratXoshiro256StarStarGaussianRsg(long dimensionality, ZigguratXoshiro256StarStarGaussianRng rng) {
    this(QuantLibJNI.new_ZigguratXoshiro256StarStarGaussianRsg(dimensionality, ZigguratXoshiro256StarStarGaussianRng.getCPtr(rng), rng), true);
  }

  public SampleRealVector nextSequence() {
    return new SampleRealVector(QuantLibJNI.ZigguratXoshiro256StarStarGaussianRsg_nextSequence(swigCPtr, this), false);
  }

  public long dimension() {
    return QuantLibJNI.ZigguratXoshiro256StarStarGaussianRsg_dimension(swigCPtr, this);
  }

}
